### ISSUE TITLE
Support for dotnet project requiring workload installation for builds

### ISSUE THREAD

**Issue by yamachu** [dependabot/dependabot-core#10117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

6.11.0.71

### Manifest location and content before the Dependabot update

https://github.com/yamachu/VoicevoxCoreSharp/blob/main/examples/MAUI/MAUI.csproj

### dependabot.yml content

https://github.com/yamachu/VoicevoxCoreSharp/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

If workload restore was required, run something like `dotnet workload restore` to verify dependencies in a build-enabled state.
Or, parse csproj without build and verify dependencies.

For example, a similar product that verifies dependencies without build is `dotnet-outdated`.

### Images of the diff or a link to the PR, issue, or logs

https://gist.github.com/yamachu/d3c978b554e74ac5fdc6a94ac6efab51

**Comment by jeromelaban** [comment]
Looking further into this, I'm getting messages like this one, same as the original poster:

```
/usr/local/dotnet/current/sdk/8.0.303/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: wasi-experimental [/tmp/package-dependency-resolution_QwqwLB/Project.csproj]
/usr/local/dotnet/current/sdk/8.0.303/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [/tmp/package-dependency-resolution_QwqwLB/Project.csproj]
```

And looking [at the .NET source](https://github.com/dotnet/sdk/blob/7ca2f7cf5dcb94cf852a964b2d003bbd4a684836/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportWorkloads.targets#L36,), it may be interesting to set the `IsDesignTime` property to avoid this error since the build is only interested in getting the packages dependency graph.

It would probably need to be set in that group:

https://github.com/dependabot/dependabot-core/blob/10e5c7c5c7fe7b822fdd233f2cda672eb50d5b13/nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs#L710-L715

**Comment by brettfo** [comment]
Good catch and thank you for filing the issue, it's now on our backlog.
