### ISSUE TITLE
Changing the lower bound on a requirement without being asked to do so is rude

### ISSUE THREAD

**Issue by mdellweg** [dependabot/dependabot-core#10130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python

### What you expected to see, versus what you actually saw

This test demonstrate exactly the old good and the new (at least by us) unwanted behaviour:

```diff
-              its([:requirement]) { is_expected.to eq(">=1.3.0,<1.6") }
+              its([:requirement]) { is_expected.to eq(">=1.5.0,<1.6") }
```

https://github.com/dependabot/dependabot-core/commit/47cd8fdfbf84307826e0d0085e675874c958494c#diff-2c26ae287011b080cc4582ed4ed3b3dbb2381d8790e58016abbc4a295c1a07b1L149-R149

### Images of the diff or a link to the PR, issue, or logs

This commit broke it:
https://github.com/dependabot/dependabot-core/commit/47cd8fdfbf84307826e0d0085e675874c958494c

**Comment by kbukum1** [comment]
Thank you for bringing this to our attention. We are currently looking into the issue and will address it as soon as possible.

**Comment by kbukum1** [comment]
Hi @mdellweg 

Just need to confirm a few details to better understand the issue:

1. Are you using the increase strategy for dependencies?
2. Do you have a lower bound specified for the library (e.g., ">=...")?

We made these changes following our guidelines. If you are using the increase strategy and have specified a lower bound for the library, we are currently updating it to the latest installed version as mentioned in our [versioning strategy](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy). Note that the changes are applied because this functionality wasn't working properly.

**Comment by mdellweg** [comment]
We do not have a strategy configured, and the feature was working perfectly until last week.
For library like projects, you really want the broadest possible statements about compatibility you can safely provide. And bumping the lower bound of a dependency is a breaking change. If that was needed for a new feature, or an important bugfix, it'd better be done by hand.
If you work on an app that will always be deployed in isolation, go use `~=` or `==` depending on your relative requirements of security and lazy.
And BTW, yes we run tests with the lower bound of dependencies.

**Comment by kbukum1** [comment]
@mdellweg , 

We did make changes for the lower bound with the increase strategy. Currently, we are reviewing the rules and will come up with a better solution . However, if you don't have a strategy configured and the current lower bound is not working as expected, I believe the `widening` strategy should work well since it doesn't make changes to the lower bound if the new version higher than lower bound and only increases the upper bound to up one major version.

**Comment by kbukum1** [comment]
Here is the document how to set strategy
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

**Comment by petrjasek** [comment]
imo the issue is that now it uses the increase strategy instead of widening which was automatically used before

**Comment by mdellweg** [comment]
Now python (pip) does not seem to allow the "widen" strategy. (I'm almost sure i saw it in the docs two days ago, but not anymore.)
What am I supposed to do now?

**Comment by kbukum1** [comment]
The changes of this PR are reverted in #10194. The versioning strategy needs to be re-planned, and a solution will be implemented according to the new plan.
