### ISSUE TITLE
No longer updatable

### ISSUE THREAD

**Issue by rajivshah3** [dependabot/dependabot-core#1138]
This is kind of like #439 but I'm not sure what the cause is. We received a [PR](https://github.com/iotaledger/trinity-wallet/pull/1336) for an update to `eslint`, but it was later closed with the message "Looks like eslint is no longer updatable, so this is no longer needed.". Is there something we did that impacted the PR?

**Comment by greysteil** [comment]
@feelepxyz can you take a look at this one? Looks related to our peer dependency checking logic.

**Comment by feelepxyz** [comment]
Yes taking a look!

**Comment by feelepxyz** [comment]
@rajivshah3 looks like this was closed due to `eslint-config-airbnb@16.1.0` having a peer requirement on `eslint@^4.9.0` so we can't update this until `eslint-config-airbnb` is updated. Done in this PR: https://github.com/iotaledger/trinity-wallet/pull/1423

Trying to figure out why this PR was opened in the first place as it should have been blocked due to this peer requirement.

**Comment by rajivshah3** [comment]
Ooh, I see. Thanks!
