### ISSUE TITLE
Closing of superseded merge requests

### ISSUE THREAD

**Issue by morpheus-87** [dependabot/dependabot-core#1159]
How can I configure dependabot, so that is closes superseded merge requests and deletes the corresponding branches?

**Comment by greysteil** [comment]
Are you using `dependabot-script` to run Dependabot on GitLab? Since that's just a script it doesn't have any knowledge of previously created PRs, so doesn't know how to supersede them. In future we'd like to bring Dependabot's full functionality to GitLab, but the script won't be the right place for that to live long-term.
