### ISSUE TITLE
Add grouped updates

### ISSUE THREAD

**Issue by anym0us** [dependabot/dependabot-core#1190]
Our company is migrating to Dependabot from another similar tool (Depfu).

One of the features we miss is grouped updates (when all available updates are merged into 1 PR). Here's how the option is configured for every repository in Depfu's settings (just for example):

<img width="763" alt="Screen Shot 2019-06-06 at 12 04 16 PM" src="https://user-images.githubusercontent.com/5333431/59020728-3f77f500-8853-11e9-8b09-104e0ab65c84.png">

**Comment by greysteil** [comment]
Thanks for the feedback @anym0us. We love what the Depfu folks did.

We don't have support for grouped updates yet, so if that's a feature you really need I recommend you stick with Depfu for now. We'll get there on it, but it's just not the way Dependabot currently works.

**Comment by frangio** [comment]
I'm really interested in this feature to reduce the number of Dependabot PRs. I see that the PR was pinned a month ago. Would it possible to clarify whether this is in the roadmap? Thanks!

**Comment by tuan-bui** [comment]
We're interested in this feature as it makes it a lot easier to view it all in one PR. Wondering when it is planned for release also, cheers!

**Comment by JeremyTX** [comment]
We're also interested in this feature. If there are any estimates, it would be much appreciated!

**Comment by RichiCoder1** [comment]
PR simplicity + less notification noise + less Github Actions minutes spent processing dep PRs :)

**Comment by rbright** [comment]
Beyond reduction of PR noise and build times, grouping would be valuable for libraries that need to be updated together for purposes of compatibility.

For example, updating a single AWS CDK package can lead to test failures due to API compatibilities with other CDK packages. Upgrading them all at once generally mitigates this issue.

Until update grouping is possible, we have to disable CDK auto-updates and apply them manually.

**Comment by mbrevda** [comment]
Same for react + react-dom - these always need to be updated in tandem.

**Comment by mockdeep** [comment]
I would love to see something like this. It could actually be really useful to have all minor/patch updates grouped in one PR, and separate PRs for major version updates.

**Comment by scottrobertson** [comment]
Grouping across directories would be amazing. Every time there is a release, we get one PR per directory, and it gets a bit crazy.

<img width="395" alt="Screenshot 2020-07-23 at 11 23 42" src="https://user-images.githubusercontent.com/68361/88276450-f8f38d00-ccd6-11ea-9296-368ad82d2ad9.png">

**Comment by jonathanong-houzz** [comment]
would love to see this for jest, babel, react, and storybook packages as they all use lerna and you generally need to update all the packages at once

**Comment by WyriHaximus** [comment]
Would love to see this. Having it grouped by vendor would be amazing, projects like Symfony tag all their packages at the same time so it rains updates, having all those combined into one PR saves us so much more time <3

**Comment by sandersiim** [comment]
Definitely would like to see this for babel and similar updates. We were using Renovatebot before, which did this nicely with "babel monorepo" updates.

**Comment by hackel** [comment]
I really hope this issue is being prioritized.  Since adding Dependabot, I've found it to actually be a productivity killer—the opposite of its intended use.  Instead of individually merging 10-15 PRs every other day, I've gotten in the habit of using it merely as an update notifier and manually updating dependencies myself in a single commit.  Even in this workflow it still causes a lot of spam in our list of pull requests, though.  Trying to look through the closed PR history becomes a real challenge.

**Comment by RichiCoder1** [comment]
That's essentially what we're considering now. Using dependabot as a vuln notifier, but actually manually managing updates or using `renovate`'s self-hosted mode with actions since it has grouping support.

**Comment by mozbhearsum** [comment]
I know this is a bit of a pile on at this point - but the other pain point I'd like to point out is how many CI cycles get wasted due to this. Every PR dependabot sends to a repo triggers CI. For those of us that prefer to group updates (or need to, often because of multiple dependencies needing to update at the same time), this means 50, 100, or even more CI runs that necessary can happen every single week.

**Comment by martingjaldbaek** [comment]
I was missing this feature too, so I created a GitHub workflow to automatically combine/group all Dependabot PRs together into a single PR. I figured others could benefit from it too, so I made it available here: https://github.com/hrvey/combine-prs-workflow

**Comment by JLLeitschuh** [comment]
Hi,

I was the one who recently [reported and disclosed the vulnerability in JUnit 4](https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp).

It seems that by doing so I've caused Depenabot **to generate over 290,000+ pull requests (and counting)**.
https://github.com/search?o=desc&q=Bump+junit+from+to+4.13.1+GHSA-269g-pwp5-87pp&s=&type=Issues

There are over 1,508,273+ usages of JUnit 4 according to the [GitHub Dependency Graph](https://github.com/junit-team/junit4/network/dependents?package_id=UGFja2FnZS0xNzk4NzY0ODY%3D).

Due to this vulnerability, one of the projects we maintain at Gradle ended up having 101 pull requests generated for it to fix each individual POM.xml file.
https://github.com/gradle/performance-comparisons/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+junit


There is absolutely no way that you can sanely merge 100+ pull requests using the GitHub UI currently. Thus, we were forced to create a seperate PR and close the 101 dependabot generated PRs.

We're not the only ones experiencing this issues, it is reflected on twitter by various others:

 - https://twitter.com/sormuras/status/1316010270590812160
 - https://twitter.com/headius/status/1316055330657243142?s=20
 - https://twitter.com/MarcNuri/status/1316067844602331136?s=20
 - https://twitter.com/CedricChampeau/status/1315918744036741120?s=20
 - https://twitter.com/olamy/status/1315908629954916352?s=20

---

IMHO, if dependabot is going to generate over 10 PRs against a single project for the same dependency, it should consolidate it into one PR with an optional command to explode the PR into individual PRs should the maintainer wish for that instead.

Something like `dependabot separate`

**Comment by neverendingqs** [comment]
For anyone looking for a Node alternative to this issue, I created a GitHub action that mimics what is asked here: https://github.com/neverendingqs/gh-action-node-update-deps.

It uses [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) and [hub](https://github.com/github/hub) to create a pull request with updates to all dependencies. It's not as feature-rich as dependabot, but leaving security updates enabled and running this weekly has been sufficient to keep my dependencies updated.

**Comment by AviVahl** [comment]
In several repositories (while not in others), dependabot started grouping `react` and `react-dom`:
https://github.com/wix/potato-bruce/pull/145

Is the dependabot team experimenting with this? Would be great to have a way to specify npm scopes that update together (@jest, @babel,etc.)

**Comment by ChrisCates** [comment]
I've written a potential spec here.

https://github.com/dependabot/dependabot-core/issues/2672

I'm not really sure what the status is on this feature. But it would be nice to have these updates in.

**Comment by wangyun1517** [comment]
We have introduced dependabot into my company's GHE. After some team start to use it, they complains a lot about the PR hells.

The group feature will make our life easier.

**Comment by fkirc** [comment]
I would prefer if grouping could be configured on a per-organization basis:

For example, I get a lot of PRs for `@types`-dependencies, e.g. `@types/node`, `@types/lodash` and so on.
Even in small projects like `attranslate`, I get quite a lot of `@types`-PRs: https://github.com/fkirc/attranslate/pulls?q=%40types+

Those `@types`-dependencies are not super-critical because they do not change any runtime-behavior, therefore it would be easy to merge multiple `@types`-dependencies in a single PR.
If I could configure a grouping for the `@types`-organization, then this would be already a huge help to reduce noise and overheads.


Of course, `@types` is not the only organization that is good for grouping.
For example, @stephanvierkant pointed out that `@symfony` could be a good grouping-candidate as well:
https://github.com/dependabot/dependabot-core/issues/2265#issuecomment-626533927

Therefore, it seems natural to make organization-grouping configurable instead of hardcoding a specific behavior.

**Comment by dudo** [comment]
I'd like to see "group patch updates", nested under "group minor updates", nested under "group major updates". I can't imagine most would use the major, but for hobby projects, maybe. Still seems like a simple config, and already plays well with the existing "auto merge" config.

**Comment by n1ru4l** [comment]
I also agree that updating should be configurable. E.g. all `@aws-cdk/*`-scoped packages are released at the same time. However, other scoped packages could be less dependant on each other.

**Comment by cecilemuller** [comment]
Personally what I miss most is a way to group in a single PR the update of a single dependency that is used in multiple package.json (instead of having one PR per package.json).

**Comment by vladkosinov** [comment]
The biggest pain we have that once you merge one PR you need to rebase (which is crucial to not get broken dependencies tree) others one by one and wait for tests to pass each time.

When you have, let's say, 6 PR from dependabot and your tests take ~10 minutes to merge all PRs you need to wait one hour. 

It could help if there would be an auto-merge feature to not struggle with merge manually, but dependabot lost it during the migration to GitHub: https://github.com/dependabot/dependabot-core/issues/1973 (and it's not an option to workaround this with GitHub Actions since we've got our own CI infrastructure)

dependabot's support for private registries is currently (https://github.com/github/roadmap/issues/67) vendor-locked to Github Packages, which is one of the main reasons pushed our company to migrate to GitHub packages. But since dependabot has **no auto-merge** and **no grouping** it's now faster and easier to bump dependencies locally than struggle with PRs rebasing hustle. This makes dependabot useless 😢

**Comment by n1ru4l** [comment]
One thing to add is that renovate can even detect packages that belong together that are not in the same repository or follow any organization scoping.

See https://github.com/dungeon-revealer/dungeon-revealer/pull/889 as an example.

**Comment by Anthchirp** [comment]
For information: https://github.com/github/roadmap/issues/133

**Comment by 0rvar** [comment]
> For information: https://github.com/github/roadmap/issues/133

@Anthchirp that is a completely unrelated and orthogonal feature.

**Comment by JLLeitschuh** [comment]
It's actually not unrelated, this roadmap item should actually alleviate some of this pain. Unfortunately, I can't say more at this time.

**Comment by ChrisCates** [comment]
> It's actually not unrelated, this roadmap item should actually alleviate some of this pain. Unfortunately, I can't say more at this time.

@JLLeitschuh, I agree, however the most important question is how the team at Github feels about all of this.

I'm only willing to give a hand because it's clear how beneficial these tools could be to the public... For example, the potential to integrate UIX buttons to generate dependabot configurations directly into the Github UI would be great for newer and casual developers.

However, these are features that need to be something Github is willing to accept. And we haven't heard from them for a while.

**Comment by thepwagner-smurf** [comment]
> I created a GitHub action that mimics what is asked here
> It's not as feature-rich as dependabot, but leaving security updates enabled and running this weekly has been sufficient to keep my dependencies updated.

Me too! These Actions also implement this request:
* https://github.com/thepwagner/action-update-go
* https://github.com/thepwagner/action-update-docker
* https://github.com/thepwagner/action-update-dockerurl

There's no detection, but dependencies can be grouped by regular expression - [sample](https://github.com/thepwagner/action-update-dockerurl/blob/main/.github/workflows/update.yaml#L27-L29). 
You can also set a "cooldown" period for particular groups, so the Action can be scheduled daily, without getting ~daily PRs  from projects like https://github.com/aws/aws-sdk-go/tags . I hadn't thought about grouping by the version diff (e.g. patch, minor, major), cool idea!

These actions are unsupported, but maybe a useful starting point.

**Comment by GaboFDC** [comment]
There is a lot of feedback from the community here but still no word from GitHub or maintainers.
A response would be appreciated, even if you say you are just considering it and may take really long to implement but at least some kind of reply would be nice.

**Comment by jurre** [comment]
> There is a lot of feedback from the community here but still no word from GitHub or maintainers.
> 
> A response would be appreciated, even if you say you are just considering it and may take really long to implement but at least some kind of reply would be nice.

Heya, maintainer (and Huber) here.

We'd like to support this, but it would currently indeed take really long to implement so we've not been able to prioritize it. It's on our radar and backlog but I'm not able to give a timeline for when it might land.

**Comment by rhymes** [comment]
I'm not sure how this happened but we got a grouped update from dependabot at Forem https://github.com/forem/forem/pull/11990 :

> Bumps flipper-ui, flipper-active_record and flipper. These dependencies needed to be updated together.

**Comment by mbj** [comment]
@rhymes Its very likely the dependencies that where bumped in your case where strongly connected and dependabot had no option to just bump all of them the same moment.

**Comment by jpbourgeon** [comment]
May I suggest a cumulative approach ?
Dependabot tries to merge dependencies updates in a targeted PR based on a criteria (dependabot dedicated PR, latest opened PR, SEMVER level major/minor/patch as suggested by @dudo, other way?) ; if the update is successfull it keeps stacking. If a specific dependency fails to merge, the PR is rolled back and a new PR is opened for manual investigation.

**Comment by Shane32** [comment]
It would seem that if a configuration option was available to specify which updates are grouped together, it would be able to serve both feature requests.  `*` should be supported as a wildcard character for convenience and to support grouping "all" as shown below.  (npm package names cannot contain the `*` character.)  Since dependencies are predetermined, Regex is not necessary and would overly complicate use.

For instance, to group react packages together and storybook packages together:

```yml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    group_updates:
      - packages:
        - react
        - react-dom
        - @types/react
        - @types/react-dom
      - packages:
        - @storybook/*
```

Or to group ALL updates in a weekly pull request, you'd just do this:
```yml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    group_updates:
      - packages: [*]
```

**Comment by wangyun1517** [comment]
We are crying for this!!!

**Comment by wangyun1517** [comment]
Fine, I have stopped crying and moved to Renovate.

**Comment by johnhunter** [comment]
Any update on this? It is particularly important for monorepo dependencies e.g. [storybook](https://github.com/storybookjs/storybook) with dependencies from a single monorepo that generate multiple PRs (which cause merge conflicts on package-lock files).

I'm loathed to move to a competitor but this feature has been coming soon for a couple of years now.

**Comment by jurre** [comment]
No update on the timeline, it's still something we'd love to support but realistically we won't have time for it in the next couple of months, so it's unfortunately not coming soon.

**Comment by edoardopirovano** [comment]
We would also find this feature very useful.

**Comment by BillWagner** [comment]
We're very interested in this feature as well. Details in #4119

**Comment by ferdicus** [comment]
> Fine, I have stopped crying and moved to Renovate.

Hey there @wangyun1517, 
how did Renovate turn out for you?  

Would like to get your review on the process :)

**Comment by nedrebo** [comment]
We had to disable Dependabot in our monorepo because of this issue. It opened 30+ PRs at the same time, bringing our CI to its knees.

For reference, this was the commit message:

```
Dependabot floods our CI with pull requests, one for each update.
Dependabot has an open issue for making only one PR:
See dependabot/dependabot-core#1190.

Disable dependabot until this issue is fixed. Note that this way of
fixing it was found in the documentation:
docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit.

Dependabot may still make PRs for security updates:

This option has no impact on security updates, which have a separate,
internal limit of ten open pull requests.

If that becomes problematic then we can instead generate
an empty dependabot.yml.

Made issue XYZ-123 to re-enable it in the future.
```

**Comment by asbjornu** [comment]
Now that _Dependabot_ is GitHub-native and _Dependabot Preview_ is phased out, I would love to have this feature. Just an example of why:

<img width="818" alt="Heaps of Dependabot pull requests" src="https://user-images.githubusercontent.com/12283/134636559-17df4132-b737-441a-925f-e3e64d1fe1d6.png">

😅

**Comment by sobolevn** [comment]
Yesterday I got my first grouped PR: https://github.com/wemake-services/kira-release/pull/101

Wow! 👍

**Comment by asbjornu** [comment]
@sobolevn, wow that looks great! How did you get that? I can't see anything special in your `dependabot.yml` file?

**Comment by levrik** [comment]
@sobolevn But that's not a new feature. All these dependencies are linking each other via peer dependencies. For example `react` and `react-dom` also usually update in 1 PR if there's a major bump due to peer dependencies.

**Comment by sobolevn** [comment]
No, just random.

**Comment by planetf1** [comment]
Really would like this feature too.

Each month we get hit with 60-80 PRs (part is because we are switching maven->gradle so we get double). 

Currently I manually create a PR & cherry-pick each commit, resolving conflicts as necessary/. I submit and then let dependabot auto-close so I've caught everything. That bunch will be tested together by our FVTs (in ci/cd). We also do at the beginning of a release cycle (monthly) to allow time for additional flushing out of issues

Any PR that breaks of course needs removing from the batch, along with potentially anything where the info looks dubious.

At least this cuts down on the pr/merge time, but still it is a little disruptive. 

I too would find support of batched updates really helpful

**Comment by rnorth** [comment]
In case anyone is interested, I created a quick extension for GitHub CLI that aims to make it slightly easier to deal with mass PRs from Dependabot. It aims to automatically produce a combined PR that groups together as many of the dependency bump PRs as possible, roughly replicating what many of us have been doing by hand.

The extension is here: https://github.com/rnorth/gh-combine-prs, and an example PR can be found [here](https://github.com/testcontainers/testcontainers-java/pull/4448). I won't promise that it's the greatest piece of code (it's fundamentally just a hacked-together bash script 😄), but hopefully it's useful for other people.

**Comment by WtfJoke** [comment]
@rnorth probably not intenational, but your repo is not accessible (typo or private repo?)   🙃

**Comment by rnorth** [comment]
@WtfJoke OMG, thanks for pointing that out. The repo was indeed private. How embarassing 😅

**Comment by martingjaldbaek** [comment]
Similar to rnorth, I also took matters into my own hands - I made a GitHub Workflow that uses git to combine the PRs opened by dependabot - you can trigger it from the Actions tab of your repo. By default it only combines branches where checks have passed - and you can also manually exclude branches by adding the 'nocombine' label to them. You can find it here: https://github.com/hrvey/combine-prs-workflow

Limitation: Because the workflow uses git's automerge, it comes with the same limitations as that - specifically, it tends to fail if the different PRs modify the same line in the .lock to something different - which tends to be the case when something is a shared dependency (e.g. A and B both depend on C, so the two branches bumping A and B both bump C to different versions, so the .lock file can't be auto-merged). So if all your dependencies are closely related (e.g. submodules in a bigger framework), my workflow likely won't help. But if they're mostly unrelated, like mine tend to be, then it can handle it quite well, and if you occasionally run into a problematic merge, you can exclude one of the problematic branches from the combined PR and then merge it separately afterward.

**Comment by hertzg** [comment]
For people who don't want to complicate their pipelines and are ok moving away from dependabot, Renovate bot has such a feature.

**Comment by WaKeMaTTa** [comment]
@hertzg people are asking for an renovate example YAML file in the comments above.

**Comment by subesokun** [comment]
@WaKeMaTTa Here's my generic Renovate config for grouping packages. It bundles all minor and patches + auto merges them. Major updates are still single PRs with no auto merge. Would love to see this kind of functionality as part of Dependabot because having a self-managed Renovate Bot comes also with some overhead.

```json
{
    "assigneesFromCodeOwners": true,
    "packageRules": [{
            "packagePatterns": ["*"],
            "updateTypes": ["minor", "patch"],
            "groupName": "all non-major dependencies",
            "groupSlug": "all-minor-patch",
            "automerge": true,
            "approvals_required": false,
            "labels": ["dependencies"]
        },
        {
            "packagePatterns": ["*"],
            "updateTypes": ["major"],
            "labels": ["dependencies", "breaking"]
        }
    ]
}
```

**Comment by HonkingGoose** [comment]
@subesokun You're using outdated properties for some Renovate config options. 😉 

Change:

- `packagePatterns` -> `matchPackagePatterns`
- `updateTypes` -> `matchUpdateTypes`

Updated Renovate config here:

```json
{
    "assigneesFromCodeOwners": true,
    "packageRules": [{
            "matchPackagePatterns": ["*"],
            "matchUpdateTypes": ["minor", "patch"],
            "groupName": "all non-major dependencies",
            "groupSlug": "all-minor-patch",
            "automerge": true,
            "approvals_required": false,
            "labels": ["dependencies"]
        },
        {
            "matchPackagePatterns": ["*"],
            "matchUpdateTypes": ["major"],
            "labels": ["dependencies", "breaking"]
        }
    ]
}
```

**Comment by subesokun** [comment]
Thanks for the hint (updated my example too) 👍  Getting the Renovate configs correct is not easy, a lot of trial and error.

**Comment by gbvanrenswoude** [comment]
This probably should be a priority since the theory of single PRs is great, the practically is not. Especially with frameworks that throw around package dependencies like hot candies like aws-cdk, there really should be an option for grouping. Until then, Renovate seems like a great option. I feel like Dependabot will lose traction with the community the longer this feature is not delivered, even tho it's being pushed by GitHub. If we can do anything to help out, please deliver some pointers.

**Comment by exvuma** [comment]
PM For dependabot here 👋🏼  If you'd like to monitor any future updates, please watch [the issue on the public roadmap](https://github.com/github/roadmap/issues/148). There are no plans for the immediate future since this is a complex problem to solve, but the request remains top of mind.

**Comment by jeffwidman** [comment]
Unlocking by request so that folks can upvote this as a feature request. 

Feel free to leave comments that meaningfully add to the conversation, but avoid comments like "bump" or "we need this" or "is there an update / ETA?" as they waste everyone else's time. 

At this time there is no ETA, but I will say we are _fully_ aware this is a high-value feature, and although it could be quarters or years away, I _do_ expect we will ship some sort of grouped update functionality at some point. Subscribe to this issue to get notified whenever that eventually happens.

**Comment by saiichihashimoto** [comment]
@jeffwidman definitely agree with not "bumping" the convo but it becomes unavoidable when a stale bot that goes off of activity will close the ticket otherwise.

**Comment by patrick91** [comment]
I don't think if this has been mentioned already, but I think it would be nice to have grouped updates by “topic”, for example I'd love to get grouped updates for dev dependencies, but not for prod ones. Or a group for types dependencies (for TS and Python)

**Comment by Plasma** [comment]
Grouped updates would definitely improve the usefulness of Dependabot, at the moment I’m updating dependencies manually ahead of Dependabots scheduled check to not have many PRs that aren’t mergable on their own, as dependencies rely on each other.

Perhaps an option to specify a set of wildcard namespaces (eg Amazon.*) that cause matching updates to be grouped together.

**Comment by sirosen** [comment]
There's a special case of grouped updates which seems simpler than a more configurable and generalized feature.

Many dependency managers, like bundler for ruby or poetry for python, pair "true requirements data" (`Gemfile`, `pyproject.toml`) with a generated lockfile (`Gemfile.lock`, `poetry.lock`) which pins the exact package versions. In this case, the update action could just be to run the relevant lockfile regeneration command (`bundler update`, `poetry update`).

Dependabot is already somewhat aware of lockfiles (`versioning-strategy: lockfile-only`). This could even be phrased as an alternative `versioning-strategy` value, e.g. `lockfile-only-grouped`.

**Comment by davidism** [comment]
Is there somewhere less noisy we can follow if we just want to know when some form of grouped updates is implemented?

**Comment by nbarbettini** [comment]
@davidism To my knowledge, this public roadmap item still represents this feature: https://github.com/github/roadmap/issues/148

**Comment by LeviPesin** [comment]
Not sure if somebody has already mentioned this, but it would be great to have a method for manually combining two Dependabot PRs (not enabling a "combine-all" option) - e.g. if libraries like `react` and `react-dom` have both updated (https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-596163915), or just two internal organization packages, updating from one API to another.

**Comment by fbartho** [comment]
I could be wrong, but it looks like Dependabot is now exploring the ability to have "Grouped" dependency updates.

https://github.com/microsoft/reactxp/pull/1389, https://github.com/microsoft/reactxp/pull/1384 and others!

**Comment by WyriHaximus** [comment]
Noticed the same thing. But maybe for security alerts only? Glad to see it happen :D

**Comment by LeviPesin** [comment]
It seems like it is only for group updating ancestor dependencies yet. But it is a good start nevertheless!!

**Comment by tresabhi** [comment]
What might the config file look like to opt into this? It doesn't have to be complicated:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    batching: grouped # individual / grouped / security-batched / etc. ...
```

**Comment by tomkerkhove** [comment]
I'd love to see this as well, this is a blocker for us

**Comment by darenmalfait** [comment]
> What might the config file look like to opt into this? It doesn't have to be complicated:
> 
> ```yaml
> version: 2
> updates:
>   - package-ecosystem: 'npm'
>     directory: '/'
>     schedule:
>       interval: 'weekly'
>     batching: grouped # individual / grouped / security-batched / etc. ...
> ```

I like that.

Either way, I hope something gets implemented soon.

**Comment by tomkerkhove** [comment]
This is an example of why this feature is important:
![image](https://user-images.githubusercontent.com/4345663/211249808-2a0e0605-ada6-447d-b16e-3ca44c75f4ba.png)

In .NET world, this will never work given they all need to be updated simultaneously.

**Comment by dave-yotta** [comment]
Yeah this needs to be much more configurable.  E.g. doesn't make sense to test updating MongoDB.Driver on 1/10 csproj without updating any other MongoDB.* pacakges within the same PR - it will simply fail to build.

**Comment by LeviPesin** [comment]
Same reason for me as well.

**Comment by nwalters512** [comment]
The lack of grouped updates means that we end up using a huge number of Actions minutes every time we merge a Dependabot PR, and the resulting queue of jobs means that our repo is essentially frozen for hours as we wait for the queue to clear. I ended up disabling rebasing in my repo, which I hope will help with this problem.

**Comment by jeffwidman** [comment]
A gentle reminder of [what I said previously](https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1315623277):

> Unlocking by request so that folks can upvote this as a feature request.
> 
> Feel free to leave comments that meaningfully add to the conversation, but avoid comments like "bump" or "we need this" or "is there an update / ETA?" as they waste everyone else's time.
> 
> At this time there is no ETA, but I will say we are fully aware this is a high-value feature, and although it could be quarters or years away, I do expect we will ship some sort of grouped update functionality at some point. Subscribe to this issue to get notified whenever that eventually happens.

The last eight comments on this ticket are effectively spam for everyone else who's subscribed to this ticket for updates... if this continues, I'll have to lock the issue again.

**Comment by nilekhc** [comment]
> Unlocking by request so that folks can upvote this as a feature request.
> 
> Feel free to leave comments that meaningfully add to the conversation, but avoid comments like "bump" or "we need this" or "is there an update / ETA?" as they waste everyone else's time.
> 
> At this time there is no ETA, but I will say we are _fully_ aware this is a high-value feature, and although it could be quarters or years away, I _do_ expect we will ship some sort of grouped update functionality at some point. Subscribe to this issue to get notified whenever that eventually happens.

@jeffwidman Let me know if I can help with testing if the feature is in works

**Comment by dave-yotta** [comment]
I think the strategy is not straight-forward.  Grouping everything in one PR would help, since the PR can be edited to revert some of the updates to get a partial set.

However configuration or UI to expiate this would really help e.g.

```
updateGroups:
   group1:
     - MongoDb*
     - System.Bson*
     - Stackexchange.Redis*
   group2:
     - Microsoft.CodeAnalysis*
   group3:
     - *
```

so that there are 3 potential PRs that could be opened at any one time.

**Comment by brcarp** [comment]
> However configuration or UI to expiate this would really help e.g.
> 
> ```
> updateGroups:
>    group1:
>      - MongoDb*
>      - System.Bson*
>      - Stackexchange.Redis*
>    group2:
>      - Microsoft.CodeAnalysis*
>    group3:
>      - *
> ```

@dave-yotta with YAML you can have nested/multidimensional arrays without having to name them, which would make maintaining such a configuration easier. For example:

```yaml
updateGroups:
  -
    - MongoDb*
    - System.Bson*
    - Stackexchange.Redis*
  - 
    - Microsoft.CodeAnalysis*
  -
    - *
```

**Comment by dave-yotta** [comment]
I'm just giving some gist...but I think named groups would be nice to see e.g. on the PR title.  Maybe the model gets deeper as there are other things possibly relevant such groups forward-looking:
```
updateGroups:
 - name: Databases
   frequency: .... other stuff
   patterns:
    - MongoDb*
.....
```
etc...

**Comment by levrik** [comment]
@brcarp But also quite unreadable IMO. I think named groups would be better.

**Comment by emilio-notable** [comment]
Hello &#x27;Miroslav,

Thank you for contacting us!  The Notable office is currently closed in observance of the Martin Luther King Jr. Holiday.

We will resume normal business hours on Tuesday, January 17th from 9am to 9pm EST and look forward to assisting you at that time.

Happy Holidays!

Best Regards,
The Notable Team

**Comment by tresabhi** [comment]
I forgot you could reply by email 💀

**Comment by PovilasKM** [comment]
Hi, we are currently in a similar situation as [bajtos](https://github.com/bajtos) above. Due to company reasons, we are moving from renovatebot to dependabot and we really miss the ability to group pull requests by scope in the same repository. 

For example, instead of having 5 pull requests that update patch versions of 5 different dependencies, causing builds for every PR and rebuilds after every merge, renovatebot was able to group them all into a single PR. In this case, we except patch versions to not break anything so we are much more lenient on testing them.
This would make dependabot much easier to use and wouldn't strain our pipeline as much.

**Comment by simonhaenisch** [comment]
At least a simple option to group all minor and patch updates into the same PR would be very helpful already.

**Comment by jeffwidman** [comment]
I'm going to lock this for now to spare the inboxes of folks who are subscribed primarily for updates.

**Comment by carogalvin** [comment]
👋🏻 Hey everyone, I'm the Product Manager for Dependabot Updates. If you would be interested in providing your feedback on Dependabot and answer a bunch of questions about how you use it today, please feel free to book a time on my calendar: https://calendly.com/carogalvin/30min

In particular, we are currently researching how Security Updates should behave for grouping, and recruiting for the private beta of grouped Version Updates in May. Please feel free to book a slot or email me at carogalvin[at]github.com if you're interested!

**Comment by carogalvin** [comment]
GREAT NEWS! In case you haven't seen it already, grouping rules for version updates is now in PUBLIC BETA which means you will be able to set up grouping rules for any repo now!

Since we are in public beta, you may notice some instability or changes in behaviour without notice. If you encounter any bugs, please file new issues for them and the team will take a look.

You can see the docs on how to set these up here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

If you have any feedback, please feel free to email me at `carogalvin@github.com` or set up a meeting with me by [picking a convenient time in my calendar here](https://calendar.app.google/YdAa1FZ1GFL3mWUF8).

**Comment by jurre** [comment]
We're working on adding support for grouping on SemVer levels, some details [here](https://github.com/dependabot/dependabot-core/issues/7795) which links to a form you can fill out for private beta access for the feature

**Comment by carogalvin** [comment]
FYI for anybody using groups, we discovered [this bug](https://github.com/dependabot/dependabot-core/issues/7830) that may result in you seeing multiple grouped and ungrouped PRs for the same updates. We're working on a fix now, and you can track the linked issue for updates.

**Comment by carogalvin** [comment]
Good news! Grouped updates for Dependabot version updates is officially generally available 🥳 

Read our blog post here: https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/
See the docs here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

With that, we will close this issue. Thanks everyone for your feedback!
