### ISSUE TITLE
Support for dependency updates in arbitrary configuration files

### ISSUE THREAD

**Issue by JimNero009** [dependabot/dependabot-core#1290]
Hello!

I was wondering what your feelings are around dependency bumping in configuration files, specifically for Continuous Integration/Continuous Deployment systems, but in principle for anything. As a specific example, in our company we use Drone (https://drone.io/), which works by reading a YAML file in a repository and executing the set of steps defined within it, each of which specifies a Docker image that the step should use to execute commands within. Because the file includes Docker images, in an ideal world we would like to have something that could parse these files and ensure that the images in those steps are up-to-date. This would be simple regex replacement.

Similarly, we have our own proprietary CD system that works by reading another YAML file. Again, this may contain Docker images that we would like to keep up to date across the company and could be solved by exactly the same mechanism.

Similar situations are true of other CI/CD systems like TravisCI, CircleCI etc, where again one generic bit of logic could work on all these different types of files.

What would therefore be awesome to have is a general 'file bumper' kind of bump in the core library. It would work something like this:

- Configure the bumper so that is looks for files with certain names
- Configure the bumper so that it knows what kind of things to bump and how to do so (Docker images with regex replacement, for example)
- Have that resolve the latest version of the thing it wants to bump and then replace it appropriately in a file

What are your thoughts on this? Is this something you feel belongs within the scope of dependabot? Have you considered this issue before? 

Many thanks,
Jim

**Comment by JimNero009** [comment]
Beginning work on what will probably be a simplified version of this here: https://github.com/dependabot/dependabot-core/pull/1447.

**Comment by rebelagentm** [comment]
@feelepxyz Do you know if we have considered something like this before?

**Comment by feelepxyz** [comment]
@JimNero009 thanks for your work on this. I don't think we want to bundle Drone support inside the Docker package manager as this usually means it becomes much harder to maintain a diverging set of features over time.

We should probably add each type of manifest file as it's own package manager but this is pretty involved and currently requires a lot of our time to fully understand a new package file format so that we can maintain and support it. This is also why we're so slow on reviewing PRs 😢 

Would love to make it easier to write external plugins that could be required inside the Dependabot config file and run against custom file formats. This will hopefully happen in the next 12 months or so if we manage to move Dependabot over to GitHub Actions.

**Comment by JimNero009** [comment]
Okay -- so internally, we will use the code as is (since this is a requirement for us) but the suggested action here is to wait until you can loop back round to creating a mechanism for external plugin contribution?

**Comment by infin8x** [comment]
Closing this as we don't expect to have the bandwidth to support arbitrary external plugins anytime soon.

**Comment by rmannibucau** [comment]
+1 to get support for dependabot on a drone instance
