### ISSUE TITLE
Dependabot php composer strange/wrong behaviour

### ISSUE THREAD

**Issue by b1rdex** [dependabot/dependabot-core#1348]
I have created a test repo to reproduce the problem: https://github.com/b1rdex/dependabot-composer-bug

As you can see in b1rdex/dependabot-composer-bug#2 (and other opened pull requests), dependabot tries to rearrange the order of some records and replaces emojis with `?`.
But when I run `composer update package-name` locally with composer 1.9.0 there are no such changes.

Such rearrange/emojis replacement breaks "auto-mergeability" in my setup because each opened pull request tries to change the same lines and that produces conflicts with local updates.

ps. I run dependabot on my self hosted Gitlab, but luckily issue is reproducible on GitHub too,

**Comment by fmasa** [comment]
AFAIK, composer.lock contains [content-hash](https://github.com/b1rdex/dependabot-composer-bug/blob/master/composer.lock#L7) key, so it cannot be "auto-merged" anyway. See https://github.com/composer/composer/issues/6929

**Comment by greysteil** [comment]
I get the same re-orderings and emoji removal when running locally with Composer 1.9.0 (running `composer update beberlei/assert --no-autoloader --no-scripts`). Perhaps these are changes that come in with Composer 1.9.0, rather than an issue with Dependabot?

**Comment by greysteil** [comment]
Looks like this is indeed an issue with Composer / Packagist: https://github.com/composer/composer/issues/8268

**Comment by b1rdex** [comment]
> AFAIK, composer.lock contains [content-hash](https://github.com/b1rdex/dependabot-composer-bug/blob/master/composer.lock#L7) key, so it cannot be "auto-merged" anyway. See [composer/composer#6929](https://github.com/composer/composer/issues/6929)

@fmasa content-hash field changes only on composer.json changes. If dependabot simply updates with no constraint change, then almost all merge requests are mergeable.

@greysteil thank you for the composer issue info.

**Comment by greysteil** [comment]
Picking this back up here after the discussion in https://github.com/composer/composer/issues/8268.

I'm not sure what to do here. https://github.com/b1rdex/dependabot-composer-bug/pull/2/files#diff-1da2c7edc898c70e5a79a9997c98ceccR9274 is definitely wrong, but I'm guessing [these lines](https://github.com/dependabot/dependabot-core/blob/master/Dockerfile#L6-L7) are in the Dockerfile for a reason. Further, since emoji aren't supported for me locally Dependabot would cause flapping for many people if it *didn't* convert them to question marks.

It's not ideal, but I think we're best off leaving things how they are here, unless there's a fix  possible in Composer.
