### ISSUE TITLE
Mentions in Changelog send notifications

### ISSUE THREAD

**Issue by jrjohnson** [dependabot/dependabot-core#1421]
Seems to be a recurrence of #427 except for Changelog summary. As an example this PR https://github.com/rdohms/chainlink/pull/36 mentions me in the Changelog section and I got notified about it

**Comment by feelepxyz** [comment]
@jrjohnson yes will take a look at fixing this!

**Comment by PombeirP** [comment]
Curiously, only the first part of the string up to the first code fence (```` ```registerLoader``` ````) seems to have been sanitized (see the `body` element in https://api.github.com/repos/rdohms/chainlink/issues/36). This seems to point to a bug in the logic in [`sanitize_links_and_mentions`](https://github.com/dependabot/dependabot-core/blob/5526fe9581edca610877f3cde46407e0073dd128/common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb#L35-L47), where instead of iterating through all the code fences, it considers everything after the start of the first code fence to be part of the code fence, and therefore ingests it as-is.

If I have some spare time I'll take a look into improving the unit tests to cover this scenario and fixing the implementation.

**Comment by feelepxyz** [comment]
@PombeirP yup nice find, I've got a fix here: https://github.com/dependabot/dependabot-core/pull/1426

**Comment by PombeirP** [comment]
Thanks @feelepxyz! I'll create a separate PR to handle an additional scenario with complex nested code fences too, to avoid false positives.

**Comment by jrjohnson** [comment]
Thank you!
