### ISSUE TITLE
Start using the Go module proxy

### ISSUE THREAD

**Issue by hmarr** [dependabot/dependabot-core#1437]
After [upgrading to Go 1.13](https://github.com/dependabot/dependabot-core/pull/1433) we had to [disable the module proxy](https://github.com/dependabot/dependabot-core/pull/1436), as it was causing issues with private dependencies.

If you want to use the Go module proxy with the checksum database (sum.golang.org), you need to set `GOPRIVATE` to any private import paths, as by default all modules will be verified with the checksum database.

Given this, we probably need to make `GOPRIVATE` user-configurable, as there's no easy way of figuring out which modules are private (other than trying to fetch them all and seeing which 404 / 410).

**Comment by mctofu** [comment]
We are now using the public Go module proxy: https://github.com/github/dependabot-updates/issues/2012

For Dependabot it's not user configurable but the following rules are used:
- If a registry is defined in `dependabot.yml` then the module proxy is not used (`GOPRIVATE=*`)
- For public repos the module proxy is used for all dependencies (`GOPRIVATE=`)
- For private repos the module proxy is not used for other dependencies with the same owner  (`GOPRIVATE=github.com/owner/*`)

**Comment by mahlunar** [comment]
Hi

When debugging an issue with our Github Dependabot integration I saw this issue.

We use a lot of internal go packages which are hosted in private repositories inside our Github organization. go modules are named as `go.company.com/<packageName>` but hosted at github.com/company/<packageName>. For this to work locally, we have configured the `GOPRIVATE` environment variable as follows: `export GOPRIVATE=go.company.com,github.com/company`

We have configured Dependabot with access to all the private go packages in our Github org.

What we observe is that during the Dependabot check, a new version is found. The private package is then being verified at https://sum.golang.org/lookup/ with a 410 GONE response which makes Dependabot fail its check.

Could this be related to the changes made here, as we are using module rewrites?

Let me know if I should create a new issue instead of writing here.

**Comment by dangogh** [comment]
Hi @mahlunar ..    I'm no longer in the position that led me to file this originally, so can't even try it out.  But since this is closed and your issue is not quite the same, a new issue would be best so you can describe exactly what you're seeing without any distraction from this one...

@dangogh

**Comment by mctofu** [comment]
@mahlunar: Yes, that does sound like it would be caused by this change. Thanks for the report of this use case!

A workaround would be to add a [git private registry](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#git) to your `dependabot.yml` which would restore the `GOPRIVATE=*` behavior. It doesn't currently matter what the url of the registry is but getting it to work with `https://go.company.com` may help in the future if we optimize `GOPRIVATE` to include registry urls.

Another solution could be to allow specifying a custom `GOPRIVATE` in `dependabot.yml`. To request that, it would be best to submit a new issue.
