### ISSUE TITLE
Possibility to set Python version?

### ISSUE THREAD

**Issue by milesgranger** [dependabot/dependabot-core#1455]
Problem :open_mouth: 
---
We use `pip-compile` on a project which uses Python 3.6.

When dependabot creates pull requests, it can miss a dependency if that project has conditional dependencies based on python version.

For example, `aiohttp` declares that `idna-ssl>1.0` is required for Python versions `<3.7`
https://github.com/aio-libs/aiohttp/blob/a89fff941fb8a9a185cf071409f90f0666fd3c9b/setup.py#L59

Therefore, it subsequently removes this pinned dependency from our `requirements.txt`, again, because it _would_ have been marked as a dependency if ran in a Python 3.6 environment. 

Solution :question: 
---
Perhaps I'm missing it, but couldn't spot where I could configure the Python version dependabot uses.

**Comment by rebelagentm** [comment]
@feelepxyz Thoughts?

**Comment by feelepxyz** [comment]
@milesgranger yes you can tell Dependabot to run with a specific python version by adding a `.python-version` file. Let us know if that solves the problem.

**Comment by craigds** [comment]
Can that be added to some docs somewhere? This is the third completely different solution I've found a maze of github issues. Hopefully this one works...

**Comment by mst-ableton** [comment]
Glad that there is a workaround for this. Just throwing my two cents in: it would be really nice to specify this in either `pyproject.toml` or `setup.cfg`!

**Comment by craigds** [comment]
Not sure this always works - we've got an old python 2 app, and it seems like dependabot is scanning with python 3.8 despite the presence of a `.python-version` with `2.7` in it.

Maybe they don't support python 2 any more, which'd be fine if it _errored_ with some kind of message, but it keeps trucking and just silently picked the wrong version

**Comment by feelepxyz** [comment]
@craigds you'll have to set the version matching one of the available versions exactly, listed here: https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/python_versions.rb#L12-L17

Working on improving the docs on this.

**Comment by ssbarnea** [comment]
Can anyone confirm that this trick also works for the github dependabot? I find it very weird not to be able to configure that inside https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem and having to touch a file that affects developer machines that have pyenv. My default python is 3.10 not 3.6...., but I need dependabot to use 3.6,... not me.

**Comment by jurre** [comment]
> Can anyone confirm that this trick also works for the github dependabot?

Yes, it should work.

> My default python is 3.10 not 3.6...., but I need dependabot to use 3.6,... not me.

Why do you need dependabot to be different from what you use locally or in CI? Trying to understand the use case here and see if I can offer possible work-arounds.

**Comment by gschaffner** [comment]
I can't speak for @ssbarnea, but my team has a similar requirement. We work on a library that supports Python >= 3.7, < 3.11. This library does not define a `setup.py` and instead specifies a build system per PEP 517/518. Dependabot needs to use 3.7 since all pinned dependencies must support 3.7 at minimum. (Ideally one could specify to Dependabot a range of Python versions that dependencies must be compatible with, e.g. `>= 3.7, < 3.11`. This is off topic, but does Dependabot currently handle this syntax when it inspects a `setup.py` that uses `setuptools`?)

Each developer, on the other hand, can configure their Python environment for working on this library however they like, and this may involve setting a custom `.python-version`. E.g. Alice may specify `3.8.12` while Bob may specify a pyenv-virtualenv `myvenv` and fallback to `system` for access to globally-installed tools. We can't commit `.python-version` to version control since each developer may have their own `.python-version`, so we had to add a `runtime.txt` in order to configure Dependabot.

**Comment by jurre** [comment]
Thanks @gschaffner that makes a lot of sense.

Using `runtime.txt` seems like the right approach here, I would prefer to avoid adding anything to the dependabot config file for this sort of thing when there are solutions native to the ecosystem available.

I'll add a note on our backlog to improve documentation around this, because I agree that it's currently not easy to figure this out.

**Comment by ssbarnea** [comment]
@jurre Thanks for the update. IMHO adding option to dependabot.yml would be far better than all the other config files basically because all of them may be used for other purposes. A second reason for it is that it would be very hard for you to validate dependabot config if that validation relies on multiple files. Imagine addition on new value or removal of possible value, which could easily be made using a JSON schema (like github action already use, even on the live editor). Still, I am sure that doing this would require more engineering effort than just updating the docs to mention `runtime.txt` and possible values that can be used there.

**Comment by webknjaz** [comment]
@jurre

> Using `runtime.txt` seems like the right approach here, I would prefer to avoid adding anything to the dependabot config file for this sort of thing when there are solutions native to the ecosystem available.

While this may be acceptable for projects that target only one Python version, it is problematic for those needing to support different interpreters. I don't see how having a config-level mapping would help for as long as it only supports setting directories and not individual files. But using filenames/comments in the files could be a reasonable place for this type of metadata/hints.

P.S. `runtime.txt` is not an ecosystem-native thing, it's actually Heroku-specific and I haven't heard of many projects using it in other contexts.

**Comment by aciba90** [comment]
https://github.com/dependabot/dependabot-core/issues/1455#issuecomment-567951224
> @craigds you'll have to set the version matching one of the available versions exactly, listed here: https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/python_versions.rb#L12-L17
> 
> Working on improving the docs on this.

Is this documented somewhere? I did not find it anywhere.

Just for other people trying to set up the minimum python version, the `.python-version` file must only contain the version and not any comment line.

**Comment by jeffwidman** [comment]
> Is this documented somewhere? I did not find it anywhere.

It's not documented, and in fact it no longer works that way. We changed the python detection logic a few months ago when we stopped downloading python versions on the fly and instead pre-package a handful of them in the Dockerfile for speed reasons... 

Now, you no longer have to match the patch version exactly, but instead Dependabot now extracts the minor version that you've pinned to, and then Dependabot uses the latest patch version of that minor version release... 

> Just for other people trying to set up the minimum python version, the `.python-version` file must only contain the version and not any comment line.

Oof, we shouldn't be that brittle. Can you please file a new issue here in `dependabot-core` for that?

**Comment by aciba90** [comment]
Thanks, @jeffwidman.

> > Is this documented somewhere? I did not find it anywhere.
> 
> It's not documented, and in fact it no longer works that way. We changed the python detection logic a few months ago when we stopped downloading python versions on the fly and instead pre-package a handful of them in the Dockerfile for speed reasons...
> 
> Now, you no longer have to match the patch version exactly, but instead Dependabot now extracts the minor version that you've pinned to, and then Dependabot uses the latest patch version of that minor version release...

Are there plans to document it?

> > Just for other people trying to set up the minimum python version, the `.python-version` file must only contain the version and not any comment line.
> 
> Oof, we shouldn't be that brittle. Can you please file a new issue here in `dependabot-core` for that?

https://github.com/dependabot/dependabot-core/issues/6650 created.

**Comment by jeffwidman** [comment]
No, I don't see a need to document it.

It's an implementation detail which generally works, and for those who are really interested they can search the issue tracker and find this or they can check the source code itself.

**Comment by ssbarnea** [comment]
> No, I don't see a need to document it.

Undocumented features that have notable impact are risky, but in this case very bad, because adding a `.python-version` file might impact other tools in an undesired way.

**Comment by SMoraisAnsys** [comment]
I've tried to use the `.python-version` file and assumed that dependabot would be using the associated version to propose new releases. However, I gave it a try and it didn't behaved as I expected it to.

Here is an example of a project where, at the time were I post, I would expect a PR to be opened to bump the version of `matplotlib` from the range `>=2.5,<3.9` to `>=2.5,<3.11` (latest release being [3.10.3](https://pypi.org/project/matplotlib/3.10.3/)). However, since my project is compatible with python >=3.8, a PR is opened with range `>=2.5,<3.10` instead. I'm assuming that the reason if because the python version used is 3.9.22 while the latest releases of `matplotlib` are only compatible with python `>3.10`.
Here is the workflow run https://github.com/SMoraisAnsys/pyaedt/actions/runs/15999170337/job/45129574321
Despite specifying `3.10` in the python version file, I can't end up with the expected version range bump.

@feelepxyz @jeffwidman Am I missing something or could this issue be opened again ?

**Comment by SMoraisAnsys** [comment]
I think this issue should be reopened as using a .python-version file is not working.

**Comment by dpprdan** [comment]
I agree with @SMoraisAnsys and think that dependabot should support explicit python `version` and `version-file` config settings for the python ecosystem. See my https://github.com/dependabot/dependabot-core/issues/13858#issuecomment-4386351833 for details.

**Comment by LordFckHelmchen** [comment]
We have a hard Python pin to 3.12.9 - both specified in `requires-python = "==3.12.9"` as well as a `.python-version` with the exact same pin (which we hoped would solve the dependabot issue - which it didn't). It still fails due to the resolution to the latest patch-level and not the exact version. It was working before the "speed" enhancement.

**Comment by webknjaz** [comment]
@LordFckHelmchen it's sorta never gonna work with a generic service like dependabot. It can't give you enough control because of the limitations they're willing to be dealing with. If you're up for tradeoffs, you can run pip-tools directly (instead of replying on the limited way of how Dependabot does that anyway), have little infra of your own with more control of what you really need. You could also try sticking a small `-c hard-pins.in` on top of your main `.in` file restricting the transitive dep to exactly what you require.

Personally, I've been doing the mix of GHA+tox+pip-tools creating bump PRs with a bunch of per runtime "DIY lock files". It's a different kind of maintenance burden but at least it does exactly what I want it to be doing.
