### ISSUE TITLE
Possibility to randomize assignees of a PR?

### ISSUE THREAD

**Issue by joberget** [dependabot/dependabot-core#1482]
Is it possible to randomize assignee from a list of users from a group or list of users in default_reviewers or default_assignees?

**Comment by rebelagentm** [comment]
@feelepxyz Do you know the answer to this?

**Comment by feelepxyz** [comment]
@rebelagentm @joberget we're tracking a similar issue here: https://github.com/dependabot/feedback/issues/126 and still blocked on the permission to read org members. I'm wondering if it would be easier to write a GitHub action that would randomly set assignees on dependabot PRs instead of it being a Dependabot feature?

**Comment by rebelagentm** [comment]
Thanks for chiming in, @feelepxyz!  Since this is a duplicate request, I'm going to close this issue out.  I copied your @feelepxyz's comment over there.

@joberget You can track this in the earlier issue that @feelepxyz referenced.
