### ISSUE TITLE
write a custom message on the PR thread

### ISSUE THREAD

**Issue by oreporan** [dependabot/dependabot-core#1529]
Great library! great work!

We're using a merge bot [Miro](https://github.com/Soluto/Miro), which merges PRs that write a message `miro merge` on the PR thread (after CI passes).

I was wondering if it would be possible to config `dependabot` to write some custom message on the PR thread, apart from the original commit description.

Just to clarify, by PR thread I mean the same place where I give dependabot comands like `@dependabot rebase`

**Comment by CAD97** [comment]
This would be quite useful for [bors](https://bors.tech/) as well, which is widely used in the Rust ecosystem. For bors specifically, because it gates on CI passing on the `staging` branch rather than the PR itself, merging via bors can be semantically different from just "merge when green and up to date", because the `staging` branch can run different CI checks.

**Comment by mwaddell** [comment]
Now that we have `dependabot/fetch-metadata` you should be able to do that with a custom github action

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#common-dependabot-automations

**Comment by jeffwidman** [comment]
Yep, exactly what @mwaddell wrote ☝️.
