### ISSUE TITLE
Incorrect PR on xstream vulnerablilty

### ISSUE THREAD

**Issue by mteodori** [dependabot/dependabot-core#1531]
the related security alert was showing an update from xstream from 1.4.10 to 1.4.11 was needed but the automated PR did update to 1.4.10-java7

https://github.com/Activiti/activiti-cloud-service-common/pull/228

**Comment by brrygrdn** [comment]
Thanks for getting in touch about this @mteodori - I've investigated and I believe this is a bug specific to the [Automatic Dependency Update](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates) feature rather than specific to the Dependabot Core project.

I've raised an issue internally to follow up on this bug and fix it in our integration.
