### ISSUE TITLE
How do I pin a package to a specific version?

### ISSUE THREAD

**Issue by nikolas** [dependabot/dependabot-core#1550]
In [pyup](https://pyup.io/), I can pin a package by doing this:

```
Django==2.2.7  # pyup: <3.0
```

How do I do this in dependabot?

**Comment by rebelagentm** [comment]
@feelepxyz Is this supported in Dependabot?

**Comment by nikolas** [comment]
... apparently not. >_<  well, I will add it to my TODO list.

**Comment by feelepxyz** [comment]
@nikolas yep, there's currently no way to pin unless you pin all versions to the version requirement in your manifest file by setting `version_requirement_updates: off` in your config file (or "lockfile only" using the dashboard UI). You'll need to update the requirement to something like `Django>=2,<3` if you want similar behaviour.

**Comment by nikolas** [comment]
Ah okay, well doing something like `Django>=2,<3` works too. Thx.

**Comment by infin8x** [comment]
Closing this due to age and low demand. If this scenario is critical to your workflow please feel free to comment.

**Comment by fvaillancourt** [comment]
Given that SixLabors ImageSharp and Fluent Assertions (and probably others) went from free open source to paid commercial projects, it would be nice to be able to pin them. Repeatedly suggesting that we update them to a paid version is just evil.
In VS and Rider we can add square brackets around the version number to stop them from suggesting updating them, I don't see that as difficult to implement on your side ...

**Comment by legrab** [comment]
> in VS and Rider we can add square brackets around the version number to stop them from suggesting updating them

We use central package management via Directory.Packages.props file as well.
There we already pin versions such as the example below to match the reference to FluentAssertions:
`    <PackageVersion Include="FluentAssertions" Version="[7.0.0]" />`
This works for IDEs and I wondered why it wouldn't for dependabot.

I would reckon this is a basic feature that's there, but apparently, it is not getting recognized as a pinned version by dependabot and we still get update PRs.
I know we can add an ignore to the dependabot.yml, but that brings redundancy and a nightmare to maintain if we use dozens of pinned package versions.

Is this really not supported still, or do we need to use a different syntax maybe? like `[7.0.0, 7.0.0]` as a range would work better?

**Comment by kaylumah** [comment]
I tried using `<PackageVersion Include="FluentAssertions" Version="[7.0.0, 8.0.0)" />` and still see logs like 

2025-03-27T10:12:41.0971699Z updater | 2025/03/27 10:12:41 INFO <job_987819133> Latest version is 8.2.0
2025-03-27T10:12:41.0977808Z updater | 2025/03/27 10:12:41 INFO <job_987819133> Requirements to unlock all
2025-03-27T10:12:41.0978680Z updater | 2025/03/27 10:12:41 INFO <job_987819133> Requirements update strategy 
2025-03-27T10:12:41.1008490Z updater | 2025/03/27 10:12:41 INFO <job_987819133> Updating FluentAssertions from 7.0.0 to 8.2.0

Instead of trying 7.2.0 which is the latest safe version to use
