### ISSUE TITLE
Changelog within PR

### ISSUE THREAD

**Issue by RoryMacDonald** [dependabot/dependabot-core#158]
We're running a trial of dependabot on some of the GOV.UK repos at the moment. Would you be open to us creating a PR for `dependabot-core` which pulls the dependancy changes into the PR creator, rather than linking out to the changesets?

It's something that we feel would be a better experience for PR reviewers and also addresses a risk around the changesets being edited in dependant repositories. Wanted to get your thoughts on this before we cut any code.

**Comment by greysteil** [comment]
Hey @RoryMacDonald - totally up for that. We think the Dependabot PR text is currently "quite good" but could definitely be better.

One thing to keep in mind (may or may not be relevant here): the `PullRequestCreator` and `MetadataFinder` classes must be safe to run in a non-isolated environment. That means you can't make calls to the `FileFetcher`, `FileParser`, `UpdateChecker` and `FileUpdater` classes from them, since those classes sometimes `eval` code from the internet, which is obviously unsafe.

Would love to see designs, and very open to PRs - I can't see nay reason why you guys would have different needs to any of our other users, so I think our interests should be 100% aligned 😄 .

**Comment by sfdye** [comment]
+1

**Comment by greysteil** [comment]
FYI, I'm working on this today and tomorrow. You'll start seeing commit and release note details embedded in some Dependabot PRs tomorrow morning, and changelogs will be embedded the morning after.

Thanks for the feedback!

**Comment by sfdye** [comment]
@greysteil Awesome news!

**Comment by greysteil** [comment]
This is done! 🎉

**Comment by sfdye** [comment]
Is it live? I take it will only take effect for new PRs?

**Comment by greysteil** [comment]
Yep, and will only take effect for new PRs.

**Comment by sfdye** [comment]
@greysteil Unfortunately I think there is a bug, the `commits` and compatibility badge are also collapsed inside the `changelog`.

**Comment by greysteil** [comment]
Can you send over a link? Doesn't look like that's happening on all PRs.

**Comment by sfdye** [comment]
@greysteil I can't, it's our private repo 😞 

But interestingly it's only happening for this PR, other PRs are not affected.
> Bump vue from 2.4.2 to 2.5.16

**Comment by greysteil** [comment]
Thanks - that should be enough for me to take a look at what's happening in Vue's changelog that could cause this!

**Comment by greysteil** [comment]
FYI, I hunted down that bug and squashed it. Was a bug in the way GitHub sanitize \<template> tags within blockquotes, which we're now working around.
