### ISSUE TITLE
Problem with version suffixes

### ISSUE THREAD

**Issue by bogaertg** [dependabot/dependabot-core#1676]
Hi,

I have two repositories on github with terraform modules : 

* [technical module](https://github.com/bogaertg/terraform-technical-module) (monorepo with all technical terraform modules)
  * technical-module-a
  *  technical-module-b

* [terraform-myapp-module](https://github.com/bogaertg/terraform-myapp-module) which reference severals technical modules.

```hcl
module "myApp1" {
source = "github.com/bogaertg/terraform-technical-module//technical-module-a?ref=v1.0.0-technical-module-a"
}
  
module "myApp2" {
source = "github.com/bogaertg/terraform-technical-module//technical-module-b?ref=v1.0.0-technical-module-b"
}
```
I release technical modules with suffix (each different for module) : 

Ex :   X.Y.Z-technical-module-a | X.Y.Z-technical-module-b

I have dependabot enabled on terraform-myapp-module. Dependabot suggest to [update](https://github.com/bogaertg/terraform-myapp-module/pulls) : 

* Bump myApp2 from 1.0.0-technical-module-b to 1.1.0-technical-module-b in /app
* Bump myApp1 from `1.0.0-technical-module-a` to `1.1.0-technical-module-b` in /app

I wouldlike dependabot check new version against a pattern with fixed suffixed.

* Bump myApp2 from X.Y.Z-technical-module-b to <whathever>-technical-module-b in /app
* Bump myApp1 from X.Y.Z-technical-module-a to <whathever>-technical-module-a in /app

Regards,

**Comment by bogaertg** [comment]
up ?

**Comment by bogaertg** [comment]
up ?

**Comment by jeffwidman** [comment]
👋 Sorry for the glacially slow response. The team was buried with the migration to GitHub and then a bunch of internal infrastructure changes, plus understaffed for a while.

This issue is over two years old and there's been a lot of changes/improvements to the Dependabot support for Terraform since then... Are you still able to repro this?

My guess is that it's still an active issue and requires a fix similar to https://github.com/dependabot/dependabot-core/pull/5560
