### ISSUE TITLE
Wrong dependency is shown in the commit message

### ISSUE THREAD

**Issue by tetienne** [dependabot/dependabot-core#1683]
Hi,

Since today, the commit message done by dependabot-preview is not correct anymore. The description and the title of the PR is OK.

Sorry, I don't have any direct link, as the repo is private.

![image](https://user-images.githubusercontent.com/8216238/74143174-9613ab00-4bfa-11ea-92bd-b94701085ffc.png)

![image](https://user-images.githubusercontent.com/8216238/74143198-a88de480-4bfa-11ea-8bde-866eba4b5ce8.png)

In the above screenshot, you can compare both.

**Comment by darora** [comment]
This still seems to be happening (example attached), and causes automation based on dependency metadata to be incorrect (e.g. a major version bump is incorrectly merged because the description says it's a patch version update)

<img width="1802" alt="image" src="https://user-images.githubusercontent.com/397622/163492531-b3e1865a-2aa6-42fa-8af4-018cf61f5026.png">
