### ISSUE TITLE
Docker image not updated

### ISSUE THREAD

**Issue by hazcod** [dependabot/dependabot-core#1815]
**Package manage/ecosystem**
docker
**Manifest contents prior to update**
http://github.com/ironPeakServices/iron-cockroachdb/blob/master/Dockerfile
**Updated dependency**
none
**What you expected to see, versus what you actually saw**
update cockroachdb/cockroach to latest tag.
I had to manually update the. tag in https://github.com/ironPeakServices/iron-cockroachdb/commit/d5c691a14815f56f99b3fb5a03015f5a68cb8be5
**Images of the diff or a link to the PR, issue or logs**
https://app.dependabot.com/accounts/ironPeakServices/update-logs/30761688

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is over two years old, from before Dependabot ran on GitHub's infra, so things have changed a lot since then. Unfortunately, the logs are long since gone, so there's not much to go on here.

I'm going to close, but if you're still seeing this when running on the current Dependabot code / infra, please file an issue and we'll do our best to be a lot quicker to respond.
