### ISSUE TITLE
How to add a new SecurityAdvisory

### ISSUE THREAD

**Issue by masahiro331** [dependabot/dependabot-core#1857]
Thank you good product.

I want to add a new vulnerability source to dependabot.
For example, if I want to add golang vulnerability detection, should I implement dep/lib/dependabot/dep/metadata_finder.rb?

Deep respect for this product and its developers.

**Comment by jeffwidman** [comment]
If you want to wire this up yourself and then send the alerts to `dependabot-core` it's going to be complex... there's an issue or two in the archives here documenting it.

But if you're running on GitHub.com cloud, then you're probably looking to extend the GitHub advisory database: https://github.com/advisories

I'm going to close as given this issue is over two years old I doubt it's still relevant, but if you still need help leave a comment and we can reopen.
