### ISSUE TITLE
Yarn workspace files not getting identified for azure devops

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#1888]
In file_fetcher.rb in npm_and_yarn, while fetching the various yarn workspace package.json files, expanded_paths function is called for identifying the various package.json in the workspaces folder. In this method, there is one step where it does a regex match of the path of the fetched file with workspaces folder regex. For azure, this path value is the relative path of the package.json file with respect to the workspaces root whereas the expanded_paths function expects this path to be relative to the repo root because of which the workspace files are not getting identified

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is over two years old, from before Dependabot ran on GitHub's infra, and the code paths have also changed a lot since then. 

Is this still a valid issue? If so, can you provide links to the relevant source code in `dependabot-core` so that I'm sure I'm looking at the same code path as you?

**Comment by jeffwidman** [comment]
Closing due to a lack of user response plus this code has been refactored a lot, such as the recent yarn v3 support so really not sure it's even relevant anymore. IF still an issue, comment and we can re-open.
