### ISSUE TITLE
Does dependabot support updating transitive dependencies in lockfiles?

### ISSUE THREAD

**Issue by felixfbecker** [dependabot/dependabot-core#191]
I couldn't find this on the features page.

**Comment by greysteil** [comment]
We'll automatically update a dependency's sub-dependencies whenever we update the main dependency, but we don't create PRs if it's just the sub-dependencies that need updating.

In future, I'd like to create updates for sub-dependencies if there are security alerts for them ([see this issue](https://github.com/dependabot/feedback/issues/53)). I'm waiting on GitHub for an API for their security alerts in order to do so.

**Comment by felixfbecker** [comment]
Thanks for the reply. That's too bad, would you take this as a feature request? Take this dependency for example:
- editor depends on language service
  - language server depends on parser

If there was a bug fix in the parser, that directly impacts the editor, but it won't cause a new release in the language server. Because the editor is bundling all its dependencies, we need a PR to update the lockfile of the transitive parser dependency.

**Comment by greysteil** [comment]
Happy to think on it. There are a couple of open issues around this (https://github.com/dependabot/feedback/issues/22 is the most relevant), so it's already on my radar - I'll update you here if/when I get to it.
