### ISSUE TITLE
Allow certain dependencies to be merged by Dependabot without following SemVer

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#1954]
We have a few internal Ruby dependencies that are private gem repos of ours on GitHub. It's really nice to be able to put a GitHub reference in a `Gemfile`:

```
gem "internal-gem", git: "https://<username>:<password>@github.com/our/internal-gem.git"
```

and have Dependabot automatically update the SHA hash in our `Gemfile.lock` whenever the repo is updated. We use this pattern a lot.

Unfortunately, Dependabot refuses to automatically merge any of these PRs:

```
Dependabot will not automatically merge this PR because this dependency doesn't follow SemVer.
```

It would save us a ton of time **if this was configurable or if we could override this behavior and have Dependabot automatically merge them**, because every week we see the same scenario:

1. Some linter or other minor development tool releases a new version. Dependabot makes a PR to update it in `internal-gem` and automatically merges it. (🎉)
2. Dependabot makes PRs to update `internal-gem` in dozens of our repos, but can't merge these automatically so a human has to. (😭)

**Comment by jeffwidman** [comment]
Closing, as we [aren't doing native automerge](https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-640918321), although there is a [workaround you can setup leveraging GitHub actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request). But since no default / native automerge, this issue isn't applicable anymore.
