### ISSUE TITLE
Migration to v2 of config files doesn't honour update schedule

### ISSUE THREAD

**Issue by gnarea** [dependabot/dependabot-core#1956]
See https://github.com/relaycorp/relaynet-pong/pull/85 for example. That repo uses live updates but the PR would change it to daily.

**Comment by vbuberen** [comment]
Can confirm this issue. 
Dependabot Preview works just fine on my own fork of the library I support, while Github native version worked only once when I just added v2 config into the repo a few weeks ago. 

Here is the config I use: https://github.com/ChuckerTeam/chucker/blob/develop/.github/dependabot.yml

Here is a list of PRs in the original repo: https://github.com/ChuckerTeam/chucker/pulls - no PRs from Dependabot last few weeks.
Here is a list of PRs for my fork: https://github.com/vbuberen/chucker/pulls, where Dependabot Preview created 2 PRs just yesterday.

**Comment by l0b0** [comment]
Any updates on this? This project has [configured](https://github.com/linz/geospatial-data-lake/blob/beb870c3070b97518610324625fbbb0a01e7b494/.github/dependabot.yml) pip upgrades to be weekly to reduce the noise from some packages updating every day, but we're still getting new PRs every day.

**Comment by asciimike** [comment]
@l0b0 I'm seeing it as being configured to weekly on our side. It's possible that you're getting security updates or that runs previously errored and are being re-run and thus creating PRs "out of schedule". We've got some info in the docs about this: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#scheduleinterval, https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates#about-version-updates-for-dependencies, though please let me know if this needs additional content.

I'm closing this issue since the original issue (`live` becomes `daily`) is WAI, and I'm tracking https://github.com/dependabot/dependabot-core/issues/3488, plus it looks like https://github.com/ChuckerTeam/chucker/pulls is getting Dependabot PRs again.
