### ISSUE TITLE
Add support to github project feature

### ISSUE THREAD

**Issue by wmitsuda** [dependabot/dependabot-core#1976]
Please add support to autoassign dependabot's PRs to a repository "project" (https://help.github.com/en/github/managing-your-work-on-github/about-project-boards), when it is available.

This way the PR can automatically appear in my project board and be classified to be triaged.

**Comment by SerenModz21** [comment]
this would be a nice feature to have because I currently have to leave them without a project or assign it manually. I have tried using a GitHub action to assign the project but when it comes to dependabot pull requests, it seems they get ignored. The action will finish successfully but no change to the pull request happens.

**Comment by jetersen** [comment]
With the new project beta this would be a great feature to have a project view with all pull request across org repos in one board view 😳🙌

**Comment by juliojgd** [comment]
This would be **crucial** for us, because when a PR is superseded by a new version of the same artifact, it disappears from the project board because the newly created PR (by dependabot) does not keep the project association.

So we had prioritized a dependabot PR in the project board, then a supersede occurs and you don't have it in the board 😢

**Comment by smcvb** [comment]
We would very much benefit from this feature as well.
It's not that we cannot select the project manually.
Nonetheless, the number of pull requests currently created by Dependabot (for which kudos, by the way) is such that it would most definitely save time if Dependabot does this for you.

**Comment by jetersen** [comment]
FYI: https://github.com/actions/add-to-project

**Comment by jeffwidman** [comment]
Thanks @jetersen, this is nifty, I didn't realize there was an official action for this!

Closing as the action is definitely a better way to go than us building it directly into Dependabot.
