### ISSUE TITLE
Dependabot won't create new labels via `default_labels` in `config.yml`

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#1978]
We just changed our `config.yml` to add a new label to `default_labels` and noticed that `dependabot-preview` wasn't adding it. It appears that it only works if the label already exists on the repo, which was surprising to us as we don't really manually use labels anywhere and `dependabot-preview` appears to have just been creating the `security` and `dependencies` labels in the past.

**Comment by joshuasimon-taulia** [comment]
dependabot really should create labels if they don't exist

**Comment by jurre** [comment]
> dependabot really should create labels if they don't exist. for instance, my CI (following the prow convention) won't start without the `ok-to-test` label

We create any of the default labels if they don't exist, but assume that custom labels that are configured are already present in the repo. What's the scenario where you're configuring dependabot to create labels that don't already exist?

**Comment by joshuasimon-taulia** [comment]
1. dependabot files a PR and is configured to apply the `ok-to-test` label
2. the `ok-to-test` label doesn't exist on the repository
3. since the PR was filed by an 'outside collaborator', the [CI system](https://github.com/kubernetes/test-infra/blob/master/prow/README.md) won't trigger the pull request job until it detects the `ok-to-test` label
4. a manual touch is required on 10+ dep PRs

multiply this by 50+ github repos

**Comment by jurre** [comment]
Maybe the CI system could ensure the labels exist and create them if they don't, using the GH api? Long-term I think https://github.com/github/roadmap/issues/276 might help here, I'm not sure if Dependabot is the best place for this to be handled, but I can see the reasoning for both sides.

Have tagged this as a feature request so we can consider it when planning, but I can't speak to if and when we might get to it.

**Comment by abdulapopoola** [comment]
Closing out as stale
