### ISSUE TITLE
[PHP] Update understood but no PR

### ISSUE THREAD

**Issue by waghanza** [dependabot/dependabot-core#1988]
Hi,

I have a `composer.json` in my project
https://github.com/the-benchmarker/web-frameworks/blob/d3077f9f6a03d49b4dc4652dd67076d691b10ac2/php/imi/composer.json#L3

In this file, there is `imi` at a version `1.0` and the bot detect that an update exists to `1.2`.

However, I have not any `PR` concerning it.

Regards,

LOG : https://app.dependabot.com/accounts/the-benchmarker/update-logs/30316379

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

This is a really old issue, from before Dependabot was integrated into native GitHub. We've shipped a lot of improvements since then, plus with time passing and people manually upgrading their packages, bugs like this tend to no longer be reproducible. So I'm going to close, but if for some reason I'm wrong and you're still affected/able to reproduce, please comment and we can reopen.

**Comment by deivid-rodriguez** [comment]
Checked the public repo just in the case and the issue is now fixed 💪.
