### ISSUE TITLE
bumped manually, but no PR

### ISSUE THREAD

**Issue by OskarStark** [dependabot/dependabot-core#199]
locally I got an update for this package:
```
Package operations: 0 installs, 1 update, 0 removals
  - Updating sebastian/comparator (2.1.0 => 2.1.1): Downloading (100%)
```

but no PR by dependabot. Maybe thats because it is not a direct dependency?

For Debugging, this is my composer.json|.lock:
https://gist.github.com/OskarStark/21ad0cb2c0001f417833f52f5ecd4bb0

**Comment by greysteil** [comment]
That's definitely going to be because it's not a direct dependency - at the moment, Dependabot will only update the dependencies listed in your `composer.json`.

There's a bit more discussion about this one [here](https://github.com/dependabot/feedback/issues/22) and [here](https://github.com/dependabot/feedback/issues/53) - current status is that I'm waiting on GitHub for access to their security alerts API (which doesn't exist yet). Longer term I'd love to create PRs for sub-dependencies on a less regular basis, and grouped together (since they should, by definition, be non-breaking). That's a way off though.

I'm going to close this here since I think it's covered by the issues linked, but feel free to continue the conversation here (or on those issues) if you've got more opinions on it. And thanks for the feedback!

**Comment by OskarStark** [comment]
Thanks for your feedback 👍
