### ISSUE TITLE
[Java] Version range not understood

### ISSUE THREAD

**Issue by waghanza** [dependabot/dependabot-core#1991]
Hi,

I've added https://github.com/tipsy/javalin framework to https://github.com/the-benchmarker/web-frameworks.

According to https://github.com/the-benchmarker/web-frameworks/blob/63422950ceba428840fca673fa93a9d73d90426a/java/javalin/pom.xml#L19, the version required is `3.6`

(I stick to https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402 as I have not knowledge of `java` practices).

However, according to the log bellow, the version understood by the **bot** is `3.8.1`, so it does not think an update is required (a **false positive**).

PR : https://github.com/the-benchmarker/web-frameworks/pull/2499
Log : https://app.dependabot.com/accounts/the-benchmarker/update-logs/30117187

Regards,

**Comment by jeffwidman** [comment]
👋 this is an old ticket, sorry for the glacially slow response.

From a quick skim, I think this is working as expected since:
https://github.com/the-benchmarker/web-frameworks/pull/2499/files#diff-a8ca5caa8ebb1c0cd5ae4c7d1823691526750f009b78709cd7d8920f9a34348aR19

specifies between 3.8 - 3.9 IIUC, and 3.8.1 is between those... But I can't see the logs as those are ancient, so I may be wrong, but that's what I think is happening.

I'm going to close, but if for some reason you think I'm wrong please comment and we can re-open.
