### ISSUE TITLE
dependabot only updates lock file

### ISSUE THREAD

**Issue by msallent** [dependabot/dependabot-core#1993]
Hello.

I'm using dependabot on 3 repositories where it works fine except on one of them, where the issue seems to be that it only updates the yarn.lock file, but not the package.json file.

The repository is being handled by Lerna and Yarn Workspaces, although one of the other repositores uses Workspaces and everything seems to be working great.

Repository is: https://github.com/msallent/gatsby-theme-skeleton

I read somewhere else that someone had a similar issue, and they fixed it by removing any symbol from the "name" key in package.json. Two of my package names have symbols because I'm publishing them to NPM scoped under my username (@msallent/....) so unfortunately, I can't rename them.

Could this be the reason of why it's failing? Any other ideas?

If more information is needed, I can provide what's needed. Thanks.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow followup.

This issue is very old, from back before Dependabot was acquired by GitHub.

Since then, we've completely rewritten the backend, although kept the internal package parsing library (this repo). We've also push a _lot_ of fixes since then.

It also looks like the repo mentioned int he original post is now gone: https://github.com/msallent/gatsby-theme-skeleton

So I'm going to close, but if you're still encountering this please file a new issue and we'll try to help you sort things out.
