### ISSUE TITLE
[Python] [Pipenv] Dependabot accidentally removes a package for the Windows environmen.

### ISSUE THREAD

**Issue by roy-n-roy** [dependabot/dependabot-core#2000]
If `"markers": "sys_platform == 'win32'"` is set in the Pipenv.lock file, Dependabot accidentally remove the package.
(I'm using Python and Pipenv on Windows 10.)

For example, like [this](https://github.com/roy-n-roy/roy-n-roy.github.io/pull/6/files#diff-46bb8405eeb4d8a11deb635f562f7c48L270-L277).
This removes the 'atomicwrites' dependency of 'pytest'.

```
-        "atomicwrites": {
-            "hashes": [
-                "sha256:03472c30eb2c5d1ba9227e4c2ca66ab8287fbfbbda3888aa93dc2e28fc6811b4",
-                "sha256:75a9445bac02d8d058d5e1fe689654ba5a6556a1dfd8ce6ec55a0ed79866cfa6"
-            ],
-            "markers": "sys_platform == 'win32'",
-            "version": "==1.3.0"
-        },
```

**Comment by AllanChain** [comment]
Seems pipenv issue: https://github.com/pypa/pipenv/issues/3702#issuecomment-484116975

**Comment by jeffwidman** [comment]
👋 sorry for the slow response.

This is a legit bug, but as pointed out above the issue is with underlying `pipenv`, not the Dependabot code... Dependabot is just the glue that grabs the manifest file and passes it to `pipenv`, so we respect whatever they return. I'm afraid there's nothing we can really do here other than if they do fix this we'll happily pull in that new release.
