### ISSUE TITLE
PRs not created besides dry run report show changes

### ISSUE THREAD

**Issue by pbarsotti-glovo** [dependabot/dependabot-core#2003]
I configured dependabot to use a private maven repository (artifactory) and the PRs are only being created for the dependencies from public repositories (maven central).
I checked the access logs on artifactory and I see dependabot downloading the metadata XMLs. Also tried a dry run (setting the private repo and my GH PAT) and the logs shows that the stale dependencies are detected OK.
I created a GH support ticket (#616306) but I got no response.
The repo where I'm testing this is https://github.com/Glovo/sample-service

Can you take a look an tell me if you see any problems from your side?

Thanks!

**Comment by jeffwidman** [comment]
👋 this is an old ticket, and it's not clear how to reproduce this anymore, so I'm going to close.

If for some reason this is still an issue, please re-ping on your support request... since it's a private repo and not reproducible with an open source repo a support ticket is a better fit than an issue here in core.
