### ISSUE TITLE
Add support for C# / NetStandard

### ISSUE THREAD

**Issue by deinok** [dependabot/dependabot-core#203]
Hi Guys, nice job with this.
Are you thinking about adding support for C# projects?

**Comment by greysteil** [comment]
Thanks @deinok!

We'd love to add C# support, but are currently blocked by our own expertise on it. If you'd like to help out I'd be totally up for working on it with you, but otherwise it's likely to be a bit of a wait.

There's an issue tracking this (and Java support, which I really need to get over the line...) at https://github.com/dependabot/feedback/issues/33, so I'm going to close this.

**Comment by deinok** [comment]
@greysteil Well, I can give with how to conceptualy do it but I don't think I can send a PR (Im dont know Ruby).

So I can writte the algorithm of how to check everything and you can "port" it to Ruby if you want.
Let me know it ;)

**Comment by greysteil** [comment]
Sounds good to me! Let me get the Java beta out and I'll hit you up with some questions / bits that need to be written in C#. :octocat:

**Comment by deinok** [comment]
Okey, tag me when you start working on it and i will give you a hand
