### ISSUE TITLE
Dependabot doesn't notify about broken dependencies

### ISSUE THREAD

**Issue by just-jeb** [dependabot/dependabot-core#2032]
Dependencies in my [repo](https://github.com/just-jeb/angular-builders) are not getting updated with new major versions.  

Example: [`jest: ^24.7.1`](https://github.com/just-jeb/angular-builders/blob/master/package.json#L40), latest is `25`, no PR created by dependabot.  

I think it started when I removed the lockfiles (I don't use them anymore) but I can't be sure.

**Comment by jdforsythe** [comment]
@feelepxyz 

We had a similar issue #4038 where a dependency that we release privately was not getting PRs to update because there was a new unmet peer dependency. There was no notification on GitHub, nor anything in the update logs saying that the update failed.

It would seem that you could open a PR to bump the dependency version and add the peer dependency. I get that CI might not catch errors, but if you opened it as a draft PR with a warning that it also adds a peer dependency, that would be great. At the very least, a GitHub notification saying that a PR could not be opened due to to a missing peer dependency would at least inform us that there is an issue that needs our attention, even if we have to manually intervene to add the peer dependency ourselves.

**Comment by just-jeb** [comment]
+1 one for opening a draft PR in such a case. The draft PR won't be merged automatically but the users will at least be aware that there's an issue.

**Comment by jeffwidman** [comment]
We've shipped a lot of improvements to peer dependency support over the last few months, so we may be able to succeed in more of these cases: https://github.com/dependabot/dependabot-core/pulls?q=is%3Apr+is%3Aclosed+peer+dependency

But the overall theme of notifying when there's an error is still unresolved. That's already tracked in https://github.com/dependabot/dependabot-core/issues/3509 as a more generic issue beyond peer dependencies so I'm going to close this as a duplicate.
