### ISSUE TITLE
Dependabot reporting on deleted files

### ISSUE THREAD

**Issue by davidpustai** [dependabot/dependabot-core#2041]
1. I've committed a `package.json` with a library subdirectory included in my project (not using package manager for this project).
2. Dependabot reported [a security alert](https://github.com/cesky-svaz-orientacnich-sportu/vybriz/network/alert/www/ext/tinymce/package.json/jquery/closed).
3. I've deleted the `package.json` and thought that it would resolve it.

But I'm still getting the alert listed in my daily e-mail notification (and in the list of alerts on repository Security page). I've tried to dismiss the alert with "A fix has already been started", didn't change anything.

The alert page further shows a warning message "Dependabot cannot update this dependency" detailed as "Dependabot couldn't update this dependency to the required version as it doesn't support your dependency files.".

**Comment by lopopolo** [comment]
I converted some repos from `yarn.lock` to `package-lock.json` and I only get Github Security Advisories for the long-since deleted `yarn.lock` file. It is unclear if the existing `package-lock.json` file is monitored.

**Comment by levenleven** [comment]
I have monorepo and deleted one of the packages. But still getting alerts once a while (until dismissed) for no longer existing package-lock.json

**Comment by christopherblaser** [comment]
Getting this as well.

**Comment by WereDev** [comment]
I too am having this issue.  The files it's reporting have been deleted for months.  Even the folders that they used to be in are long gone.

**Comment by rlisowski** [comment]
The same for me. File and directory have been deleted a while ago but I still get new notifications about vulnerabilities.

**Comment by rande** [comment]
Did you have a branch with those deps still available ?

**Comment by J-Vin** [comment]
What would fix this?

**Comment by WereDev** [comment]
> Did you have a branch with those deps still available ?

In my case, no.  There are only two branches and the files were completely removed from both.  I haven't checked it in a while as all I was getting was false reports so I disabled the feature.

**Comment by liddellj** [comment]
I also recently experienced this - received an alert against a package.json file that had been deleted from the master branch weeks ago. Clicking the link to the package.json in the alert resulted in a 404. We _do_ have stale branches that will still include that package, but my understanding was that dependabot should only pay attention to the default branch.

**Comment by wigsofoz** [comment]
We had this issue today (GitHub Enterprise 2.22.4).

A workaround - 

1. Replace the deleted package.json file with one that has zero dependencies. Commit it. 
2. Delete the package.json file. Commit it.

The result of this is the zeroing out of the Dependency Graph for that file, but the file remains mentioned in the dependency graph view. You shouldn't get any more security warnings for those outdated dependencies.

**Comment by jurre** [comment]
I know the Dependency Graph team is aware of this, I'll link them to this thread

**Comment by nkn81** [comment]
+1 - Receiving the same issue with deleted directories reporting vulnerability alerts regarding `package-lock.json` files for numerous repos. The alert is dismissed and reappears a few weeks/months later.  Similar to @karlhorky with **new** alerts coming in.

**Comment by tomwillis608** [comment]
+1 
I have a project where a deleted Pipfile.lock keeps getting vulnerability findings, even though the file was deleted on all branches months ago.

**Comment by raniesantos** [comment]
I have a similar problem.

I stopped using Yarn, but my security alerts indicate that dependabot is still reading from `yarn.lock`.

At the moment running `npm audit` locally shows 0 vulnerabilities.

Please give us some way to manually force dependabot to recognize the new lock file.

**Comment by jurre** [comment]
The Dependency Graph fixed an issue with deleted manifests a while ago, these issues might pre-date the fix? If you let me know the repo this is happening on I can force a re-detect, or feel free to contact support and they should be able to do it as well.

Unfortunately there is currently no way to run the re-detect yourself, and (possibly confusingly) our team doesn't maintain this feature, but I'm happy to help and so are our wonderful support engineers.

**Comment by raniesantos** [comment]
@jurre 

https://github.com/raniesantos/artisan-static

**Comment by raniesantos** [comment]
@jurre is the link enough or should I also contact support like you said? Where can I do this?

**Comment by jurre** [comment]
Hi @raniesantos, I just kicked off the re-detection. I was out for a few days over Easter hence the slow response.

FWIW support can be contacted via https://support.github.com/

**Comment by ccrraaiigg** [comment]
I also need a re-detect, on repo https://github.com/ccrraaiigg/caffeine/. Thanks!

**Comment by raniesantos** [comment]
I'm still getting this, I just got it this week.

![Screenshot from 2021-05-08 21-32-26](https://user-images.githubusercontent.com/8528269/117541123-ffc07600-b044-11eb-9c2c-1045ca4bfacb.png)

**Comment by donatj** [comment]
We moved our `package.json` / `package-lock.json` up a level over a year ago, it was in `public/js/app` and is now in `public/js` but we still get warnings for the old `public/js/app`.

![image](https://user-images.githubusercontent.com/133747/117837283-f00c8180-b23e-11eb-8dab-9518094eb1ca.png)

When you click into one of these even Dependabot is like "something is wrong here"

![image](https://user-images.githubusercontent.com/133747/117837596-31049600-b23f-11eb-938c-12d945e9add3.png)

**Comment by raniesantos** [comment]
I got an email alert about my non-existent yarn.lock file again today.

**Comment by 2-REC** [comment]
> We had this issue today (GitHub Enterprise 2.22.4).
> 
> A workaround -
> 
> 1. Replace the deleted package.json file with one that has zero dependencies. Commit it.
> 2. Delete the package.json file. Commit it.
> 
> The result of this is the zeroing out of the Dependency Graph for that file, but the file remains mentioned in the dependency graph view. You shouldn't get any more security warnings for those outdated dependencies.

Just had the issue (on a previously existing 'package.json' deleted a while ago).
This workaround seems to have solved it.

**Comment by raniesantos** [comment]
Can you please seriously consider giving repo owners more direct control over this?

I thought my issue would have been solved already, but it just came back.

**Comment by grzesuav** [comment]
I got the same, I get alerts for `Gemfile.lock` which does not exist....

**Comment by BinBashBanana** [comment]
Happening to me too... super annoying

**Comment by raniesantos** [comment]
I'm back! I just got a report for an axios vulnerability for a repo that doesn't even use axios. Yaaaay!!!!

**Comment by tegner** [comment]
![image](https://user-images.githubusercontent.com/2571413/133095889-46964799-4ddc-4845-ad9f-8c2576cd4cd8.png)

It makes very little sense that the alert is sent week upon week, while the file is actually missing. And marked as inaccurate every week.

**Comment by jurre** [comment]
Hey, I know it's somewhat confusing but dependabot-core is not used for the alerts feature on GitHub. This issue is on that teams radar though, so I'm going to close this out from our issue tracker. When running into this the easiest way to reach that team is to go via [github support](https://support.github.com/), but we'll try to forward things as best as we can.

**Comment by chadlwilson** [comment]
Acknowledging that this might not be a dependabot issue - has anyone figured out how to address this when the Dependency Graph is showing previously deleted vendored dependencies, e.g historically source controlled Ruby gems and gemspecs?

According to https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/troubleshooting-the-dependency-graph it's not supposed to look at vendored deps anyway (for whatever reason).

e.g. it wasn't doing so until recently, but https://github.com/gocd/gocd/network/dependencies has started showing stuff long-since deleted e.g

![image](https://user-images.githubusercontent.com/29788154/229969545-176b11c1-3685-4b29-9fb2-bcf52a283128.png)

Deleted in https://github.com/gocd/gocd/commit/f8132a1e8f9e1ebf58c1f188f247fdfa6a032e40.

Since the source is not a single `Gemfile` or `GemFile.lock` I'm not sure what workaround might exist here. Tried adding an empty folder with `.gitkeep` but didn't seem to do the trick. Will try raising a ticket with Github Support, but thought someone might have noticed this and figured this one out.

**Comment by jeffwidman** [comment]
You could also try creating a [Code Security discussion](https://github.com/orgs/community/discussions/categories/code-security)... that's the officially recommended "public" place for raising issues about dependency graph or security alerts. But based on your description, this may be specific to your repo in which case a support ticket is probably your best bet.

**Comment by chadlwilson** [comment]
Thanks @jeffwidman - will see how I get on with support and try the community otherwise. Reason I asked is that this seems to have started in the last few days around the time of the launch of the new Dependency Graph view, and the behaviour contradicts documentation so is at least a documentation bug, if not a "real" bug - usually such things affect multiple folks.

No idea if the original bug discussed here on inexplicably stale dependency graph entries has been addressed - maybe it hasn't been and some recent changes to include `vendor`ed dependencies (which seems reasonable to me, personally) has just exposed some repos with similar issues.

**Comment by jorisroling** [comment]
Just had this issue with a old yan.lock file pointing to since than long remove package. (this commit is three year old). Since then I moved from yarn.lock to package-lock.json.

I fixed my issue by adding a new yarn.lock file (by running 'yarn'). commited this. Then deleted to yan.lock file again, and commit this again. Looking at the alert page, it immediately 'removed' the issue.

Hope this helps some of us. Cheers!

**Comment by jl2** [comment]
I'm still seeing this in some of my repos.  Very, very annoying to get these emails for fixed issues, so I'm disabling the dependabot scan.

**Comment by chadlwilson** [comment]
> I'm still seeing this in some of my repos. Very, very annoying to get these emails for fixed issues, so I'm disabling the dependabot scan.

You can use the virtual agent to ask GitHub to redetect dependencies for a repo. [Try this search](https://support.github.com/?q=redetect+dependencies)?

**Comment by domschl** [comment]
While that virtual agent is a nice high-tech work-around (can't say yet if it actually does something), but how about solving the underlying problem?

I am (so far) receiving Rust dependency [errors](https://github.com/domschl/indrajala/security/dependabot/18) for a Python project that doesn't contain a single line of Rust in any branch any more. That indicates that Dependabot uses some hallucinated project state as basis for it's reports which is a twofold security issue in itself:

- It might miss actual problems because reporting on some outdated state
- It will make users annoyed because of reporting hallucinated problems, making them switch off an otherwise very useful tool.

So, Github, please fix the underlying issue.

**Comment by chadlwilson** [comment]
@domschl   Based on  https://github.com/dependabot/dependabot-core/issues/2041#issuecomment-979953683  I think the issue here is that it relates to some problematic caching or something else outside dependabot itself so we'd need to find the right place to get this tracked on GitHub side of things if it's still happening, either via GH support or some other repo?

**Comment by domschl** [comment]
Some problematic caching? Shouldn't dependabot kind of know what data it is operating on?

No worries, I simply remove the bot on all of my projects.

**Comment by max-tarlov-infinitusai** [comment]
Ran into this issue today after consolidating several uv.lock files into a single uv workspace lock file. Here are the steps for the workaround I used (suggested by @yeikel in issue [#15010](https://github.com/dependabot/dependabot-core/issues/15010#issuecomment-4445683032))

1. Navigate to Settings > Advanced Security
2. Take a screenshot of your Dependabot settings (you'll need to restore them later)
3. Disable dependency graph. You'll see a warning like this: "Disabling the dependency graph will also disable Dependabot alerts." Confirm that you want to disable all this
4. The page will reload, and you can re-enable dependency graph and your Dependabot settings from your screenshot
5. Navigate to Insights > Dependency graph. The status of the dependency graph should either be in-progress or completed in the time between now and when you re-enabled dependency graph in step 4
6. Once the dependency graph has been generated, navigate to Security and quality > Dependabot > Vulnerabilities
7. Click on the gear icon/settings menu and click "Refresh Dependabot alerts." Dependabot will scan the new dependency graph and automatically close stale alerts as "Fixed" in about 10 minutes

<details>
<summary>Related issues</summary>
<ul>
<li>https://github.com/dependabot/dependabot-core/issues/4129</li>
<li>https://github.com/dependabot/dependabot-core/issues/1917</li>
<li>https://github.com/dependabot/dependabot-core/issues/15680</li>
</ul>
</details>
