### ISSUE TITLE
Version parsing for Maven `PRD` tag to treat as a pre-release tag may be incorrect

### ISSUE THREAD

**Issue by agustin-golmar** [dependabot/dependabot-core#2044]
Hi. My project uses Java 12 and Maven.

I received an automatic pull-request for **javax.measure:unit-api:2.0** to v2.0-PRD ([Vortex PR dependabot/feedback#5](https://github.com/agustin-golmar/Vortex/pull/5)), but you can clearly see that v2.0 was released on 7/Jul/2019 and v2.0-PRD on 12/May/2019 ([UoM API: Releases](https://github.com/unitsofmeasurement/unit-api/releases)), _i.e._, its an **older release**.

In fact, this break my current code, because the reference implementation of the API (**tech.units:indriya:2.0.2**), request a method that v2.0-PRD doesn't have.

Thanks in advance.

Similar issues in Dependabot:
- [PR dependabot/feedback#344](https://github.com/dependabot/feedback/issues/344)
- [PR dependabot/feedback#360](https://github.com/dependabot/feedback/issues/360)
- [PR dependabot/feedback#404](https://github.com/dependabot/feedback/issues/404)
- [PR dependabot/feedback#701](https://github.com/dependabot/feedback/issues/701)

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

We've shipped a number of fixups to Maven parsing lately, even a couple in the last week. 

Additionally, our underlying Maven parsing is all regex/ruby, and we want to long term move to using Maven itself as that's much less brittle. So while we're happy to fix bugs that are currently affecting folks, we're not adding new features and for bugs that aren't currently affecting folks we'd rather invest that energy into figuring out how to switch to Maven long term.

I'm going to close, as I assume this either isn't reproducible or isn't currently affecting you (since the upstream package had several releases since 2.0). But if I'm wrong please comment and we can re-open.

**Comment by deivid-rodriguez** [comment]
This could potentially be related to https://github.com/dependabot/dependabot-core/issues/6637 and the upstream issue linked from there.

**Comment by agustin-golmar** [comment]
Hi all; I'm still alive. Thanks to everyone. I believe an automatic version update system like Dependabot shouldn't rely on conventions or string matching, as it changes periodically and from project to project. This is fragile. It should be based on package release timestamps or another deterministic measure that is immutable and monotonic (I know time isn't deterministic, but a fixed, incremental measure of the timestamp is; it represents a total order in the repository, or at least, it should be). Cheers.
