### ISSUE TITLE
Flatten/de-dupe npm lockfile

### ISSUE THREAD

**Issue by XhmikosR** [dependabot/dependabot-core#2079]
So, this situation has bit me numerous times :)

Basically, after a while using dependabot, one ends up with many duplicate packages. A recent example is https://github.com/twbs/bootstrap/pull/29730

I'm not sure how dependabot could mitigate this issue. `npm dedupe` does not seem to solve the issue. On the other hand, regenerating the lock file shouldn't be done by default since it can break many things.

I know there is https://github.com/dependabot/feedback/issues/313, but it seems that was focused mostly on yarn.

**Comment by yudai-nkt** [comment]
Any updates on this?

I received a dependabot PR with a patch release update breaking the CI (yudai-nkt/jupyterlab_city-lights-theme#103), and it turned out to be caused by duplicated packages thanks to jupyterlab/jupyterlab#9699. `npm dedupe` didn't fix my problem neither, so I thought it's related to this issue rather than a new issue.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response, we're finally getting a chance to look at some of our backlog.

This is a really old issue... is it still happening or can this be closed?

Dependabot generally tries to shell out to `npm` / `yarn` native package managers, so it's unclear if the root problem here is in Dependabot or upstream in the package managers themselves... especially if `npm dedupe` isn't resolving it.

**Comment by XhmikosR** [comment]
Maybe this is now fixed assuming you are using newer npm, it's been some time since I last noticed it.
