### ISSUE TITLE
Use a single PR for updates with the same GroupId and Version

### ISSUE THREAD

**Issue by larsgrefer** [dependabot/dependabot-core#2121]
This is a special case of:
* https://github.com/dependabot/dependabot-core/issues/1190

I have multiple dependencies pointing to different submodules of the different overall project:

```gradle
dependencies {
    compile "org.springframework:spring-beans:4"
    compile "org.springframework:spring-context:4"
    compile "org.springframework:spring-web:4"
}
```

When Version 5 becomes available all of these dependencies should be updated in one atomic PR.

Some real world examples:

- Updating the group `com.squareup.retrofit2` from 2.5.0 to 2.6.1
  - freefair/gradle-plugins#58
  - freefair/gradle-plugins#54
- Updating the group `io.freefair.gradle` from `3.7.4` to `3.8.1`
  - freefair/okhttp-spring-boot#15
  - freefair/okhttp-spring-boot#16
  - freefair/okhttp-spring-boot#17
  - freefair/okhttp-spring-boot#18
  - freefair/okhttp-spring-boot#19
  - freefair/okhttp-spring-boot#20

**Comment by infin8x** [comment]
Similar to #1190

**Comment by missedone** [comment]
pls check this https://github.com/dependabot/dependabot-core/issues/1618#issuecomment-665863295 which works for me

**Comment by mwaddell** [comment]
Similar to #3856 also

**Comment by jeffwidman** [comment]
Solving this for all edge cases really requires leveraging a native helper:
* https://github.com/dependabot/dependabot-core/issues/1164

**Comment by jeffwidman** [comment]
I get that you _want_ them to all be bumped in a single PR, but which of the following is true:
1. They are force-linked together in some way such that  Gradle will realize they _always_ must be bumped in lockstep?
2. Or technically is it allowed by the Gradle tooling that only some of them bump and some others don't? 

1️⃣ is tracked in the generic sense in:
* https://github.com/dependabot/dependabot-core/issues/1296

2️⃣ is tracked in:
#1190

**Comment by mwaddell** [comment]
@jeffwidman There are a lot of different issues related to this, but they all basically come down to the same underlying frustration with dependabot - it creates a lot of "noise" because virtually every version of every dependency gets its own individual PR.  The value of dependabot is that it automates the process of checking for available updates and creating PRs when new updates are available.  However, those PRs are not grouped or managed the way a human would do it if given the same job, so dependabot ends up adding a lot of additional overhead in now managing all of those individual PRs.  This problem is much worse in ecosystems like javascript where even relatively small projects have a large number of dependencies which get updated very regularly and where many are logically grouped together.  In addition to being frurstrating to manage them all, it can quickly blow up your CI costs if you run CI on your dependabot PRs.

Currently, the only solutions to this problem are to (a) manage all of these various PRs manually, or (b) to set up custom scripts to manage all the dependabot PRs after-the-fact.  Managing them all manually gets frustrating pretty quickly.  Using custom scripts works okay, but adds another layer of code to maintain and demotes dependabot to an alerting system only (basically the approach is that you set up CI to ignore all dependabot PRs and instead have a github action which triggers every time a new dependabot PR is created.  That action uses fetch-metadata to grab the relevant information, looks up the group it should be in, and then creates/uses the branch with that name, merges the changes in and closes dependabot's PR - it's clunky and breaks often because of merge conflicts, but it's the only automated solution at this time).

In order to solve this more fundamental problem, dependabot requires 2 major changes.  The first is to allow multiple directories for the same ecosystem.  The second is to add a new `groups:` section of the config that would contain one or more group names which each follow the same format as the `allow:` section does now.  For example:

```yaml
version: 3
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/web"
      - "/api"
      - "/docs"
    schedule:
      interval: "weekly"
    groups:
      react:
        - dependency-name: "react*"
      eslint:
        - dependency-name: "eslint*"
        - dependency-name: "@typescript-eslint*"
      other-development:
        - dependency-type: "development"
```

The above would put any dependency (across all three directory) which starts with "react" in the same PR and reuse that PR as other dependencies/versions are added (as long as it is still open).  Matching can be done in order (so "other-development" only matches if the first 2 didn't match) and anything which doesn't match any of the defined groups would work the same way it does now.

I know that this would be significant change to some core dependabot functionality but it would singlehandedly address a large number of existing issues and make dependabot more flexible and configurable.

**Comment by 0xdevalias** [comment]
I really like how the suggestion above ([Ref](https://github.com/dependabot/dependabot-core/issues/2121#issuecomment-1426017138)) puts the 'control of grouping' back on us as individual developers, which IMO would remove a lot of the 'effort' of trying to figure out the correct groupings for everyone that uses dependabot.

And then later, any public repo's can be data-mined for their dependabot grouping configs to build up a 'database' of the most common groupings, that could then be used to improve the 'default smarts' of dependabot (or suggest groupings for users to include in their own config; which itself could potentially be implemented as a dependabot PR suggesting changes to it's own config, to still 'keep a human in the loop')

**Comment by larsgrefer** [comment]
> I get that you _want_ them to all be bumped in a single PR, but which of the following is true:
> 
>     1. They are force-linked together in some way such that  Gradle will realize they _always_ must be bumped in lockstep?
> 
>     2. Or technically is it allowed by the Gradle tooling that only some of them bump and some others don't?

I'ts mostly 2, but a bit of 1 could happen.

Technically, Gradle would be fine with them being declared with different versions. But dependencies which are essentially different modules published by the same project have a high chance of being interdependent.
So updating only one module could lead to compilation failures if there is a breaking API change between the modules.

There is no easy way to 100% correctly determine, which dependencies should be bumped together, but multiple dependencies having the same groupId, the same current (old) version and the same new target version should be a reasonably good heuristic.

I'm not sure if I like the idea of having to declare all dependency groups manually. First, because I'm lazy and don't want to spend my time configuring dependabot for all my repositories, and second because potentially thousands of repositories would need to declare the same groupings over and over.

If you don't like to use a heuristic here it might be the better option to have a static list of groups inside dependabot itself.
Having the ~100 most common groupings declared in some sort of semi-official list, should help to reduce the PR count for many projects.

**Comment by abdulapopoola** [comment]
**Update**: We've started doing some grouped updates work! This particular issue might not be part of the first ship but if you want to track our updates, do follow #1190.

**Comment by carogalvin** [comment]
Just wanted to pop in from the Dependabot team to mention that we have configurable grouping rules in public beta, which should solve this problem! You can see the docs on how to set these up here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

If you have any feedback, please feel free to email me at `carogalvin@github.com` or set up a meeting with me by [picking a convenient time in my calendar here](https://calendar.app.google/YdAa1FZ1GFL3mWUF8).

**Comment by mwaddell** [comment]
> Just wanted to pop in from the Dependabot team to mention that we have configurable grouping rules in public beta, which should solve this problem! You can see the docs on how to set these up here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> 
> If you have any feedback, please feel free to email me at `carogalvin@github.com` or set up a meeting with me by [picking a convenient time in my calendar here](https://calendar.app.google/YdAa1FZ1GFL3mWUF8).

@carogalvin It would be nice if dependabot closed the old individual PRs when it created the combined one.  It's a little confusing that when you close them manually you get the "I won't notify you" alert but it is still tracking them in the other PR...

**Comment by abdulapopoola** [comment]
Closing this out as we've officially[ released grouped version updates](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/); please feel free to reopen or reach out if there are more questions or feedback.

**Comment by deki** [comment]
Is there a way to group updates by Maven groupIds now? I reviewed multiple config samples but it seems I still have to manually specify all groupIds?!
