### ISSUE TITLE
Support "apply from:" in Gradle

### ISSUE THREAD

**Issue by wtanaka** [dependabot/dependabot-core#2138]
It's possible to use "apply from" in gradle to include other .gradle files:

https://github.com/wtanaka/ciconfiggen/blob/cc8bfc43f7e9e4109310c9fb48af6ad83cdacf13/build.gradle#L2-L4

Based on what's shown in the web dashboard, it looks like dependabot might not be scanning dependencies in these included files:

https://app.dependabot.com/accounts/wtanaka/repos/178891901

**Comment by tunderwood** [comment]
Following since I would also find this feature useful. I was actually just looking at the code and it appears that this is actually semi implemented for a very specific filename. 

It wouldn't solve this exact use case but it looks like they will scan dependencies in a file located at `<default dir>/gradle/dependencies.gradle` without any extra configuration

This seems to only work if you include the line:  `apply from: 'gradle/dependencies.gradle'` in your `build.gradle` file. Since the functionality is already there for this specific file, it might not be too hard to extend it to work with other custom file names.
