### ISSUE TITLE
Feature-request: PGP signed commits and verified merges from Dependabot

### ISSUE THREAD

**Issue by HendrikPetertje** [dependabot/dependabot-core#2145]
I work in a team using dependabot where all team members are advised to sign their commits with PGP keys. This is to make sure (to some degree) that everything done is signed and things altered by people or bots with bad intentions stick out. 

Dependabot however, doesn't sign its commits, nor are the squashed commits verified Github merges. Would it be possible to make this possible?

example commits log with Dependabot on a PGP enforced team:
![Screenshot 2019-06-03 at 10 01 39](https://user-images.githubusercontent.com/3583395/58786131-34209180-85e7-11e9-8d50-14f899cfa53d.png)

Thanks!

**Comment by simkimsia** [comment]
Same issue as @alexkuc 

On the PR, can see that it's verified
![image](https://user-images.githubusercontent.com/245021/140884814-39292e4a-3e2e-4646-91ae-42299138c9b2.png)

At the main branch after i rebased and merged

![image](https://user-images.githubusercontent.com/245021/140884941-c9dc8bcc-d5f9-46a4-9442-52e72bbc8c6a.png)

I see at rebase and merge authored and signed off by dependabot but the committer ends up being me

which is not an issue because i did a regular merge on github.com and the verified is just fine

![CleanShot 2021-11-09 at 16 01 28@2x](https://user-images.githubusercontent.com/245021/140885135-8881de1e-c4af-41db-af0c-51e8f341ad34.png)

help pls?

**Comment by jeffwidman** [comment]
The summary as best I can tell is the commits are now verified for fast-forward merges, but as explained in ☝️, they won't be for rebase-and-merge PR's. I do see squash-and-merge showing as verified in the commit history here in `dependabot-core` itself.

I'm going to close as there's nothing more we can do specifically here in Dependabot... if there's still an issue with the display of the PR's for rebase-and-merge it's a general GitHub PR's issue, not specific to Dependabot.
