### ISSUE TITLE
Limit concurrency of updates for Dependabot

### ISSUE THREAD

**Issue by StephanBijzitter** [dependabot/dependabot-core#2161]
Hello!

When merging a pull request from dependabot, it automatically rebases all other open pull requests (at least if pull requests must be up to date).

This is awesome! But... we use Codeship and we have a plan with limited concurrency where we can only have so many builds active at one time. When Dependabot updates it could very well rebase 20 to 30 pull requests, most of which end up in a queue.

Now, the queuing is also not really bad: they will eventually run. The problem is when we are also working on other things and need to deploy changes to our testing environments and our own changes are queued behind the builds triggered by Dependabot.

I'd like to propose an optional setting for Dependabot where the concurrency can be configured. For example, when set to 3, Dependabot should not rebase (or create new) branches until there's less than 3 existing Dependabot pull requests with pending status checks.

It's a minor inconvenience, but if it's a simple feature... who knows :-)

**Comment by casmith** [comment]
+1 would be great to throttle the number of concurrent PRs from dependabot as it creates a lot of pressure on our CI environments with all the redundant builds.

**Comment by atmcarmo** [comment]
+1 for this feature request. This would really be helpful for us as well as sometimes we have a burst of dependabot builds.

**Comment by asciimike** [comment]
Closing as I believe this has been solved via [`open-pull-requests-limit`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#open-pull-requests-limit), but feel free to re-open if it's not working for you!

**Comment by eps1lon** [comment]
> Closing as I believe this has been solved via [`open-pull-requests-limit`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#open-pull-requests-limit), but feel free to re-open if it's not working for you!

I don't believe this applies to the intended usage.

Say we want updates on a Monday. Right now dependabot might open 40+ PRs where most fail due to timeouts  because we don't have enough ressources. In this situation it would be ideal to tell dependabot to only "trickle in" these PRs over time (e.g. throttle dependabot).

What you're suggesting is to only get 5 updates on a Monday which certainly helps with ressource issues but will result in less overall updates received.

Though I do understand that this is a tricky problem for dependabot to solve. CI providers are probably in a better spot to implement custom scheduling of queued PRs.

**Comment by asciimike** [comment]
I agree that I don't think it's the exact feature requested, but I believe that the outcome is mostly the same. I think that something like `max-pull-requests-created-limit` is more of what's being requested (give me up to N PRs every update, regardless of how many are open).

That said, I think this behavior basically already happens with open PR limit, since a lot of times what will happen is that a PR is merged, which updates the manifest, which triggers a new update job, and gives you new PRs up to that limit, so the trickle in behavior occurs (one at a time for every PR merged), and should keep you under the resource limits.

Obviously if a PR is closed, that doesn't touch the manifest therefore we'll wait until the next time the updater runs, so it's not a perfect system.

**Comment by eps1lon** [comment]
> which updates the manifest, which triggers a new update job,

Only if you constantly accept updates, no? For scheduled updates for a specific date I've never seen this kind of behavior.

**Comment by patkujawa-wf** [comment]
Another option would be to add a schedule.interval of `hourly` https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

**Comment by ffMathy** [comment]
@asciimike this is not solved, for the reasons given in the issue. Can we re-open this?
