### ISSUE TITLE
Support for CircleCI Orbs

### ISSUE THREAD

**Issue by aaronjensen** [dependabot/dependabot-core#2191]
CircleCI orbs are versioned and published to a public repository. It'd be great if dependabot could offer automatic upgrades for them as well.

**Comment by infin8x** [comment]
Closing this as we don't expect to get to it in the foreseeable future. We're not accepting PRs at the moment due to capacity limitations, but in the future we expect to accept contributions, including those adding CircleCI support in Dependabot Core, as long as they don't damage the maintainability of Dependabot Core.

**Comment by schneems** [comment]
> in the future we expect to accept contributions, including those adding CircleCI support

That makes sense to me. What kind of timeline (if any) could you project for opening the core up to external contributions?
