### ISSUE TITLE
Dependabot cannot be told to use a certain project for issues and pull requests it opens.

### ISSUE THREAD

**Issue by AraHaan** [dependabot/dependabot-core#2212]
A ``@dependabot use this project`` would be perfect to have.

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.

**Comment by AraHaan** [comment]
Sorry about that was busy trying to fix some breakage on some code of mine that I forgot to reply to keep it active.

**Comment by jeffwidman** [comment]
This was created for the old Dependabot preview.

The current Dependabot iteration no longer creates issues when it hits problems... https://github.com/dependabot/dependabot-core/issues/3509 tracks notifying upon error in some fashion.

As for the PR's, I haven't seen any other requests for PR's to be assigned to particular projects... we do support labels, I suspect you can use a GitHub action to assign PR's with a particular label to a particular project? I've never tried to wire it up though.

I don't see us implementing this anytime soon due to lack of user interest plus a GitHub actions-based workaround probably exists for the folks who need it. But if not please comment and we can re-open.
