### ISSUE TITLE
Update Docker image on kubernetes deployment files

### ISSUE THREAD

**Issue by AndreaGiardini** [dependabot/dependabot-core#2217]
It would be nice to have the possibility to have the docker image update logic also for Kubernetes deployment files.

Dependabot will have to scan all yml/yaml files, get the `image` field and check for updates of the docker image.

**Comment by jglick** [comment]
See also #2237.

**Comment by JesperTerkelsen** [comment]
+1

**Comment by jeffwidman** [comment]
Support for this was merged in https://github.com/dependabot/dependabot-core/pull/5348 🎉

**Comment by Raboo** [comment]
@jeffwidman is it the `package-ecosystem: "docker"` that is used for Kubernetes YAML files?

**Comment by dimisjim** [comment]
@Raboo seems to be so yeah, based on: https://github.com/dependabot/dependabot-core/pull/5348#issue-1296588620 

> It is added onto the Docker package.

as it's also the only one in the doc right now: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

**Comment by jeffwidman** [comment]
Currently this is buried behind a feature flag for folks on GitHub.com...

We'd like to start slowly rolling it out for everyone, but before I do that, I'd like to test on a few repos to ensure no unexpected issues. I can / will setup a fake test repo, but there's nothing like live data to confirm things.

Anyone watching this issue care to volunteer to have their repo(s) be part of the beta test?

Repos must match the following criteria:

* on GitHub.com
* public, because for security reasons we can't access private repos w/o jumping through some hoops
* have k8s deployment yaml files... ideally with a combination of up-to-date and outdated docker image tags

If interested, please comment on this thread with the URLs of any repos you own/maintain. Once I get a couple of volunteers, no need to keep volunteering... I expect/hope the rollout should be pretty quick, so you won't be waiting too long.

**Comment by chadlwilson** [comment]
Hi @jeffwidman Is this intended to support Helm templates? Or only raw K8s YAML?

https://github.com/gocd/helm-chart/tree/master/gocd is a Helm chart, so the deployment YAMLs are templates ([first](https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-agent-deployment.yaml), [second](https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-server-deployment.yaml), [third but is a Job](https://github.com/gocd/helm-chart/blob/master/gocd/templates/tests/gocd-test.yaml)). They are reading values from values file defaults, so are non-trivial unless the implementation renders a template somehow or "understands" Helm norms.

Please ignore if only intended to support raw YAML. 🙏

**Comment by jeffwidman** [comment]
@chadlwilson this change will support both raw K8s YAML and Helm files, _but only docker image tags_ within those files. As you noted, we'd need a bunch of additional tooling to support actual Helm template inheritance beyond just regex'ing out the docker image tags.

**Comment by jeffwidman** [comment]
I've enabled the feature flag on 100% of GitHub.com cloud repos, so anyone is now welcome to try this on their repos. If you run into any bugs, please file an issue.

**Comment by kpocius** [comment]
> public, because for security reasons we can't access private repos w/o jumping through some hoops

Is this requirement still true even after full rollout?

We've added the following:
```
- package-ecosystem: docker
  directory: namespace/traefik/install
  schedule:
    interval: weekly
  rebase-strategy: disabled
```
But end up with an error:
![image](https://user-images.githubusercontent.com/10368398/203309744-5af9d9e4-6eee-489c-9dcb-764a80790eed.png)

**Comment by kpocius** [comment]
Pardon the spam. Turns out there was a typo in the config.
