### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by douglasrlee** [dependabot/dependabot-core#2245]
I might have missed this somewhere but it would be awesome if you could get dependabot to notify you of PRs created via slack.

**Comment by infin8x** [comment]
Closing this as the GitHub Slack integration is the way to go.

**Comment by richardsimko** [comment]
@infin8x There seems to be very little activity in that repo (40+ PRs not merged, ~200 open issues, no commits for the last 6 months). Also that integration doesn't work if you *only* want dependabot alerts in Slack, as the label filter doesn't work for dependabot PRs for whatever reason. I read in one of the issues that the label filter doesn't work if the PR is opened without labels and the label is added later, so that could be the reason.

Anyway, any chance you might revisit this in light of these issues?

**Comment by jeffwidman** [comment]
If you were following this, it got re-opened at #4642. So follow that for updates if/when we get to it.
