### ISSUE TITLE
Use a "status" on PRs to block merging when rebasing

### ISSUE THREAD

**Issue by nesl247** [dependabot/dependabot-core#2249]
When dependabot detects a rebase is needed, it only updates the PR description with the message. Unfortunately, this can mean that `composer.lock` for example is outdated when doing multiple merges, as the `content-hash` is different. Dependabot doesn't detect the PRs need a rebase quick enough, so a status update while it is being determined and or rebased would be great.

**Comment by deivid-rodriguez** [comment]
I _think_ this is essentially a duplicate of https://github.com/dependabot/dependabot-core/issues/2379? Please reopen if not!

**Comment by nesl247** [comment]
It's not a duplicate. That suggests moving it to a draft, this is about using the checks API to add a new status.

**Comment by deivid-rodriguez** [comment]
@nesl247 Yeah, I noticed that, my point was that both issues request a fix to the same end user problem: "Avoid accidental merge of Dependabot PRs", regardless of how that is implemented. Is this correct? Would you need a status check for anything else?

I'm actually wondering now whether #2379 should be closed too, because we closed #4570 (which is the newest between the 3 issues), because current branch protections seem to work just fine to prevent this?

**Comment by nesl247** [comment]
They do work to solve the same problem, and I don't think I need this anymore myself with our current settings. I'm not sure if those settings were to change that maybe we would need it again, but for now I'm good.
