### ISSUE TITLE
Support grouping of pull requests

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#2265]
See https://github.com/dependabot/dependabot-core/issues/376 for more detail.

**Comment by infin8x** [comment]
Duplicate of #1190

**Comment by wangyun1517** [comment]
> We're planning on implementing this (it's our most requested feature) but this will come after we've launched the new integration of Dependabot native within GitHub (beta coming soon).
> 
> I'm locking this issue to prevent spamming existing subscribers.

@feelepxyz Any update on this?

**Comment by infin8x** [comment]
@wangyun1517 hoping to dig into this between now and the end of the year. If you'd like, head on over to #1190 to follow along.

**Comment by fkirc** [comment]
I would prefer if grouping could be configured on a per-organization basis:

For example, I get a lot of PRs for `@types`-dependencies, e.g. `@types/node`, `@types/lodash` and so on.
Even in small projects like `attranslate`, I get quite a lot of `@types`-PRs: https://github.com/fkirc/attranslate/pulls?q=%40types+

Those `@types`-dependencies are not super-critical because they do not change any runtime-behavior, therefore it would be easy to merge multiple `@types`-dependencies in a single PR.
If I could configure a grouping for the `@types`-organization, then this would be already a huge help to reduce noise and overheads.


Of course, `@types` is not the only organization that is good for grouping.
For example, @stephanvierkant pointed out that `@symfony` could be a good grouping-candidate as well:
https://github.com/dependabot/dependabot-core/issues/2265#issuecomment-626533927

Therefore, it seems natural to make organization-grouping configurable instead of hardcoding a specific behavior.

**Comment by asbjornu** [comment]
Now that _Dependabot_ is GitHub-native and _Dependabot Preview_ is phased out, I would love to have this feature. Just an example of why:

<img width="818" alt="Heaps of Dependabot pull requests" src="https://user-images.githubusercontent.com/12283/134636559-17df4132-b737-441a-925f-e3e64d1fe1d6.png">

😅

**Comment by ldemailly** [comment]
the other issue is locked but would a work around be to split the target branch into a source branch which would still be the default branch by default and a destination integration branch so I can merge than one in batch

I could deal with many individual PRs but having my main branch commit full of depandabot is really not great. This being said having the option to collapse into fewer PRs would probably be even better, with some command to reject some of the updates/split them away

**Comment by andy840119** [comment]
dependabot support grouping of pull requests now 🎉 

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
Here’s the documetation.

https://github.com/eve-val/eve-roster/pull/1815/files
Here’s the sample
