### ISSUE TITLE
yarn.lock actual resolved version seems to be ignored by dependabot version range alert 

### ISSUE THREAD

**Issue by mdgbayly** [dependabot/dependabot-core#2279]
Our yarn.lock file contains a number of references to the `kind-of` package including ^3.xx, ^4.x.x, ^5.x. and ^6.x.x versions.

There is a dependabot alert for versions >= 6.0.0, < 6.0.3

CVE-2019-20149
moderate severity
Vulnerable versions: >= 6.0.0, < 6.0.3
Patched version: 6.0.3

Our yarn.lock references to ^6.x.x look like this:
```
kind-of@^6.0.0, kind-of@^6.0.2:
  version "6.0.3"
  resolved "https://registry.yarnpkg.com/kind-of/-/kind-of-6.0.3.tgz#07c05034a6c349fa06e24fa35aa76db4580ce4dd"
  integrity sha512-dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==
```
i.e. it has resolved to version "6.0.3" already but we are still getting the alert

**Comment by jeffwidman** [comment]
We shipped a lot of improvements to yarn over the past year. Is this still reproducible?

**Comment by jeffwidman** [comment]
Closing due to lack of user response.

Also, this repo / issue tracker is about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves. Versus this issue is about the alerts themselves, not the resulting PRs.

So if you're still seeing issues, I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles alerts. Feel free to drop a breadcrumb link on this issue to the discussion.
