### ISSUE TITLE
Non-GitHub-native Dependabot not respecting weekly schedule

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/dependabot-core#2284]
We have this in our Dependabot settings:

<img width="492" alt="Screen Shot 2020-07-06 at 10 40 57 AM" src="https://user-images.githubusercontent.com/1114569/86606114-9760be00-bf75-11ea-82b9-5735f6513f9e.png">

And yet I'm seeing non-security Dependabots getting created much later on Monday, e.g. https://github.com/panorama-ed/rainbow-backend/pull/1875

Have we misconfigured something?

**Comment by jbranchaud** [comment]
Similar to @JacobEvelyn, we've seen non-security Dependabot PRs come through later in the day a few times.

Currently, we are two Mondays in a row of **no** dependabot PRs coming through. We haven't touched our configuration in a while, so I'm not sure what could have changed. Anyone else experiencing this?

**Comment by lseppala** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to scheduling in both Dependabot and the Dependabot service. Is this still something you are still  experiencing? PRs from scheduled updates may be delayed when there are many repositories trying to update at the same time. Since Mondays are a particularly popular choice for updating, there have been delays in the past. We're constantly working to make the service more reliable, and hopefully the incidence of this has gone down since this issue.

**Comment by jurre** [comment]
Few thoughts on PRs being opened outside the schedule.

Given that this happened in dependabot-preview, which is no more, I'm not sure it still applies?

That said, there are a number of reasons why PRs can be issued outside of the schedule, security updates you already mentioned which are apparently not the case here, but Dependabot also runs whenever the manifest file or lockfile is changed (it will rebase any existing PRs, but new PRs can also be opened) or when the dependabot.yml config is changed.

Some of this churn can be avoided by configuring dependabot not to rebase open PRs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#rebase-strategy

No PRs being opened seems like an unrelated issue, if that is still happening please open a new issue for this using the [bug report template](https://github.com/dependabot/dependabot-core/issues/new?assignees=&labels=T%3A+bug+%F0%9F%90%9E&template=bug-report.md&title=) that we have, so we'll have all the relevant data.
