### ISSUE TITLE
Is the directory config value recursive or does it support glob?

### ISSUE THREAD

**Issue by IEvangelist** [dependabot/dependabot-core#2302]
This is a simple question, as I was unable to find the answer in the docs.

Is the [`directory`](https://dependabot.com/docs/config-file/#directory-required) recursive, or does it support glob patterns? I'm curious as I have a config that could be dramatically simplified. Our existing config file is growing, and it seems very redundant to have so many entries: https://github.com/dotnet/docs/blob/master/.github/dependabot.yml

**Comment by feelepxyz** [comment]
@IEvangelist 👋  not currently recursive but we have some ideas to improve this longer term. Dependabot currently only fetches individual files using the GitHub API which is why we haven't added support for deeper globs as this would get real slow using the API. We're planning to support vendoring and go major version updates which require a full repo checkout, which would enable us to glob for manifest files, but this is a while out as we're busy integrating Dependabot natively in GitHub for the next few months.

**Comment by IEvangelist** [comment]
Hi @feelepxyz 👋 

Thank you for your reply. I'll close this issue now, but I'm hopeful that this will eventually make its way into the bot.
