### ISSUE TITLE
Dependabot stuck trying to create automated security fix

### ISSUE THREAD

**Issue by kirtangajjar** [dependabot/dependabot-core#2327]
I'm having the same issue as described in https://github.com/dependabot/feedback/issues/578.

![Screenshot from 2020-07-17 13-04-13](https://user-images.githubusercontent.com/8456197/87762388-af1b2a80-c830-11ea-9b1d-d2ff0320e449.png)

**Comment by bootsie123** [comment]
Same here with lodash

**Comment by ehymowitz** [comment]
Same here, also with lodash

**Comment by bootsie123** [comment]
Since yesterday it seems to have timed out and I was able to have it recreate the security update successfully

**Comment by GaganBhat** [comment]
![image](https://user-images.githubusercontent.com/25236969/88080298-7e930380-cb44-11ea-8b10-858f892236b9.png)
Same issue here. I've tried to give it some time over the span of a couple of days, even kept the tab open, but it appears it's just stuck trying to generate the automated security update.

**Comment by ylemkimon** [comment]
The non-security Dependabot at Dependency graph also seems to be stuck:

![2020-07-27 15-16-25](https://user-images.githubusercontent.com/888148/88509554-498f2100-d01c-11ea-8f08-461de3b6964d.png)

**Comment by duythanhvn** [comment]
Same here... 😞

**Comment by priyomukul** [comment]
Same here, 

[screenshot](https://d.pr/i/e5K6UM)

not sure what, we don't have any package-lock in git, maybe it was in the past. 

but still, it's reading the file or else not sure what's going on.

**Comment by grische** [comment]
We are experiencing the same issue, dependabot being stuck for 5+ hours:
![image](https://user-images.githubusercontent.com/2787581/92100525-32421100-eddc-11ea-88d8-99534fe763b6.png)

@priyomukul your error message is different, it says "cannot update to the required version". That means you need to manually fix this.

**Comment by priyomukul** [comment]
@grische 

Funny thing is, I don't have that dependency in my codebase.

**Comment by markcmiller86** [comment]
I think I am having same issue. So far, *every* dependabot alert I've encountered in repos that I am an owner on, I have not been able to successful create an associated PR using the automated buttons on GitHub. Every repo this is occuring with is a gh-pages repo....some of which are 2-3 years old now. I believe I have seen it both in repos using *builtin* gh-pages themes and in repos using custom themes though all those below are using custom themes

* https://github.com/markcmiller86/atpesc2018/
* https://github.com/xsdk-project/MathPackagesTraining
* https://github.com/xsdk-project/ATPESC2018HandsOnLessons
* https://github.com/xsdk-project/MathPackagesTraining2020
* https://github.com/visit-dav/dashboard

I think it has something to do with `Gemfile` or `Gemfile.lock` contents though

**Comment by jurre** [comment]
> We are experiencing the same issue, dependabot being stuck for 5+ hours:

@grische it can sometimes take a while to generate these pull requests when we have a large backlog of alerts to process. 5 hours is not unreasonable, but is should never be stuck for more than 24 hours. Have you seen this recently?

> So far, every dependabot alert I've encountered in repos that I am an owner on, I have not been able to successful create an associated PR using the automated buttons on GitHub.

@markcmiller86 are you getting a "cannot update to the required version" message, or is the job indefinitely stuck in "Generating an automated security update" for a long time?

**Comment by markcmiller86** [comment]
> @markcmiller86 are you getting a "cannot update to the required version" message, or is the job indefinitely stuck in "Generating an automated security update" for a long time?

Yes, I've seen that message. Can't say for sure if in all cases but for sure I recall seeing it in some cases.

**Comment by grische** [comment]
@jurre We are usually fixing those security issues in less than 24 hours manually. I can see if we can wait, the next time a security fix is proposed.

**Comment by sgkiokas** [comment]
Hi guys. We have the same issue as well and I was wondering if you have an estimation of a fix or if this is in your Backlog in general. Thanks!

**Comment by jurre** [comment]
> Hi guys. We have the same issue as well and I was wondering if you have an estimation of a fix or if this is in your Backlog in general. Thanks!

Could you clarify what exactly you're experiencing including timelines? That'll help me diagnose what may be happening

**Comment by sgkiokas** [comment]
@jurre thanks for the prompt reply. We merged the dependabot config file to `master` yesterday. The file looks like this:

```
# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
      allow:
          - dependency-type: production
      open-pull-requests-limit: 5
      labels:
          - 'dependencies'
```

I can see all the dependabot alerts have been created properly, however, no PR has been created (not sure if this is related to the schedule interval).

If I manually try to update the dependency, I get:

![image](https://user-images.githubusercontent.com/22507185/96717210-c7aa5c00-13ae-11eb-956c-8bc3404c12b9.png)

This is the case for the rest of the dependencies flagged as vulnerable as well.

**Comment by jurre** [comment]
I think what happened here is that a PR could not be created because `http-proxy` is locked to a vulnerable version by another dependency (perhaps a parent dependency).

We're currently working on explaining why an update was not possible in this UI, but I'd need to have a look at the manifest files to determine what happened here currently.

In any case it can take a while between clicking "Generate PR" and the PR appearing, as we kick off a job to download the manifest files, analyze them, attempt an update etc, and at times there's a backlog of these jobs before they're processed. From you screenshot it seems like it was started very recently ("started now"), once the job finishes you should either see an error saying the update is not possible, or a PR.

**Comment by sgkiokas** [comment]
Thanks @jurre. Yes, a better error/warning message it'd indeed be better :)

**Comment by rzfzr** [comment]
I'm still having this same issue, on all my repos which dependabot appears, public or private, last one was on [this](https://github.com/rzfzr/toboard)

**Comment by alexrecuenco** [comment]
I am having the same issue [here](https://github.com/alexrecuenco/typescript-eslint-prettier-jest-example/security/dependabot/package-lock.json/ws/open)

**Comment by landsman** [comment]
Hi guys, I have probably the same issue as you have. Private repos.

<img width="994" alt="Screenshot 2021-06-14 at 21 54 12" src="https://user-images.githubusercontent.com/3184228/121951356-1e5c1000-cd5b-11eb-9101-256a2b6898c8.png">


<img width="988" alt="Screenshot 2021-06-14 at 21 54 03" src="https://user-images.githubusercontent.com/3184228/121951350-1c924c80-cd5b-11eb-8077-e206f56abb12.png">

**Comment by Warkanlock** [comment]
Same here with ``glob-parent`` and ``normalize-url``

**Comment by xrdavies** [comment]
The same....
![image](https://user-images.githubusercontent.com/1884084/124459898-43272e80-ddc1-11eb-8adf-4a51ac361762.png)

**Comment by landsman** [comment]
Same here with `glob-parent` as @xrdavies mentioned 😢

**Comment by landsman** [comment]
Is there some way how can we please help with this? @greysteil, @feelepxyz, @hmarr? 🙏 
Provide some logs? Access?

**Comment by feelepxyz** [comment]
@landsman could you ping over the repo name if public, or if its private contact us through github support and reference this issue: https://support.github.com/contact

Jobs can sometimes take a long time to start if we have a big backlog of jobs but we have different queues for manually triggered jobs so generally they start quickly.

**Comment by bbeckford** [comment]
Same issue here on 4 private repos:
 
![image](https://user-images.githubusercontent.com/2021072/134021113-edacb360-1ba4-45a5-ab55-2e967680f864.png)

**Comment by mcpierce** [comment]
Same here, multiple updates on a public repo.

**Comment by anthonyjdella** [comment]
Same. Happening to all of my public repos.

**Comment by kausrga** [comment]
Any update on this? I just configured dependabot on 2 different repos. Not one PR has created in the last 3 hours or so. I do see 15+ alerts fired.

**Comment by jaybuidl** [comment]
+1

**Comment by mcpierce** [comment]
Stuck for a year and a half and not even an acknowledgement of the problem from Github? That's sad.

**Comment by rzfzr** [comment]
From the lack of response the project looks dead....

**Comment by deivid-rodriguez** [comment]
Not dead at all @rzfzr :), we just struggled with giving more timely response in the past, but we're working in improving this.

I have seen this issue myself too, I will discuss with the team what we can do to improve this experience in general, through better UI feedback for example about what's going on, although I suspect the root cause needs to be figured out for each problematic case independently.

**Comment by jeffwidman** [comment]
👋 I'm going to close this because it's become a "catch-all" ticket... Unfortunately catch-call issues aren't really helpful because while the symptoms may be similar, the root cause may be entirely different.

Feel free to open new issues when you encounter this behavior, but please include more details than just "stuck". The more you help us, the better the odds that we'll be able to track down what's actually happening:
* Be sure to include a link to your repo. If it's a private repo, then open a support ticket. For extra credit, remove the sensitive code from the repo so it's a minimally reproducible example that you can use to make a new public repo. This makes it _much_ faster for us to verify that a potential code fix actually resolved the issue.
* Try running the native package manager locally to see if it can succeed with the upgrade. Sometimes it's a problem in your manifest file, and Dependabot doesn't surface the error properly... oftentimes the native package manager will give a more descriptive error. Exposing that error better is something we should improve, so please still file an issue, but knowing that it's a messaging bug not a logic bug saves a lot of debugging time.
* Try running dependabot's [`dry-run` script](https://github.com/dependabot/dependabot-core#dry-run-script). I _highly_ recommend doing that from within [the Dependabot Docker image](https://github.com/dependabot/dependabot-core#running-with-docker). If the error is in the Dependabot logic, this will often provide a more helpful traceback of the underlying Dependabot error than we surface in the UI.

Thanks!
