### ISSUE TITLE
Dependabot doesn't observe config in dependabot.yml 

### ISSUE THREAD

**Issue by echarrod** [dependabot/dependabot-core#2328]
Our repo is using the new [dependabot config file](https://github.com/getyoti/yoti-node-sdk/blob/master/.github/dependabot.yml)

But when PRs are created, they are not using the rules defined there.
We would expect them to have the base branch to be `development`, and add the reviewers and assignees. 
Examples:
- https://github.com/getyoti/yoti-node-sdk/pull/216
- https://github.com/getyoti/yoti-node-sdk/pull/214
- https://github.com/getyoti/yoti-node-sdk/pull/213

Before 3 days ago it seemed like it worked fine, with the most recent example being - https://github.com/getyoti/yoti-node-sdk/pull/212

On the dependabot dashboard it all looks fine:
![image](https://user-images.githubusercontent.com/1381991/87765335-93535c80-c80f-11ea-900c-7646274fb085.png)

And the insights look OK too:
![image](https://user-images.githubusercontent.com/1381991/87765421-b251ee80-c80f-11ea-953f-f0447e7a2da1.png)

**Comment by echarrod** [comment]
Another example - https://github.com/getyoti/yoti-node-sdk-sandbox/pull/44

**Comment by jurre** [comment]
These two screenshots are from different versions of Dependabot, the first screenshot is from the [now shutdown](https://github.blog/2021-04-29-goodbye-dependabot-preview-hello-dependabot/) dependabot-preview, and the second screenshot is from the GitHub-native version of Dependabot.

I realize this has been confusing, but since the former is now shut down, I'm going to assume this has been resolved, so I'm going to close out the issue.
