### ISSUE TITLE
Allow filtering on lockfiles and severity.

### ISSUE THREAD

**Issue by remcohaszing** [dependabot/dependabot-core#2374]
So far, most dependabot alerts I have received have been about low severity vulnerabilities of indirect dependencies. I am not interested in these, as they don’t affect any of my packages. A great example is [lodash](https://www.npmjs.com/package/lodash). Basically every JavaScript package depends on lodash indirectly, but barely any of them are affected by [CVE-2020-8203](https://github.com/advisories/GHSA-p6mc-m468-83gw) which was found about 2 weeks ago. This means thousands of users have to act on this notification for multiple repositories, even though they are probably not affected.

I would like more fine grained control over dependabot notifications. I.e. I would like to get notifications about all vulnerabilities of dependencies directly defined in `package.json`, but only for moderate or higher severity notifications for dependencies defined in my lock files.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

This repo is about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves. Versus this issue is about the alerts themselves, not the resulting PRs.

So I'm afraid I'll have to close this.

I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles alerts. Feel free to drop a breadcrumb link on this issue to the discussion.
