### ISSUE TITLE
running for requirements.txt but not setup.py

### ISSUE THREAD

**Issue by Mearman** [dependabot/dependabot-core#2384]
I'm not sure if this is a bug or that I haven't got the github action set up properly.
I have both a `requirements.txt` and `setup.py`
Dependabot is running fine for the `requirements.txt` but not for the `setup.py`.
https://github.com/Mearman/ML-Frabeller/blob/master/setup.py

**Comment by lseppala** [comment]
Hi @Mearman.

It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this issue still happening? If so, would you mind providing a bit more detail about what you expect to happen and what is actually happening? Thanks!

**Comment by ShadowJonathan** [comment]
@jeffwidman why was this closed unceremoniously?

**Comment by deivid-rodriguez** [comment]
Hei @ShadowJonathan!

Many months ago, more information was requested from the OP, since it was suspected that the issue would be no longer happening due to recent fixes/changes in dependabot-core. We never got further feedback about it so we assumed it was no longer an issue.

If you are running into this yourself, would you mind opening a separate ticket making sure to fill out the issue template we have these days? Thanks!
