### ISSUE TITLE
Timeout on private registry

### ISSUE THREAD

**Issue by tgomesfork** [dependabot/dependabot-core#2477]
We are getting timeouts for packages in our private registry, and we would like to know which IPs we have to whitelist from [this list](https://api.github.com/meta) to make it work. Right now we have whitelisted the addresses inside `hooks`. This used to work before, not sure what changed and we still have PRs open from 2 days ago.

**Package manager/ecosystem**

Javascript

**Manifest contents prior to update**

**Updated dependency**

Private dependencies inside our private registry.

**What you expected to see, versus what you actually saw**

We used to get PRs for private dependencies too, but now connections are timing out with 
`  proxy | 2020/08/25 09:34:20 [120] WARN: Cannot read TLS response from mitm'd server dial tcp 15.236.17.22:443: connect: connection timed out`

**Images of the diff or a link to the PR, issue or logs**

Log here:
https://app.dependabot.com/accounts/lafourchette/update-logs/44912244

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

I appreciate you whitelisting those IP's, but we're actually running on some different infrastructure right now that doesn't use those IPs. We have plans to change that, but that migration is a large project with no definite timeline so could be a while. Until then unfortunately we don't have a reliable list of IPs to whitelist.

However, it's been 2 years (as of tomorrow!) since this was filed... are you still seeing timeouts? We've done a lot of infra speedups since then, so hopefully this is resolved and we can close this.
