### ISSUE TITLE
Can dependabot be used with private pypi repos? 

### ISSUE THREAD

**Issue by zzztimbo** [dependabot/dependabot-core#2488]
This may be related to: https://github.com/dependabot/dependabot-core/issues/2477

We have a private Python repo. How do we use dependabot to manage updates in our company's Python artifacts?

**Comment by mahmoud-alfadel** [comment]
> This may be related to: #2477
> 
> We have a private Python repo. How do we use dependabot to manage updates in our company's Python artifacts?

Check this link [here](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates#supported-repositories). It seems private repos are not supported for updates. This is for security updates though.

**Comment by ulgens** [comment]
I answered very similar issue here: https://github.com/dependabot/dependabot-core/issues/2855#issuecomment-748857333

I'm not sure if things are different with dependabot.yaml config but it solved our issue with old-style/UI based config.

**Comment by Gidgidonihah** [comment]
It seems that indeed private repos are not supported with python package managers in Dependabot (dependabot.yaml config) but *are* supported with Dependabot-Preview (old-style/UI based config).
The UI for adding Dependabot access for private repos was recently added, and I hope to see support for python soon.

In the meantime, I'll be migrating all of our repos to the Dependabot-Preview.

**Comment by jurre** [comment]
It's supported! https://github.blog/2021-03-15-dependabot-private-dependencies/

**Comment by Gidgidonihah** [comment]
> It's supported! https://github.blog/2021-03-15-dependabot-private-dependencies/

Both [the documentation](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#package-ecosystem), and my own experimentation seem to indicate otherwise.

Note that in the linked documentation, the private repositories for python package managers are not checked, and the linked blog post mentions npm and go (but not python), both of which are checked in the private documentation.

As for my experimentation, I've given Dependabot access to our private repo:
<img width="945" alt="Screen Shot 2021-04-14 at 1 37 14 PM" src="https://user-images.githubusercontent.com/91488/114768841-9fc8ff00-9d26-11eb-8716-655c4a7512c0.png">

And it still fails on access to that repo:
<img width="1147" alt="Screen Shot 2021-04-14 at 1 36 47 PM" src="https://user-images.githubusercontent.com/91488/114768876-ac4d5780-9d26-11eb-8540-96ffea7a50df.png">

**Comment by jurre** [comment]
Ah, it seems like you're talking about private _git_ repo's whereas the issue title is talking about private `pypi` repo's. The latter is supported, the former is not.

**Comment by Gidgidonihah** [comment]
Ah indeed. I had missed the pypi in the issue title. I'll open a new issue (or find an actually matching issue) for private git repos.

**Comment by jurre** [comment]
> Ah indeed. I had missed the pypi in the issue title. I'll open a new issue (or find an actually matching issue) for private git repos.

I'm not sure if there's a public issue, but it's definitely on our radar 👍

**Comment by Gidgidonihah** [comment]
Given the support is there for private pypi repos, can we close this issue?
