### ISSUE TITLE
Link to project repo broken

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/dependabot-core#2494]
**Package manager/ecosystem**
Python: Pipfile
**Manifest contents prior to update**
Not important to the issue
**Updated dependency**
sphinx-autobuild from `0.7.1` to `2020.9.1`
**What you expected to see, versus what you actually saw**
The link in the PR body is broken. It should link to here: https://github.com/executablebooks/sphinx-autobuild
**Images of the diff or a link to the PR, issue or logs**
https://github.com/RohanNagar/thunder/pull/850

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

Also, this is a package metadata issue... we fetch what the maintainers provide for the package, so while I haven't looked at the code there's a 50/50 chance that the actual problem is with the metadata provided by the upstream package and not with `dependabot-core`.

**Comment by RohanNagar** [comment]
Hi @jeffwidman!

Thanks for your response. Honestly I don't particularly remember this issue, and I'm not sure if it's still happening.

You can probably just close this out if there are no other reports.

Thanks!
