### ISSUE TITLE
Wrong dependency version detected in package-lock.json, resulting in false-positive alert

### ISSUE THREAD

**Issue by AlCalzone** [dependabot/dependabot-core#2507]
**Package manager/ecosystem**
javascript

**Manifest contents prior to update**
https://github.com/AlCalzone/node-zwave-js/blob/42a8a329396d950085424537aecf618a798c4874/package-lock.json

**Updated dependency**
https://github.com/AlCalzone/node-zwave-js/network/alert/package-lock.json/handlebars/closed
The only occurence of handlebars is `^4.7.6`, however dependabot tries to update it to version 4.5.3 or later and fails with "one or more other dependencies require a version that is incompatible with this update".

**What you expected to see, versus what you actually saw**
I expected no update or alert at all, since the used version is already higher than necessary

**Images of the diff or a link to the PR, issue or logs**
https://github.com/AlCalzone/node-zwave-js/network/alert/package-lock.json/handlebars/closed/update-errors/48749721

**Comment by jurre** [comment]
Hi @AlCalzone, did you receive only an alert or also a PullRequest?

**Comment by AlCalzone** [comment]
Only an alert (or rather three to be exact), which includes an error that dependabot could not update:
![grafik](https://user-images.githubusercontent.com/17641229/92378711-89aaee80-f106-11ea-8988-8c4b42c38f38.png)

This is the description under "view details about this error":
![grafik](https://user-images.githubusercontent.com/17641229/92378751-9deeeb80-f106-11ea-9744-306b6d5cc7ff.png)

**Comment by jurre** [comment]
Thanks, I don't work on those alerts myself, but I'll route this to the right team, thanks @AlCalzone!

**Comment by sod** [comment]
We had those wrong reports now 3 times in a row the last 3 days. On first report, the dependency wasn't even present in our package-lock.json. The report yesterday and today was the same as the issue from the author - the version that's being requested to install is already installed.

**Comment by sod** [comment]
[This if the package-lock.json](https://gist.github.com/sod/bae2d41d5f0592540466ab5d59ce0148) and this the report:

![image](https://user-images.githubusercontent.com/905328/92413835-2f377f80-f152-11ea-890a-6a3d009cd72f.png)

**Comment by AlCalzone** [comment]
I'm now also getting the false positive for yargs-parser:
![grafik](https://user-images.githubusercontent.com/17641229/93048408-16056600-f65f-11ea-85f3-bc887938b18f.png)

The lowest version in my package-lock.json is the recommended 18.1.1. Dependabot is unable to create an update (which is expected I guess).

**Comment by drewmoore** [comment]
I've experienced this, as well, and I have a hypothesis on why. In my case, dependabot reports the vulnerability in yargs-parser `<= 5.0.0`. The recommended remediation is: "Upgrade yargs-parser to version 5.0.0-security.0 or later". However, when I run `npm ls yargs-parser` on the main branch of my repo, I only see the patched version `5.0.0-security.0 ` listed. I manually checked my package-lock.json, as well.
I'm guessing this is maybe caused by the the following:
- the parent dependency of the yargs-parser is yargs@7.1.1.
- the [package.json of yargs version 7.x](https://github.com/yargs/yargs/blob/7.x/package.json#L27) lists yargs-parser "^5.0.0" 
- dependabot only sees the yargs-parser version in the yargs package.json NOT my project's package-lock.json, therefore sending an alert
Would this be at all accurate? If so, is this the expected behaviour? I might be misunderstanding the internals of dependabot.

**Comment by jeffwidman** [comment]
These alerts are generated by code outside of `dependabot-core`... we only handle creating the code diff / PR to update the version.

I know that team has pushed a number of improvements in the 18 months since the last comment on this issue, so I'm going to close this for now. If I'm wrong and this is still happening for the examples illustrated above, please comment and we can re-open. Otherwise you can always open a new issue if / when it happens again.
