### ISSUE TITLE
Commit list is totally off

### ISSUE THREAD

**Issue by bep** [dependabot/dependabot-core#2510]
https://github.com/gohugoio/hugo/pull/7629

I expected 1 commit in that release.

Seems to get confused by the v1 and v2  branches.

**Package manager/ecosystem**
Go

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

I'm a big fan of Hugo, thanks for your hard work there!

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

Also, often with metadata issues like this, we use whatever the package maintainers give us, so while I haven't dug into the code, there's a 50/50 chance that this is an upstream issue with `github.com/nicksnyder/go-i18n` and not `dependabot-core`.

But if you're still seeing it in recent Dependabot PRs (I see you just recently merged a Dependabot PR two days ago) then please let me know... otherwise I'll close this.

**Comment by bep** [comment]
@jeffwidman I have no idea if this is still an issue, I haven't reacted negatively to it lately, so I suspect it's fixed. Closing.

**Comment by jeffwidman** [comment]
Thanks for the quick followup @bep.
