### ISSUE TITLE
Dependabot cannot update to the required version (Failed to create a security fix)

### ISSUE THREAD

**Issue by darkRaspberry** [dependabot/dependabot-core#2535]
I found one dup but its closed.

**Package manager/ecosystem**
JavaScript (Firebase)
**Manifest contents prior to update**
package.json
**Updated dependency**
![Screenshot from 2020-09-19 13-36-25](https://user-images.githubusercontent.com/56693429/93662426-9a9c1e00-fa7d-11ea-9ecd-3f2171a3443f.png)

**What you expected to see, versus what you actually saw**
I expect the dependent bot should provide a fix and create a pull request. Dependent unable to create a security fix. see the screenshot above.
**Images of the diff or a link to the PR, issue or logs**
image is above repo is https://github.com/darkRaspberry/Forest

**Comment by jurre** [comment]
Hi @darkRaspberry, in this case this is working as expected. Dependabot cannot create an automated fix, because `firebase-admin` depends on a version of `node-forge` of `^0.7.6` and `google-p12-pem` relies on version `^0.9.0`.

If you click `View details about this error` the message there should have some info about this.
