### ISSUE TITLE
Bumps kotlinx-coroutines-core from 1.3.1 to 1.3.9-native-mt-2.

### ISSUE THREAD

**Issue by ColtonIdle** [dependabot/dependabot-core#2547]
Installed dependabot and I keep getting this PR in my Android project that uses kotlin coroutines.

`Bumps kotlinx-coroutines-core from 1.3.1 to 1.3.9-native-mt-2.`

**Package manager/ecosystem**
gradle/maven

**What you expected to see, versus what you actually saw**
It would have been nice for this PR to be to 1.3.9 directly instead of this experimental native-mt-2 dep from kotlin.

**Comment by jurre** [comment]
Hmm, yeah it seems like our version resolver doesn't correctly recognize that as a prerelease, I'm not super familiar with Gradle prerelease/experimental releases. Is it common to append a tag like that? We may be comparing lexically when we shouldn't.

**Comment by ColtonIdle** [comment]
@jurre I don't know. Maybe this is a one off thing that is just best for me to skip this.

I asked about this on kotlin slack since I've never heard of native-mt-2 before and this is what someone said

This user https://github.com/gildor said this:

This is a special branch with developer preview of support multithreading coroutines for Kotlin native
if you are not interested in multithreading on native, use standard 1.3.9
More details https://github.com/Kotlin/kotlinx.coroutines/issues/462

**Comment by gildor** [comment]
> Is it common to append a tag like that

I wouldn't say that it's very widespread, but definitely not unique

I think depedabot shouldn't suggest update if 1.3.9 and 1.3.9-something versions are available to update on 1.3.9-something from 1.3.8

**Comment by Fryie** [comment]
This is unfortunately rather annoying and could also lead to someone who's not paying close attention (or has auto-merge enabled for patch releases) accidentally merging this.

**Comment by ashughes** [comment]
I keep running into this as well. Can [`ignore`](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#ignore) be used as a workaround? I'm not sure what a proper value for `versions` would be such that it means *ignore all versions ending with \*-native-mt\**.

I also have the added complexity that I'm using a `def coroutinesVersion` in my `build.gradle` to define the coroutine version once for multiple artifacts, so even with the correct `versions` above, I'm not entirely sure whether the `dependency-name` should be `coroutinesVersion` or `org.jetbrains.kotlinx:kotlinx-coroutines-*` or something else. Any guidance there would be appreciated!

**Comment by hiqua** [comment]
@jurre if you're looking for more examples:

https://github.com/iSoron/uhabits/pull/814
https://github.com/iSoron/uhabits/pull/754
https://github.com/iSoron/uhabits/pull/753
https://github.com/iSoron/uhabits/pull/746
https://github.com/iSoron/uhabits/pull/745

Some of these are especially bad because they prompt to update to a version that should have a lower precedence than the current version (e.g. https://github.com/iSoron/uhabits/pull/754).

According to https://semver.org/spec/v2.0.0.html#spec-item-9 it's pretty clear that these are pre-releases. It looks as simple as trimming the part after the `+` (if there's any, to remove build metadata), then mark the release as pre-release if it contains a `-`.

**Comment by Den-Rimus** [comment]
Is this going to be fixed sometime soon? Or is there a workaround?
