### ISSUE TITLE
How to configure a NPM Registry private?

### ISSUE THREAD

**Issue by crtdaniele** [dependabot/dependabot-core#2581]
Hi,
I have an issue with the configuration for NPM Private registry.

Details:
Registry in Azure
Javascript

The configuration of credentials:

  {
    "type" => "npm_registry",
    "token" => "", It is a new personal token (from azure is ok?)?
    "registry" => "pkgs.dev.azure.com" The full address or only the domain?
  },

Another question, I need the .npmrc in the root of project?
In case of yes, how to configure it?

The error:

Failed processing: The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): FULL_PATH_REGISTRY from package-lock 

Thanks in advance.
Daniele

**Comment by peijianju** [comment]
Hi, this is an example in articulatory, hope it helps

```
   "type" => "npm_registry",
    "token"=> "your_username:api_token", 
    "registry"=>"artifcatory_URL:443/artifactory/api/npm/aFakeRepo"
```

* You need the port number in the registry, in your case I think you need FULL_PATH_REGISTRY
* You can the basd64 encoded your_username:api_token and put it in the token field instead

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've greatly improved our support for private registries since then. I'm pretty sure this is resolved now, so going to close, but if for some reason I misunderstood please comment and we can re-open.
