### ISSUE TITLE
I get Dependabot alert for hibernate-validator version 5.3.6

### ISSUE THREAD

**Issue by TatuLund** [dependabot/dependabot-core#2593]
We have Java project with maven used for dependency management.

Our project depends on hibernate-validator version 5.3.6, we still get alerted

![image](https://user-images.githubusercontent.com/14309836/94914978-b4455880-04b4-11eb-9f17-d1be9e00dc63.png)

Our dependency is

```
<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-validator</artificatId>
  <version>5.3.6</version>
</dependency>
```

The difference to the screenshot is that we have "5.3.6" and your alert has "[5.3.6,)". Does Dependabot do exact string matching here, as logically 5.3.6 should be accepted here. We can't use open ended dependency in a framework product.

**Comment by jeffwidman** [comment]
👋 Hey there, sorry for the delay here.

So the security alerts are actually triggered by a completely different set of code from `dependabot-core`. I'm afraid I don't have much visibility into all the changes they've made over the past two years, but I know it's a lot... 

From your description, it sounds like there's three problems:
1. you're already running a patched version, so why is this complaining?
2. why is it suggesting an open-end version?
3. Dependabot tried to open a PR to fix the problem, but ran into errors.

For 1, I suspect they've fixed it already. 

For 2, this is just a docs suggested change, it's not necessarily what the Dependabot PR would suggest.

For 3, it's probably caused by the bug in 1.

Given that this issue is nearly two years old, I'm going to close on the assumption that upstream already fixed the bug, but if you continue to see it, please comment and I'll happily re-open.
