### ISSUE TITLE
Wrong change information on java/pom type

### ISSUE THREAD

**Issue by rantoniuk** [dependabot/dependabot-core#2679]
Links and changelogs are wrong when dependency type is java/pom.

See https://github.com/jenkinsci/jira-plugin/pull/295:
- says correctly about `Bumps bom-2.222.x from 15 to 16`
- link and changelogs are wrong, they should point to https://github.com/jenkinsci/bom/releases/tag/bom-16 instead of https://github.com/jenkinsci/pom

**Comment by warden** [comment]
Still happening, see https://github.com/jenkinsci/jira-plugin/pull/309

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by jeffwidman** [comment]
Closing due to lack of user response.

**Comment by jeffwidman** [comment]
I double-checked, and it looks like this may now be fixed, since the links / changelog appears to be correct for:
* https://github.com/jenkinsci/jira-plugin/pull/505

They don't deeplink to the specific release, but they do link tot he top-level releases and from there you can pick the specific release... that's certainly better than it was of linking to the incorrect release page altogether.
