### ISSUE TITLE
Remove constraint versions.

### ISSUE THREAD

**Issue by terabytesoftw** [dependabot/dependabot-core#2707]
hi, thanks for the work of this wonderful tool, Its posible remove constraint versions:

Example:

```json
"infection/infection": "^0.18.0 || ^0.19.0" ---> "infection/infection": "^0.19.0",
```

Thks.

**Comment by jeffwidman** [comment]
If your package specification file has a range, I don't think it'd be appropriate for us to unilaterally change that to a single pin. 

Instead, we'd ideally just bump the upper end of the range so that it continues to allow the latest, but doesn't prevent lower. I know we do that today for some python ecosystems.
