### ISSUE TITLE
Use CODEOWNERS along with module-level dependency configs for default reviewers in monorepo

### ISSUE THREAD

**Issue by colecrtr** [dependabot/dependabot-core#2776]
I am working in a monorepo that uses maven with a file structure like so:
```
/pom.xml
/a/pom.xml
/b/pom.xml
/c/pom.xml
```
where `a`, `b`, and `c` are `<modules>` defined in the root `/pom.xml`. Versions are defined in the root pom and the module-level poms simply state whether or not they use those dependencies in that module.

and a CODEOWNERS like so:
```
/a/ @team-a
/b/ @team-b
/c/ @team-c
```

The feature I am looking for is for dependabot to assign default reviewers based on A) what module(s) use the dependency being upgraded and B) what CODEOWNERS are defined for those modules/directories. For example, if dependabot upgraded a dependency in `/pom.xml` that `/a/pom.xml` and `/c/pom.xml` use, then assign `@team-a` and `@team-c` as default reviewers to the version bump PR.

I googled it and couldn't find any documentation on it but would be delighted to know it already exists.

**Comment by jeffwidman** [comment]
This one would be really tricky, and I don't think the requested solution is in-scope for Dependabot to solve... we'd rather stay focused on parsing packages and creating PR's rather than supporting really complex review inheritance structures.

As a workaround I'd suggest a GitHub action that parses the subfolder manifests to generate the list of deps they inherit from the top level manifest and then watches the PR's opened by Dependabot against that list of deps in order to assign custom reviewers. You may also find https://github.com/dependabot/fetch-metadata helpful for wiring up this custom workflow. 

If that doesn't provide what you want, there may be a way we could extend Dependabot to better expose the information you need, although we'd still leave the custom code reviews for you to wire up yourself based on that information. But I'm not coming up with something obvious right now that we could expose that we don't already... could also potentially leverage [this Dependency Graph API to analyze the commits](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28#get-a-diff-of-the-dependencies-between-commits )on the Dependabot PR's to see what specifically changed.

I'm going to close because not in scope, but if there's information we could expose to make it easier for you to wire up your custom actions workflow, feel free to file an issue. For something like this, we'd want to give you the raw data / building blocks, but then what you do with that is up to you because when we get to long-tail use cases like this, everyone's needs are slightly different.
