### ISSUE TITLE
Docs: Add something about which files are scanned by dependabot

### ISSUE THREAD

**Issue by bmacher** [dependabot/dependabot-core#2837]
Hi there, I am new to dependabot and was searching the documentation to know which files are scanned by dependabot. I would like to use it in my company, however we are not allowed to use tools that do code scans. It would be okay, if dependabot would only search for `package.json`, `package-lock.json` or `yarn.lock` though.

Could you give me some informations about that?

Thank you! :-)

**Comment by feelepxyz** [comment]
@bmacher dependabot currently only fetches the manifests for npm/yarn from your repo and any path dependencies that are linked from the manifest although we have plans of changing this to do a full repo clone in order to support vendoring (we already do this for go modules).

Once you've set up dependabot version updates you can see which files it monitors by going to Insights > Dependency Graph > Dependabot and clicking on the `...` icon:

<img width="900" alt="Screenshot 2020-12-10 at 09 39 09" src="https://user-images.githubusercontent.com/20165/101754379-96572e00-3acb-11eb-9091-206784c2850d.png">

**Comment by bmacher** [comment]
Thanks a lot!
