### ISSUE TITLE
Incorrect Version in Title

### ISSUE THREAD

**Issue by evantahler** [dependabot/dependabot-core#2861]
Hi!  Dependabot is great, and I use it at work and personal projects.  In this one instance (https://github.com/grouparoo/grouparoo/pull/1088) the title Depenabot created was wrong.

**Package manager/ecosystem**
* Javascript

**What you expected to see, versus what you actually saw**
The title should have been: `Bump uuid from 8.3.1 to 8.3.2`
The title was: `Bump uuid from 3.4.0 to 8.3.2`

You can see in the PR that the versions in the monorepo were all moving from v8.3.1 to v8.3.2

**Images of the diff or a link to the PR, issue or logs**
https://github.com/grouparoo/grouparoo/pull/1088

**Comment by Himadu2000** [comment]
Also happened, https://github.com/Cezerin2/Cezerin2/pull/287/files and broke the project sadly. Hope this gets fixed quickly.

**Comment by Himadu2000** [comment]
Also happened in https://github.com/Cezerin2/Cezerin2/pull/461, where the title was `feat: Package bump @types/node from 17.0.41 to 17.0.42` but also included `ws` updated from 8.7.0 to 8.8.0.

**Comment by jeffwidman** [comment]
👋 sorry for the slow followup here. We're finally catching up on some of our backlog.

For the original issue, it's been 2+ years since it was filed and we've pushed a lot of fixes since then. I'm guessing this is fixed but tougher to repro since underlying repo is archived. I don't think it's worth tracking down at this point, if you see it again please file a new issue and we can hopefully jump on it faster.

For the second cases in April / June of last year, we had some internal instability around this time IIRC, and that may have resulted in races--for example I see the broken PR happened at same time as a correct-looking PR, but they had the same content just different descriptions. Unlikely to be a logic bug in `dependabot-core` library itself given there are two PR's and one had the right content and the other didn't.., so probably a race on the back-end infra. Don't know for sure, but unfortunately logs are long gone at this point so would be tough to track down. 

For the final PR you posted, I don't see the bump in `ws` in that PR description? Only the `@types/node`...

I'm going to close this as can't repro, but if you see it again please file a new issue and we can try to track it down before the logs expire.

**Comment by pascalfiv** [comment]
Hi @jeffwidman this seems to be quite an old issue but it happened again - although can not provide a reproducible repo..  but proof with a screenshot.  
Noticed (while writing the comment) that the version is correct when taken from the package-lock.json but not from the package.json - Maybe that was the initial problem all the long.

<img width="1874" alt="Image" src="https://github.com/user-attachments/assets/db2100f6-7bbc-4cc5-9ac5-82cbc01ee7d7" />
