### ISSUE TITLE
Ignore without range should not attempt a check

### ISSUE THREAD

**Issue by bryannaegele** [dependabot/dependabot-core#3047]
The github integration currently doesn't support private packages for Elixir and Hex.pm. After adding `ignore` statements for the private packages in our mix file, the check still fails as Dependabot appears to apply ignores after checking for updates.

If a package is marked to be ignored completely (no range) then Dependabot should simply skip any checks for that dependency.

https://github.com/dependabot/dependabot-core/issues/2778
https://github.blog/changelog/2020-12-02-dependabot-version-updates-from-private-github-repositories/

**Comment by jeffwidman** [comment]
Yeah, makes sense.

This is an ecosystem-by-ecosystem change... we could fix for top-level dependencies in most ecosystems, but this will likely continue to happen with indirect deps... ie, we prefer to shell out to the native package manager wherever possible so it may see that a top-level dep requires an indirect dep on a private registry... and we don't have an easy way to stop that.

Also, we recently shipped support for private hex repos: https://github.com/dependabot/dependabot-core/pull/5043#issuecomment-1325631034

So I'm going to close because even though we didn't fix the underlying issue, we fixed the symptom and the underlying issue will vary depending on the ecosystem. As we encounter it we can fix it.
