### ISSUE TITLE
Dependabot just removes package-lock.json without actual version bump

### ISSUE THREAD

**Issue by saschanaz** [dependabot/dependabot-core#3099]
This still happens after #2643 is fixed.

**Package manager/ecosystem**
npm

**Manifest contents prior to update**
https://github.com/w3c/webidl2.js/blob/f0b95c34dba8c3ac797bb0843c3520e55fc47515/package.json

**Updated dependency**
webpack

**What you expected to see, versus what you actually saw**
It should update package.json but it's untouched, instead it removes package-lock.json

**Images of the diff or a link to the PR, issue or logs**
https://github.com/w3c/webidl2.js/pull/540

**Comment by jurre** [comment]
Thanks @saschanaz, will have a look at this today. If I understand correctly this also happened before npm 7 support landed?

**Comment by feelepxyz** [comment]
@saschanaz it looks like your project is being detected as a library, which is why only the lockfile is updated.

You can configure the default strategy by setting the [`versioning-strategy`](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy) to `increase` to always keep the `package.json` in sync with the lockfile (in your case the default is `widen`).

**Comment by feelepxyz** [comment]
The removed entries in `package-lock.json` look correct to me, they are all related to the dropped dependency: `pkg-dir`: https://github.com/w3c/webidl2.js/pull/540/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L3609

**Comment by feelepxyz** [comment]
FYI the logic to detect libraries is here, and your project is being found on npm: https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/library_detector.rb#L34-L51

**Comment by feelepxyz** [comment]
Created an issue to change the default for this case https://github.com/dependabot/dependabot-core/issues/3103

We'll probably not get to it anytime soon but will keep an eye on it.
