### ISSUE TITLE
Dependabot couldn't fetch github refs, but they're there

### ISSUE THREAD

**Issue by notEthan** [dependabot/dependabot-core#3105]
dependabot has been opening and closing issues left and right about dependencies it should be able to find

**Package manager/ecosystem**
 ruby:bundler

**Updated dependency**
Gemfile updated in commit https://github.com/notEthan/jsi/commit/774106792ae64ac820cdccc127a66da3d155e4d3
with dependency `gem 'scorpio', github: 'notEthan/scorpio', ref: 'dcb642564341c5815a5cbecc13ac6308836d7f70'`

the referenced commit on github:
https://github.com/notEthan/scorpio/commit/dcb642564341c5815a5cbecc13ac6308836d7f70

**link to the issues**
all of these:
https://github.com/notEthan/jsi/issues?q=is%3Aissue

don't know why dependabot is opening them, don't know why they're getting closed a while later - nothing is changing, I haven't touched those dependencies in weeks, and they're valid references.
the spreedly_openapi.git references are to a tag and haven't changed in months. the scorpio.git change is more recent.

**Comment by jurre** [comment]
Hi @notEthan, I think the a fix here would be to migrate to the GitHub native version of Dependabot. The native version does not rely on issues to communicate failures, and is a lot more robust in general.

It seems like this has not happened for a while now, and since we delete logs after 2 weeks it's hard to figure out what happened, but it looks like we had some networking issues. I'm going to close this out for now, but if it happens again please reopen this (and maybe ping me directly). Apologies for the noise.
