### ISSUE TITLE
[Github version] Add option to configure the files to check for updates to explicitly.

### ISSUE THREAD

**Issue by AraHaan** [dependabot/dependabot-core#3113]
Currently dependabot auto detects files to check for updates with. However there are sometimes a bug where it just skips a file that it needs to check for updates to. In my case it checks the ``*.targets`` file instead of the ``*.props`` file however the props file contains all the packages while the ``*.targets`` file contains msbuild tasks only that are inlined but common which results in some dependencies never getting updates. In this case the props and targets files here gets packed into a nuget package where it would then when the package is installed would install some analyizers that I decided to ship standard with my nuget metapackage (Sdk).

So as such I would like to be able to override what dependabot auto detects (in case it checks the wrong files) to basically list ONLY the files that I want dependabot to check for updates on.

Bonus points if dependabot was also able to learn how to checkout submodules as well before checking for updates too (since it would 404 if you have a submodule project that is part of an sln file in the repository root).

**Comment by jeffwidman** [comment]
I'm going to close this due to the reasons I explained in https://github.com/dependabot/dependabot-core/issues/2841#issuecomment-1416705485. 

What you're describing sounds more generally like behavior that Dependabot should automatically do in the code, rather than needing workarounds/overrides through config.

Not opposed to making these changes, just please file specific issues for the specific use cases / problems you're seeing. Again, see details in https://github.com/dependabot/dependabot-core/issues/2841#issuecomment-1416705485.
