### ISSUE TITLE
Unable to update npm dependency that is a private github package

### ISSUE THREAD

**Issue by saiichihashimoto** [dependabot/dependabot-core#3120]
There is no way for a repo in github to update an npm dependency that is a private github package.

When using node and having a dependency that is a github package from a private org, dependabot will not update the dependency even if the correct registry is in the `.npmrc` because it does not have the authToken in it.

```json
// package.json
{
  "dependencies": {
    "@my-private-github-org/package-that-dependabot-wont-update": "1.0.0"
  }
}
```

- This is **not** about dependabot.com. This is for github's dependabot.
- This is **not** solved by having the authToken in the `.npmrc`, ie `//npm.pkg.github.com/:_authToken=${{ secrets.SOME_TOKEN_HERE }}`. This assumption only works for github's CI, breaking local development and other CI solutions without hacky solutions.
- This is **not** solved by appending the `authToken` to the `.npmrc` or any other script within github actions/CI. Dependabot needs to check for version updates before creating a commit at all, which means it needs to do this without running any custom scripts.
- [Giving dependabot permissions to both repos](https://github.com/dependabot/dependabot-core/issues/2778#issuecomment-755222438) still doesn't solve the issue.
- This is **not** solved with `.yarnrc`, or monorepos, or anything that generally involves switching technologies to avoid the problem.

I tend to find a lot of issues about something [similar](https://github.com/dependabot/dependabot-core/issues/2778) but not quite this. It seems like something solvable, given that all the technologies involved are github except for npm itself.

**Comment by thepwagner** [comment]
👋 private registry support, such as GitHub packages, is on the way: https://github.com/github/roadmap/issues/67

> all the technologies involved are github except for npm itself.

https://github.blog/2020-03-16-npm-is-joining-github/ there really are no excuses :)

**Comment by blakemorgan** [comment]
@thepwagner I thought private registry support was already here as stated in this [GitHub blog post](https://github.blog/changelog/2020-12-02-dependabot-version-updates-from-private-github-repositories/).

I'm having a similar issue. The dependency I need to be updated is a public repo in a GitHub organization. The documentation referenced by the OP says you only need to add it for private repos. And because the repo is already public, it doesn't appear on the list of repos to give Dependabot access to. When running Dependabot, this is the error that occurs:

```
updater | INFO <job_88811731> Checking if @byu-oit/uapi-ts 2.2.0 needs updating
  proxy | 2021/02/12 15:54:30 [196] GET https://npm.pkg.github.com:443/@byu-oit%2Fuapi-ts
  proxy | 2021/02/12 15:54:30 [196] 401 https://npm.pkg.github.com:443/@byu-oit%2Fuapi-ts
updater | INFO <job_88811731> Handled error whilst updating @byu-oit/uapi-ts: private_source_authentication_failure {:source=>"npm.pkg.github.com"}
```

The `.npmrc` file for that package looks like this:

```
@byu-oit:registry=https://npm.pkg.github.com
engine-strict=true
```

Why am I getting a `private_source_authentication_failure` when it is a public repo?

**Comment by thepwagner** [comment]
@blakemorgan the linked blog post has several limitations:

1. Dependencies must be installed from _git_ sources, not NPM packages (e.g. in `package.json`):
```json
{
  ...
  "dependencies": {
    "@byu-oit/uapi-ts": "github:byu-oit/uapi-ts#v2.2.0",
    ...
  }
}
```

2. Further, the linked blog post requires all private repositories have the same owner (this doesn't matter as the repo you suggested is public).

---

> Why am I getting a private_source_authentication_failure when it is a public repo?

This is because of how GitHub packages works: while the source git repository is open to anonymous viewers, the published package is only accessible _authenticated GitHub users_ (not "anonymous").

You can confirm this using a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with the `packages:read` scope:
```
$ curl -IHEAD https://npm.pkg.github.com:443/@byu-oit%2Fuapi-ts
HTTP/2 401
server: GitHub Registry

$ curl -H"Authorization: Bearer $GITHUB_TOKEN" -IHEAD https://npm.pkg.github.com:443/@byu-oit%2Fuapi-ts
HTTP/2 200
server: GitHub Registry
```

I'd suggest:
- Switch your project to reference this dependency as a git repository (this may not be feasible, e.g. if the package is compiled TypeScript but the repository contains only sources).
- Publish `api-ts` to the https://www.npmjs.com/ registry, which does allow truly anonymous access.
- Wait for https://github.com/github/roadmap/issues/67 , at which point Dependabot will allow authentication to GitHub Packages

Neither of these options are great, sorry.

**Comment by Spunkie** [comment]
github/roadmap#67 is now closed and I've followed the example in the [linked blog post,](https://github.blog/changelog/2021-03-15-dependabot-private-registry-support-public-beta/) but dependabot is still unable to access my private github packages.

Rough example repo: https://github.com/Spunkie/junky_lerna_deps_example
Dependabot log: https://gist.github.com/Spunkie/4bd384073680cf98f6a914ab4fd1af54

**Comment by thepwagner** [comment]
@Spunkie thanks for for the clean bug report. There's definitely an issue in those logs:
* Requests to `https://api.github.com:443/` are followed by a `authenticating github api request` message, as expected.
* Requests to `https://npm.pkg.github.com:443` however aren't being authenticated.

This means Dependabot isn't including the registry configuration during this update. The cause can be traced to this error: https://github.com/Spunkie/junky_lerna_deps_example/runs/2123303858

The `-` on [this line](https://github.com/Spunkie/junky_lerna_deps_example/blob/03b99ba3750fe585db53b25231a5718e9512351a/.github/dependabot.yml#L3) means that `registries` is interpreted as an array, when it should be an hash/object. You can fix it by removing the `-`:

```yaml
registries:
  npm-github-spunkie:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
    token: ${{secrets.GH_PAT}}
```

To elaborate, while JSON configuration isn't supported it's useful to explain the difference. Your current config translates to:
```json
{"registries": [{"npm-github-spunkie":"","type":"npm-registry", "url":"..."}]}
```

But the expected format is:
```json
{"registries": {"npm-github-spunkie": {"type":"npm-registry", "url":"..."}}}
```
