### ISSUE TITLE
[bug][composer] Fails to interpret composer.json version constraints

### ISSUE THREAD

**Issue by yannoff** [dependabot/dependabot-core#3150]
**Package manager/ecosystem**
[composer](https://github.com/composer/composer)

**Manifest contents prior to update**
*Here the contents of the `require` section of the `composer.json`:*
```javascript
    "require": {
        "ext-json": "*",
        "symfony/yaml": "^3.4",
        "yannoff/y-a-m-l": "^1.1",
        "yannoff/console": "^1.2"
    }
```

**Updated dependency**
[`symfony/yaml`](https://github.com/symfony/yaml)

**What you expected to see, versus what you actually saw**
While the component dependency should **never** upgrade to a version greater than `3.4`  **given the version constraint** , `dependabot `created the following PR: `Bump symfony/yaml from 3.4.23 to 5.2.3` 

**PR Preview**
*It's a private repo, so here is the screenshot:*

![image](https://user-images.githubusercontent.com/20049273/108116339-b55dd780-709b-11eb-9415-dea71e340994.png)

**Comment by jurre** [comment]
You'll want to configure dependabot to use the `lockfile-only` versioning strategy: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy, by default `increase` is used as the strategy for apps.

I'm going to close this issue as it seems like expected behavior, but please feel free to reopen if I missed something or ping me for follow up questions!

**Comment by yannoff** [comment]
@jurre Many thanks for the quick reply :smile_cat: and for the solution too ! I'll try it ASAP :rocket:

**Comment by yannoff** [comment]
@jurre Thanks a lot, works great using the `lockfile-only` strategy :rocket: :smiley_cat: 

![image](https://user-images.githubusercontent.com/20049273/109864841-9f3b4400-7c63-11eb-9a6a-9dfb39ca7d0c.png)

I just expected this to be the default behavior, but maybe this is not the most common use case...
