### ISSUE TITLE
bug: dependabot incorrectly changed from one docker tag to another

### ISSUE THREAD

**Issue by scyto** [dependabot/dependabot-core#3173]
Dependabot should not have changed `FROM node:erbium-buster AS local-copy-src` to `FROM node:15.9.0-alpine AS local-copy-src` in the file docker/Dockerfile.contrib in this commit.

https://github.com/zwave-js/zwavejs2mqtt/commit/1bb27519c0b92a63621f15116c83f118e7e8949a#diff-4ddc2e10398d5c169795b7937f893ec72d2619b395259c592156a5dd0b476c9f

We are unclear why it did this.

Note: the change to the other file in this commit was ok.

**Comment by Sarke** [comment]
Same for me.  It looks like it just grabs the first tag and applies it to all the Dockerfiles.

https://github.com/Sarke/docker-php-fiber/pull/4/commits/66a5b4d74a38b7c9be9445979f281a7ce050c894

```
- FROM php:8.0.1-apache
+ FROM php:8.0.2-apache
```
```
- FROM php:8.0.1-cli
+ FROM php:8.0.2-apache
```
```
- FROM php:8.0.1-zts
+ FROM php:8.0.2-apache
```

**Comment by feelepxyz** [comment]
@mctofu did your PR fix this issue? https://github.com/dependabot/dependabot-core/pull/3277

**Comment by mctofu** [comment]
Yup, the fix has been released and I tested that it covers both of these reports. We now preserve the distinction between tags like `php:8.0.1-apache` and `php:8.0.1-cli` as long as they are in separate files. The zwave-js/zwavejs2mqtt example did include `node:erbium-buster` and `node:erbium-buster-slim` in the same file but since they don't reference a version number they won't receive updates.
