### ISSUE TITLE
Github Security Alerts not being created when yarn.lock contain multiple resolved packages

### ISSUE THREAD

**Issue by mehagar** [dependabot/dependabot-core#3198]
My repo has a yarn.lock that resolves to multiple versions of the same package, so it looks like this:

```
elliptic@^6.0.0:
  version "6.4.0"
  resolved "https://registry.yarnpkg.com/elliptic/-/elliptic-6.4.0.tgz#cac9af8762c85836187003c8dfe193e5e2eae5df"
  dependencies:
    bn.js "^4.4.0"
    brorand "^1.0.1"
    hash.js "^1.0.0"
    hmac-drbg "^1.0.0"
    inherits "^2.0.1"
    minimalistic-assert "^1.0.0"
    minimalistic-crypto-utils "^1.0.0"

elliptic@^6.5.2:
  version "6.5.3"
  resolved "https://registry.yarnpkg.com/elliptic/-/elliptic-6.5.3.tgz#cb59eb2efdaf73a0bd78ccd7015a62ad6e0f93d6"
  integrity sha512-IMqzv5wNQf+E6aHeIqATs0tOLeOTwj1QKbRcS3jBbYkl5oLAserA8yJTT7/VyHUYG91PRmPyeQDObKLPpeS4dw==
  dependencies:
    bn.js "^4.4.0"
    brorand "^1.0.1"
    hash.js "^1.0.0"
    hmac-drbg "^1.0.0"
    inherits "^2.0.1"
    minimalistic-assert "^1.0.0"
    minimalistic-crypto-utils "^1.0.0"
```

That first package should trigger an alert because of this security advisory: https://github.com/advisories/GHSA-vh7m-p724-62c2
But it doesn’t. I suspect that the security alerts don’t work properly when there are multiple resolved packages.

**Package manager/ecosystem**
yarn.lock

**Manifest contents prior to update**

**Updated dependency**

**What you expected to see, versus what you actually saw**

I expected there to be a PR created for updating the `elliptic` package.

**Comment by asciimike** [comment]
I'm curious, why do you have two different versions of the same package? I assume that the Dependency Graph sees that you've got a version that's patched, so it doesn't raise the alert.

**Comment by mehagar** [comment]
@asciimike I'm not exactly sure how we got into this situation, but I suspect it is because of how Yarn's dependency resolution algorithm works. There is even a separate deduplication tool [here](https://github.com/atlassian/yarn-deduplicate#duplicated-packages) that is used exactly for this purpose.

**Comment by mehagar** [comment]
This just started working now! Thanks to whoever fixed this!

**Comment by mehagar** [comment]
This just started working for me, and Dependabot created an update to fix the issue by deduplicating the packages, which is what I want. I'm not sure whether there was a change to fix this or not.

**Comment by jeffwidman** [comment]
A couple of fixes shipped recently that should resolve this... one just shipped a few days ago.

Also, please keep in mind this repo / issue tracker is now primarily about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves, as they're now two separate teams and that team doesn't monitor this issue tracker (nor should they). Versus this issue is about the alerts themselves, not the resulting PRs.

So if you're still seeing problems, I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles creating alerts. Feel free to drop a breadcrumb link on this issue to the discussion.
