### ISSUE TITLE
Allow option to use full dependency name for gradle `display_name` property

### ISSUE THREAD

**Issue by john-mejia** [dependabot/dependabot-core#3353]
As seen [here](https://github.com/dependabot/dependabot-core/blob/main/gradle/lib/dependabot/gradle.rb#L24), Dependabot uses the last artifact of a colon delimited string as the `display_name` for Gradle dependancies which ultimately make it to the commit message/PR title. For some of our Android dependencies this can end up being a very similar name or even the same in some cases.

This causes a small inconvenience when parsing through git commits in command line or release logs as they make it harder to understand at a glance which dependency was updated.

If the full name was used, the commit message would provide more useful information at a glance. 

**Example dependancies:**
com.amplitude:android-sdk
com.optimizely.ab:android-sdk

**Current PR titles for these:**
Bump android-sdk from 2.30.1 to 2.30.2
Bump android-sdk from 3.10.0 to 3.10.1 

**PR titles after proposed change:**
Bump com.amplitude:android-sdk from 2.30.1 to 2.30.2
Bump com.optimizely.ab:android-sdk from 3.10.0 to 3.10.1

**Comment by jeffwidman** [comment]
Makes sense, particularly for the Java ecosystem.

The one caveat is these can get quite verbose so we probably need to limit the max length, and either truncate if longer or flip back and forth.

I'm not sure what the max should be, I'll ask internally to see what we've landed on in the past.

**Comment by jeffwidman** [comment]
Related:
* https://github.com/dependabot/dependabot-core/issues/5761

**Comment by jeffwidman** [comment]
Thinking about this more, ideally for package truncation, we'd go from `parent-java-path/package-name` to `parent-ja.../package-name` as retaining the full `package-name` seems more important than accidentally truncating it.

So there's probably two parts for enforcing PR length here:
1. enforcing a global PR length at the pull request creator code, for now we can ignore this
2. locally enforcing a reasonable length on the full dep name... we don't know at this point though what length will be occupied by the path / version string, so we can really only guess at it... but that's probably good enough for us. This is where we do the "truncate parent path rather than package name".

Unfortunately point 1 has no semantic context that the parent path is okay to truncate but not the package name, so we probably just need to pick a ballpark number that sounds reasonable and go with it for point 2.
