### ISSUE TITLE
[Question] Why so many versions ?

### ISSUE THREAD

**Issue by ncoden** [dependabot/dependabot-core#343]
I took a look at https://github.com/dependabot/dependabot-core/blob/master/CHANGELOG.md and noticed that there is sometimes 10 versions a day. At [Foundation](https://github.com/zurb/foundation-sites) we release a new version every 1 to 6 months (I admit this is not better).

So I wonder: is there any benefits for this release process ? Are you deploying dependabot 10 times a day ?

Thanks.

**Comment by greysteil** [comment]
We deploy a bit more than 10 times a day. The structure of Dependabot is as follows:
- Dependabot Core (this repo) contains the business logic for checking for updates and creating PRs
- Dependabot Backend (private) is a web app that exposes an API to our dashboard, talks to GitHub, kicks off update runs, and creates PRs. It uses Dependabot Core for the PR creation bit
- Dependabot Updater (private) is an app that runs in an isolated environment and creates the content for PR updates (the updated files). It's isolated from Dependabot Backend because it has to run unsafe code, so can't have its own database or environment variables. It also uses Dependabot Core
- Dependabot Frontend is just a React app, consuming the API from Dependabot Backend

With the above setup, a lot of Dependabot improvements happen in Dependabot Core, but we want to pull them into the updater / backend immediately. As a result, I end up cutting a *lot* of releases! It might look a bit mad, but aside from wasting my time writing `git tag v0.x.x` several times a day the whole thing works pretty well. The alternative would be for me to pin to git references from the backend and updater, but I think doing full releases is nice.

Hope that's informative, and thanks for using Dependabot!

**Comment by greysteil** [comment]
Also worth saying that I think the many-releases approach above is sensible for Dependabot because it's only really got one user (Dependabot). I wouldn't recommend it for Foundation!
