### ISSUE TITLE
urllib3 not being updated

### ISSUE THREAD

**Issue by ThiefMaster** [dependabot/dependabot-core#3462]
**Package ecosystem**
pip / pip-compile
**Package manager version**
pip
pip-compile, version 5.5.0 
**Language version**
Python 3.9
**Manifest location and content prior to update**
https://github.com/indico/indico/blob/9e57e437fe5c2f1199bd2414264114de32bba949/requirements.txt#L287
**dependabot.yml content**
n/a (using defaults)
**Updated dependency**
urllib3
**What you expected to see, versus what you actually saw**
I expected to get a dependabot PR to update my requirements.txt accordingly. However, github/dependabot fails to do that and it looks like it's assuming this update is not allowed because of the current version being pinned there:

```
updater | INFO <job_108340039> Requirements to unlock update_not_possible
updater | INFO <job_108340039> Requirements update strategy bump_versions
updater | INFO <job_108340039> The latest possible version of urllib3 that can be installed is 1.26.3
updater | INFO <job_108340039> The earliest fixed version is 1.26.4.
```

**Comment by jeffwidman** [comment]
👋 Hey Adrian 😄 

I don't think the issue here is that the current version is pinned--the whole point is for Dependabot to bump that pin.

Typically there's another dep in the graph that's specifying a pin on `1.26.3`. So when `pip-compile` goes to bump `urllib3`, it gets to the verification step and says "hey, this creates a conflict and can't be updated due to another constraint" which bubbles up as this `Requirements to unlock update_not_possible` line.

I took a look at the current `requirements.txt` on `master`, and looks like you're already past this version, so I assume this isn't reproducible.

But if it is, then you can set the env var `DEBUG_HELPERS =true` and run [the dry-run script within docker](https://github.com/dependabot/dependabot-core/#running-with-docker) to have `dependabot-core` spit out the exact `pip-compile` command it's running... as well as the output from that command. We don't do that in prod for security reasons. But it tends to pretty clearly show whether it's a constraint problem or something else.

Obviously it'd be nice if Dependabot was smart enough to unlock whatever other constraint is locked here and bump both together... we've put some work into doing that in `npm`, but not in Python. The general concept of grouped updates is tracked in #1190, that's probably the best place to subscribe for updates.

I'm going to close assuming this specific `urllib3` problem isn't reproducible, and the broader grouped updates idea is tracked elsewhere, but if for some reason I'm wrong please comment and we can reopen.
