### ISSUE TITLE
Dependabot is excluding (ignoring) the packages it's supposed to keep updated

### ISSUE THREAD

**Issue by andreagrandi** [dependabot/dependabot-core#3589]
## Basic info:

**Package ecosystem**
pip

**Package manager version**
N/A

**Language version**
Python 3

**Manifest location and content prior to update**
N/A

**Updated dependency**
N/A

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**

https://github.com/andreagrandi/andreagrandi.it/pull/137/files

## Previous behavior in Dependabot Preview:

Previously Dependabot was able to detect these upgrades are needed

## Current behavior in GitHub-native Dependabot:

Now Dependabot is putting `ipython`, `pelican` and `markdown` in the `ignore:` section of `.github/dependabot.yml` and this (I suppose) will make them ignored by dependabot.

**Comment by brrygrdn** [comment]
Hi @andreagrandi  

The ignore file that was generated as part of the migration includes these packages along with specific version. This means only those specific releases will be ignored for purposes of your scheduled updates.

As part of the migration, we look at Dependabot Preview PRs that were closed rather than merged, e.g. https://github.com/andreagrandi/andreagrandi.it/pull/133

When a Dependabot PR is closed without merging, Dependabot will not re-attempt to create a PR to update to that version as it has either been rejected by the user or superseded.

As part of the migration, we place any versions in closed Dependabot Preview PRs in the generated updated config so GitHub-native Dependabot doesn't try to recreate anything that you have either rejected or has been recently superseded.

This should not affect any updates to `ipython`, `pelican` and `markdown` in future.

**Comment by andreagrandi** [comment]
Thank you so much for your explanation Barry. I will go on and merge my PR then. I suppose once those packages will be upgraded, I will eventually be able to simplify the `ignore:` section and remove them from there, right?

**Comment by brrygrdn** [comment]
That's right, yeah - once you have at least one new upgrade PR for them merged they can be removed entirely 👍🏻
