### ISSUE TITLE
dependabot doesn't attach changelog from private hosted pip server

### ISSUE THREAD

**Issue by 2Fake** [dependabot/dependabot-core#3607]
**Package ecosystem**
pip
**Package manager version**
21.0.1
**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Hi,

I managed to create a dependabot within our private gitlab instance. It's working fine with external python dependencies and almost fine with internal dependencies. 

Dependabot seems not able to find a Changelog and so it's not attached to PR. We hosted our python packages on a minimal pypiserver (https://hub.docker.com/r/pypiserver/pypiserver) 

Could you tell me, where dependabot gets the changelogs from? Is it pulled from the pypiserver or from gitlab? Changelog.md is in the repo and attached to the tags/releases

Hope you can help!

Have a nice day,
Markus

**Comment by jurre** [comment]
> Could you tell me, where dependabot gets the changelogs from? Is it pulled from the pypiserver or from gitlab? Changelog.md is in the repo and attached to the tags/releases

Dependabot will actually go through quite a few different sources to attempt to fetch the metadata, it'll try [the pypi listing](https://github.com/dependabot/dependabot-core/blob/c3f01dff836d2031203c3870f772e42a42668b25/python/lib/dependabot/python/metadata_finder.rb#L24-L31) and follow any links it finds there. It'll also check GitLab or GitHub.

It's hard to say why this isn't working, it seems that you are not using the GitHub-native version of Dependabot but instead running it yourself on GitLab, so I won't be able to help much with debugging, but I'm happy to answer specific questions to help you dig into what's happening.

**Comment by 2Fake** [comment]
Maybe the first question is how can i get more debug information from dependabot?

**Comment by 2Fake** [comment]
@asciimike I run it in a independent docker container within a gitlab runner. So I should have full access to all logs.

**Comment by asciimike** [comment]
Apologies, hadn't had my morning coffee yet.

**Comment by chrislujan** [comment]
I have a similar experience with ruby gems, is there any documentation on what is needed for changelogs to be attached to PR's?

**Comment by jeffwidman** [comment]
> Our minimal pypi server doesn't support a json interface. Is there another place where we can tell dependabot where to look for the changelogs?

We don't support manually specifying to Dependabot where to look for changelogs... and I don't see us doing that anytime soon, it's not feasible for most use cases.

My guess is the changelogs are exposed in a git repo for the python package... but if there's no JSON interface from the Pypi server, how will Dependabot figure out which repo generates the package? Even if no changelog, it at least needs breadcrumbs to follow. Do you think the `pypiserver` team would be open to exposing the json interface for metadata, ideally one that mimics what Warehouse does? That'd probably be the easiest way to cross-connect everything.

For now I'm going to close, as I just don't think there's anything concrete for us to do here... if the `pypiserver` has an API for us to fetch metadata, then we can definitely explore what else is needed on our side to leverage it.

@chrislujan your issue is unrelated, please open a new issue if you're still experiencing this.
