### ISSUE TITLE
Unrelated changed in Dependabot's PR

### ISSUE THREAD

**Issue by mueller-ma** [dependabot/dependabot-core#3677]
**Package ecosystem**
 gradle
**Package manager version**

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**
https://github.com/openhab/openhab-android/blob/main/.github/dependabot.yml
**Updated dependency**

**What you expected to see, versus what you actually saw**
I expect that Dependabot's PRs only bump versions. I recently removed a repository from my gradle file and now Dependabot includes this change in a recent PR: https://github.com/openhab/openhab-android/pull/2572/files
Also the PR has been opened at 23:03 and not 4:00 as defined in  dependabot.yml (Both timezone "Europe/Berlin")

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jasonrudolph** [comment]
👋 @mueller-ma: Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half-way. 😀

**Comment by mueller-ma** [comment]
@jasonrudolph I updated the issue, please reopen it.

**Comment by jurre** [comment]
I don't think these changes are "included by dependabot", the diff here is just a bit confusing? Since the PR was opened, the main branch has changed, but the diff that is shown is that of the parent commit at the time that dependabot ran.

You can ask dependabot to recreate the commit against the latest main by commenting `@dependabot rebase` on the PR, or you can manually rebase it. When you do that, you'll see the diff as expected:

```bash
openhab-android dependabot/gradle/androidx.constraintlayout-constraintlayout-2.1.0 % g rebase origin/main
First, rewinding head to replay your work on top of it...
Applying: Bump constraintlayout from 2.0.4 to 2.1.0
Using index info to reconstruct a base tree...
M	mobile/build.gradle
Falling back to patching base and 3-way merge...
Auto-merging mobile/build.gradle
openhab-android dependabot/gradle/androidx.constraintlayout-constraintlayout-2.1.0 % git diff origin/main
```

```diff
diff --git a/mobile/build.gradle b/mobile/build.gradle
index 55d7caad..2244cbac 100644
--- a/mobile/build.gradle
+++ b/mobile/build.gradle
@@ -136,7 +136,7 @@ dependencies {
     implementation "androidx.appcompat:appcompat:1.2.0"
     implementation "androidx.legacy:legacy-support-v4:1.0.0"
     implementation "androidx.recyclerview:recyclerview:1.2.1"
-    implementation "androidx.constraintlayout:constraintlayout:2.0.4"
+    implementation "androidx.constraintlayout:constraintlayout:2.1.0"
     implementation "androidx.preference:preference-ktx:1.1.1"
     implementation "androidx.biometric:biometric:1.1.0"
     implementation "com.google.android.material:material:1.4.0"
```

We can also verify this by running dependabot against the original parent:

```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb gradle openhab/openhab-android --dep=androidx.constraintlayout:constraintlayout --commit=50a8fd525319a1db16ee4f7612ac38a9ecba6ff8
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/openhab/openhab-android/
=> parsing dependency files
=> updating 1 dependencies: androidx.constraintlayout:constraintlayout

=== androidx.constraintlayout:constraintlayout (2.0.4)
 => checking for updates 1/1
 => latest available version is 2.1.0
 => latest allowed version is 2.1.0
 => requirements to unlock: own
 => requirements update strategy:
 => updating androidx.constraintlayout:constraintlayout from 2.0.4 to 2.1.0

    ± mobile/build.gradle
    ~~~
    139c139
    <     implementation "androidx.constraintlayout:constraintlayout:2.0.4"
    ---
    >     implementation "androidx.constraintlayout:constraintlayout:2.1.0"
    ~~~
```

But it should also be safe to just merge the PR and the diff will show up like ^

**Comment by mueller-ma** [comment]
Sure, rebasing (manually or done by Dependabot) is a solution for this, but it still shouldn't happen, IMO.
It's not just the diff that's wrong. These changes are part of the commit https://github.com/openhab/openhab-android/commit/42921e817a801330ba835be459cda6770e5c3ec4

**Comment by jeffwidman** [comment]
I happened upon this while looking at something else. Agreed that this shouldn't happen, but when I look at your linked commit (https://github.com/openhab/openhab-android/commit/42921e817a801330ba835be459cda6770e5c3ec4) I see only the dependabot-related changes. So maybe there was a stale cache of some kind on the PR diff? Regardless, the diff looks fixed/fine to me now.
