### ISSUE TITLE
Validator reports false duplicates

### ISSUE THREAD

**Issue by mx-psi** [dependabot/dependabot-core#3684]
**Package ecosystem**: Go modules
**Language version** Go 1.15
**dependabot.yml content**: https://github.com/DataDog/datadog-agent/blob/140a1b7/.github/dependabot.yaml
**What you expected to see, versus what you actually saw**

On May 7th we merged master into the branch for PR Datadog/datadog-agent#7845, for which the Dependabot configuration validator check failed with [1]

> Dependabot encountered the following error when parsing your .github/dependabot.yaml:
> 
```
The property '#/updates/1/ignore/0/dependency-name' is a duplicate.
The property '#/updates/1/ignore/1/dependency-name' is a duplicate.
The property '#/updates/2/ignore/0/dependency-name' is a duplicate.
```
> 
> Please update the config file to conform with Dependabot's specification.

I would expect there to be no error (same way as the PR that last changed our Dependabot PR before that, Datadog/datadog-agent#8036 [2]), since the lines are not duplicates. It seems like the validator considers a duplicate to ignore the same dependency on different Go modules, while it clearly is not (one might want to ignore a dependency on one module but not in another).

**Native package manager behavior** n/a
**Images of the diff or a link to the PR, issue or logs**

[1]: Failed validator run https://github.com/DataDog/datadog-agent/pull/7845/checks?check_run_id=2528979005
[2]: Passing validation run https://github.com/DataDog/datadog-agent/runs/2476679803

**Comment by thepwagner** [comment]
Thanks for the report! I can confirm this bug.

Specifically, it affects configurations with multiple `updates:` configuration: Dependabot is incorrectly considering all `ignore:` conditions globally instead of each `updates:` individually.

In your example, each config is using `package-ecosystem: gomod` and different `directory:` values.
The same issue would affect configs of varying `package-ecosystem:`.

_Only_ the validation check is broken: the job logs should confirm the ignored dependencies are in fact being ignored.

**Comment by markgibaud-vtail** [comment]
Redoing the lockfile worked for us, so for yarn/npm deps: `rm yarn.lock && yarn`
