### ISSUE TITLE
Dependabot doesn't pin to major version anymore with GitHub Actions

### ISSUE THREAD

**Issue by crazy-max** [dependabot/dependabot-core#3704]
Hi,

This morning I have a ton of PRs created by Dependabot although I have pinned to the major version and it does match the latest semver available so I think there's been a recent change in the last few hours that breaks this.

![image](https://user-images.githubusercontent.com/1951866/117931293-4e993480-b2ff-11eb-9604-e49cd11c9ed6.png)

Here is a list of some repos:

* https://github.com/crazy-max/diun/pulls
* https://github.com/crazy-max/goreleaser-xx/pulls

Thanks!

**Comment by akien-mga** [comment]
Confirmed, see e.g. https://github.com/godotengine/godot-docs/pull/4908.

**Comment by aaronfranke** [comment]
Some more examples of undesired/unexpected/incorrect version bumping:  
https://github.com/godotengine/tps-demo/pull/102  
https://github.com/aaronfranke/godot-measuring-tape/pull/1

**Comment by ocean90** [comment]
Maybe related to some changes in #3662? This was [released two days ago](https://github.com/dependabot/dependabot-core/blob/main/CHANGELOG.md#v01454-10-may-2021) though.

**Comment by korelstar** [comment]
A workaround would be to set `version_requirement_updates=widen_ranges`, but according to the documentation, this is not available for GitHub Actions.

**Comment by crazy-max** [comment]
@thepwagner Thanks for the fix! Any ETA? Just want to be sure before closing the PRs thanks!

**Comment by thepwagner** [comment]
@crazy-max in QA now, should be live within a few hours (I'll ping here)

**Comment by ocean90** [comment]
Thanks for the quick fix! Once it’s live, will Dependabot close all the PRs automatically on the next check or do we have to close them manually?

**Comment by thepwagner** [comment]
Sorry for the noise: the fix has been deployed to the GitHub version of Dependabot as `0.146.1-6728db7e2024e6b0ab5ec73b41f9a69b5c30fbf4 (since 2021-05-12 20:27:17 +0000)`

> will Dependabot close all the PRs automatically on the next check or do we have to close them manually

They won't be closed by the next check for any available updates: Dependabot will see no update available and move on.

They will be closed if a rebase of a particular PR is requested, like: https://github.com/dependabot/dependabot-core/pull/3706#issuecomment-840078560 , in that case Dependabot sees the expected update is no longer possible and closes the PR.
One workaround: if you push any change to `.github/workflows/*.yaml`, Dependabot will automatically rebase all open Actions PRs.  That will trigger the "dependency has been removed" case in each PR, and should auto-close. Unfortunately it's limited to a single repository.

**Comment by bewuethr** [comment]
Added to a discussion at https://github.com/github/feedback/discussions/12303
