### ISSUE TITLE
maven - failure to detect vulnerable dependency

### ISSUE THREAD

**Issue by dima-v-v** [dependabot/dependabot-core#3722]
**Package ecosystem:** maven

**Manifest location:**  /morf/pom.xml

I'm testing dependabot security alerts/updates feature. 

I forked the repo, which is maven project with the known issue, created a branch from a buggy commit and made it default:
https://github.com/dima-v-v/morf
The issue is using obsolete version of Primetek Primefaces (v. 5.1) with know vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2017-1000486 (Critical severity).

The dependency and its current version are correctly reported in the repo Dependency Graph but it's not marked as  _known security vulnerability_

![prifaces](https://user-images.githubusercontent.com/41924997/118316093-3fef8080-b4ab-11eb-8282-67a5179b6d6a.png)

**Comment by feelepxyz** [comment]
@dima-v-v thanks for reporting, does indeed look like our advisory db doesn't include this CVE yet: https://github.com/advisories?query=CVE-2017-1000486

I've raised it with the advisory db team.

**Comment by dima-v-v** [comment]
Thanks! The CVE is there (NVD) since 2018 and it's real. I have an app which was exploited this way. I wonder now if there is more NVD CVEs which are not in github advisory database.

**Comment by asciimike** [comment]
@dima-v-v currently we do manual curation of the NVD, which is why some things aren't in our Advisory Database, though we're working on publishing more of them (and soon, all of them). I'm going to close this out now that the team is aware of the issue and will add this vuln, but please let us know if you're seeing any other discrepancies!
