### ISSUE TITLE
[Query] How to label Dependabot Security Alert PRs

### ISSUE THREAD

**Issue by raisonon** [dependabot/dependabot-core#3726]
Dependabot creates two types of pull requests - standard version bumps and security vulnerability bumps.

Is there a way we can add a 'security' label to the latter?

Thanks

**Comment by asciimike** [comment]
Closing as a dupe of https://github.com/dependabot/dependabot-core/issues/2294 which is "add more labels."

I will say that the "security" label is a bit tricky because as of right now, we only show admins that a PR fixes a vuln, while adding a label would be public to all repo viewers. This is mostly an issue on public repos, so there's a thought that we might only add this to private repos to start.

I will also say that if we go down the "actions labeler" path, as discussed in the issue, we will need to provide some sort of signal to the action, which is an open question on our side.

**Comment by raisonon** [comment]
Thanks will check the other issue. For our large org of private repos, your suggestion would be very helpful. Thanks
