### ISSUE TITLE
No alerts  displayed for Maven and Gradle projects

### ISSUE THREAD

**Issue by 123tarunanand** [dependabot/dependabot-core#3838]
While using Dependabot with Maven/Gradle Java projects, the Dependabot Alerts tab does not display  any open alert, despite Dependabot issuing PR's for vulnerable dependencies.

**Comment by asciimike** [comment]
Are you an admin on the repo? Alerts are only shown to repo/org admins.

If you're comfortable sharing the repo name, I can take a look as well.

**Comment by 123tarunanand** [comment]
I've forked these repos. Is it possible for the owner of a forked repo to view these alerts.

The repos that had these issues were forked versions of-
https://github.com/signalapp/Signal-Server 
https://github.com/geosolutions-it/geostore
https://github.com/elastic/elasticsearch

**Comment by asciimike** [comment]
> I've forked these repos. Is it possible for the owner of a forked repo to view these alerts.

Yes, it is possible for the owner of a forked repo to view alerts. If you are not seeing alerts, it is likely because they do not have alerts open.

They also have Dependabot version updates enabled, so that's likely why you're getting PRs. In general, forks shouldn't have Dependabot enabled, but there are cases where this occurs, and you can re-fork the repo to turn it off.
