### ISSUE TITLE
Different compatibility score with two similar PRs

### ISSUE THREAD

**Issue by chenrui333** [dependabot/dependabot-core#3967]
👋  I have just found that even with the similar security patches, the compatibility score shows differently.

Here is color-string 1.5.3 -> 1.5.5 ![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=color-string&package-manager=npm_and_yarn&previous-version=1.5.3&new-version=1.5.5), while here is the color-string 1.5.4 -> 1.5.5 ![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=color-string&package-manager=npm_and_yarn&previous-version=1.5.4&new-version=1.5.5).

Thanks!

**Comment by asciimike** [comment]
I admit that I'm seeing both are the same here--do you maybe have screenshots when they were different?

As for the differences--it's likely because we're [calculating them all individually](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates#about-compatibility-scores), and so a different number of folks are testing/merging them. I wouldn't expect that each update is going to be the same.

Going to close this as WAI, though given a large enough N I'd expect that they should converge to roughly the same value when they're close like that.
