### ISSUE TITLE
schedule is ignored

### ISSUE THREAD

**Issue by eps1lon** [dependabot/dependabot-core#3975]
**Package ecosystem**
npm
**Package manager version**
yarn 1.22.1
**Language version**
node 12
**Manifest location and content prior to update**
./package.json
**dependabot.yml content**
https://github.com/mui-org/material-ui/blob/02d6348a22fe8825f7f3ef0b34c33a74f4fd2ba3/.github/dependabot.yml
**Updated dependency**
Bump next from 10.2.0 to 11.0.1 
**What you expected to see, versus what you actually saw**
No update at this time. The PR was opened on Wednesday when updates are scheduled for Sunday/Monday
**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**
https://github.com/mui-org/material-ui/pull/26904/files
**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by asciimike** [comment]
It looks like the config file was changed around that time, which will trigger an update, [per the docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#frequency-of-dependabot-pull-requests). I'm also seeing a few errors and timeouts, which could have pushed things back a few hours (or a day).

Closing as WAI, but please re-open if you're seeing other behavior that is different than what is described above or in the docs.

**Comment by eps1lon** [comment]
> It looks like the config file was changed around that time

Could you clarify what you mean by "changed"? The contents wasn't changed since we upgraded: https://github.com/mui-org/material-ui/commits/148b0737e2d14c8940a9e08bf27226c984e16323/.github/dependabot.yml

We've been getting upgrades a couple of times over the past few days without ever touching the config..

It's unfortunate that this is yet another instance where the dependabot team closes an issue prematurely.

yarn v2 support dropped, no grouping, no concurrency limit. Now the schedule is no longer respected. We'll be migrating to Renovate. Thanks to all the people that were working on dependabot prior to the GitHub acquisition.

**Comment by asciimike** [comment]
Sorry you feel that way. I'll admit that we're pretty underwater on the issue backlog, so we've been trying to resolve what we think are straightforward issues faster, and sometimes we're on the wrong side of that.

W.r.t. "config file changes", we'll re-trigger an update if the manifest file or the `dependabot.yaml` is updated (since in the former case, potentially a new dependency was added we should try to update, or a problematic one was removed thus we can succeed), or in the latter, there may be a new ecosystem, new ignore conditions, etc.

It looks like `/docs/package.json` has been [updated several times in the past few days](https://github.com/mui-org/material-ui/commits/next/docs/package.json), and one of those I'm seeing is attempting to update next from 10.2 to 11.0 (the above PR). It looks like https://github.com/mui-org/material-ui/commit/7759e3f687caf3852a8f0ed673bfc18d915ea563#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56 is the PR that caused us to kick off the job.

I recognize that this behavior might not be super intuitive: do you have any suggestions for how we might make this more obvious?
