### ISSUE TITLE
Configuration of python version via .python-version conflicts with pyenv

### ISSUE THREAD

**Issue by nsheth** [dependabot/dependabot-core#4062]
As mentioned in the comment here:
https://github.com/dependabot/dependabot-core/issues/2792#issuecomment-737118407

pyenv / pyenv-virtualenv utilize a .python-version for managing python environments when changing directories. This allows for clean segregation of environments across projects.

As per https://github.com/dependabot/dependabot-core/issues/1455, it says we can utilize .python-version to specify a version of Python for dependabot as well.

This usage causes conflicts. Are there alternate mechanisms by which to specify the python version?

**Comment by ilenfant** [comment]
for the other people that may run into this issue, there are several other ways to tell dependabot what python version they want to use one could use one  the following files:
`pipfile` 
> [requires]
> python_version = "x.x.x"

`pyproject.toml`
> [tool.poetry.dependencies]
> python = "x.x.x"

`.python-version`
> x.x.x

`runtime.txt`
> python-x.x.x

`setup.py`
> python_requires = "x.x.x"

I didn't test all of them but that's what seems to come from the reading of https://github.com/dependabot/dependabot-core/blob/00f0e52b630af6d55318951e8cb21a9a32eabbb7/python%2Flib%2Fdependabot%2Fpython%2Ffile_parser%2Fpython_requirement_parser.rb

**Comment by ssbarnea** [comment]
I guess using `runtime.txt` is the way to go as the other files will have undesired side-effects or not even be available for use.

Which minor versions would be available is another question we may need an answer for, especially as there is no joy to merge stuff an hope dependabot will not choke not knowing about a value like `python-3.6.16` or no longer having an older value like `python-3.6.0`.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

I'm unclear what specifically this issue is asking for. Yes, if you specify a `.python-version`, Dependabot will try to honor it when picking which python interpreter to use. For most projects, they want that to happen.

Are you saying your want to configure Dependabot to use a specific version of python, and not the one specified in your `.python-version` file? If so, can you explain your use case more? Ie, why you want this?

**Comment by jeffwidman** [comment]
Related:
* https://github.com/dependabot/dependabot-core/issues/1812

**Comment by deivid-rodriguez** [comment]
I'm also unclear about what this issue is requesting. I'm going to close since I believe it may have been due to some older problem now fixed, and because other options for configuring the Python version have been provided in case `.python-version` is not a good fit for some reason.

But if there's something we are missing, please comment and we can reopen!

**Comment by mikehow1984** [comment]
I have a similar issue. I think me and the OP want the same thing. 

For me, I have an Ansible folder in my repo, that has a `.python-version` file to be used specifically for Ansible setup on Python version 3.7. When I try to have Dependabot update dependencies in my repo, Dependabot picks up the Ansilble `.python-version` file (that isn't intended for Dependabot setup) and throws the following error:

```updater | 2023/09/05 17:04:01 ERROR <job_718313234> Error during file fetching; aborting
updater | 2023/09/05 17:04:01 ERROR <job_718313234> Dependabot detected the following Python requirement for your project: '3.7.7'.
updater | 
updater | Currently, the following Python versions are supported in Dependabot: 3.11.*, 3.10.*, 3.9.*, 3.8.*.```

I would like Dependabot to be able to ignore this `.python-version` file as it's not intended for Dependabot.
