### ISSUE TITLE
PR description Release Notes missing some versions from GitHub releases

### ISSUE THREAD

**Issue by edmorley** [dependabot/dependabot-core#4107]
**Package ecosystem**
Rust / Cargo

**Package manager version**
N/A

**Language version**
N/A

**Manifest location and content prior to update**
`/Cargo.toml`: https://github.com/Malax/libcnb.rs/blob/917a1cb085ae7fcce6869dacb3254add001f9354/Cargo.toml

**dependabot.yml content**
https://github.com/Malax/libcnb.rs/blob/917a1cb085ae7fcce6869dacb3254add001f9354/.github/dependabot.yml

**Updated dependency**
`semver` from `^0.11.0` to `^1.0.4`

**What you expected to see, versus what you actually saw**

### Expected:
The "Release notes" section of the PR description to include references/content from all GitHub releases between v0.11.0 and 1.0.4. ie:
https://github.com/dtolnay/semver/releases/tag/1.0.4
https://github.com/dtolnay/semver/releases/tag/1.0.3
https://github.com/dtolnay/semver/releases/tag/1.0.2
https://github.com/dtolnay/semver/releases/tag/1.0.1
https://github.com/dtolnay/semver/releases/tag/1.0.0

### Actual:
The "Release notes" section of the PR description only referenced the most recent GitHub release:
https://github.com/dtolnay/semver/releases/tag/1.0.4

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**
https://github.com/Malax/libcnb.rs/pull/39

**Comment by jurre** [comment]
Thanks @edmorley, the way this currently works is we try to fetch all the releases since the previous versions releases, however, there doesn't seem to be a release for `0.11.0`, and so dependabot falls back to showing the latest release.

The releases I could find for this project:

```
gh api repos/dtolnay/semver/releases | jq .[].tag_name
"1.0.4"
"1.0.3"
"1.0.2"
"1.0.1"
"1.0.0"
```

The relavant code in dependabot: https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/common/lib/dependabot/metadata_finders/base/release_finder.rb#L204-L223

I'm not sure of a good way to fix this edgecase, but I think it should work as expected when there is a release for the previous version?

**Comment by edmorley** [comment]
@jurre Thank you for the quick reply :-)

Ah true - there is not a GitHub release for 0.11.0, although there is a Git tag for that release.

I had thought it would look at both proper releases and Git tags, given both show up at:
https://github.com/dtolnay/semver/releases

...however it makes sense why they might not.

**Comment by jurre** [comment]
Yeah, it gets a little tricky with tags as it's hard to determine which ones are an actual release, and version naming varies across repo's so determining order is not straight forward.

I'm going to close this out for now because I don't think there's much we can do in this case, but please feel free to follow-up if you have any thoughts.

PS: Appreciate the clearly written report, made it really easy to figure out what was happening!
