### ISSUE TITLE
Should not generate alerts on deleted manifest files

### ISSUE THREAD

**Issue by ekevoo** [dependabot/dependabot-core#4129]
**Package ecosystem**
Python

**Package manager version**
Pipenv

**Manifest location and content prior to update**
DELETED a long time ago.

**dependabot.yml content**
Does not exist.

**What you expected to see, versus what you actually saw**
No alerts on deleted manifest files
versus this: 
![Screen Shot 2021-08-10 at 13 33 25](https://user-images.githubusercontent.com/871714/128907403-e9c1361a-3e10-42d6-8a33-eae7fa2b2dbf.png)

**Images of the diff or a link to the PR, issue or logs**
If you go to [the project page](https://github.com/ekevoo/cuckoo) you'll see Pipfile.lock has been deleted; in fact there is no longer any Python file at all. This is not the first time Dependabot harasses my projects on deleted Pipfiles.

**🕹 Bonus points: Smallest manifest that reproduces the issue**
A deleted manifest.

**Comment by Rick-Anderson** [comment]
This is not python specific. Many other file types generate this warning on files deleted years ago. The files are still in the history of the repo even though they are not in any of the active branches. Seems like a bug.

**Comment by jurre** [comment]
This issue seems to be with Dependabot Alerts, which (admittedly confusingly) isn't powered by dependabot-core, Alerts have their own implementation of manifest detection and scanning.

I know the team that works on the Dependency Graph / Dependabot Alerts have made some improvements in this area, and I've also made sure the team is aware of this issue, but in order for our team to try and get a handle on our issue backlog I'm going to close this out.

**Comment by ekevoo** [comment]
@jurre Can you please direct me to the correct place to report this bug? I have just received a similar false alert just last week. It was a bit less frustrating because they finally added a "dismiss because this alert is false" option to the menu but I would rather have a channel where I can actually describe the problem.

**Comment by Rick-Anderson** [comment]
@jurre writes > but in order for our team to try and get a handle on our issue backlog I'm going to close this out.

Is there a bug we can monitor for progress. We get alters once a week for files that were deleted 3 years ago. After getting 35 false alarms in a row, it's time to stop using the alert system.

**Comment by Rick-Anderson** [comment]
@jurre is there an option to disable scanning history? The insure files only exist in the history, not in any branch.

**Comment by juxtin** [comment]
👋🏽 from the Dependency Graph team! Sorry for any frustration this has caused.

This is indeed an issue on our side. Unfortunately our view of which manifests are currently in the repository can drift out of sync with reality from time to time. It's a known issue, or rather a known class of issues, that we're steadily working on fixing.

In this case it looks like the old manifest has been cleared out already, so that's good. If this happens again in the future, the fastest way to fix it is probably to contact support—they have the tools to clear and redetect the manifest files.

**Comment by ekevoo** [comment]
Thanks that's good to hear.

**Comment by jeffwidman** [comment]
Thanks @juxtin ! 

Closing, as there's really nothing more we (the dependabot updates team) can do here.
