### ISSUE TITLE
Dependabot keeps posting PRs in forked repo with Dependabot disabled in settings

### ISSUE THREAD

**Issue by Karlson2k** [dependabot/dependabot-core#4167]
I have a public repo: https://github.com/Karlson2k/Flexget
The repo is forked from another public repo.
As I got from [documentation](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates#supported-repositories), Dependabot shouldn't scan this repo because it's fork, however I have constant flow of new PRs from Dependabot.

I disabled all Dependabot alerts in [repo settings](https://github.com/Karlson2k/Flexget/settings/security_analysis): 
![image](https://user-images.githubusercontent.com/1898693/130659093-4597058d-2708-478b-a4f0-d28f69956567.png)
but I still have new PRs.

I also tried to disable Dependabot [globally](https://github.com/settings/security_analysis) for my account, but it didn't help either.

I think Dependabot should not post new PRs on this repo and it looks like a bug.

**Comment by jeffwidman** [comment]
Duplicate of https://github.com/dependabot/dependabot-core/issues/2804, which we recently fixed.

However, since this fork was opted in before we shipped the change, you'll need to manually disable it. See https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1326137957 for the gory details.
