### ISSUE TITLE
Detect Git submodules accessed over `git:` or `http:`

### ISSUE THREAD

**Issue by Marcono1234** [dependabot/dependabot-core#4196]
## Background
When Git submodules specify a `git:` or `http:` (unencrypted HTTP) URL, the submodule seems to be cloned without any integrity protection. This makes a project vulnerable to man-in-the-middle attacks which could provide malicious code for a submodule.

Unfortunately usage of `git:` and `http:` protocol still seems to be widespread; most likely because users committed the submodule configuration a long time ago (when HTTPS usage was not that common), and are now not aware of the issue.
- [GitHub search `git:`](https://github.com/search?q=%22url%3Dgit%3A%22+filename%3A.gitmodules&type=code)
- [GitHub search `http:`](https://github.com/search?q=%22url%3Dhttp%3A%22+filename%3A.gitmodules&type=code)

## Feature request
Dependabot should detect and warn about usage of `git:` and `http:` URLs for submodules, and possibly also suggest replacing them with `https:`.

**Comment by jeffwidman** [comment]
Interesting idea. We don't have a great mechanism today to warn users about this kind of thing, but this could potentially fit under the same bucket as a deprecated package.

However, there's a number of valid use cases for using `git` / `http` protocols, such as when running Dependabot behind a firewall where for some companies the complexity of managing https certs isn't worth the security benefit. In that case, we'd have to no only warn, but also provide a way to dismiss the warning.

This actually feels more like a CodeQL code scanning feature and not a Dependabot version updates feature:
* https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning
* https://codeql.github.com/

Because they've got a built-in pipeline for generating warnings / alerts and then letting users triage / close them.

So I'm going to pass the idea along to the CodeQL team and then close this.

**Comment by Marcono1234** [comment]
Fair point! Though I am afraid that this won't be added to CodeQL because CodeQL is mainly about code scanning and not related to Git. In fact they did extract Git information in the past but removed that support ([except for Python](https://github.com/github/codeql/blob/3c7f7511be7453e4d26399f0f66ecc0d4c0e6c96/python/ql/src/external/VCS.qll)?, not sure if that is still functional), see for example the [C# analysis changelog](https://github.com/github/codeql/blob/3c7f7511be7453e4d26399f0f66ecc0d4c0e6c96/change-notes/1.22/analysis-csharp.md?plain=1#L15-L34). And even if they added back support for it, I assume it would only be part of the programming language specific extractors and there wouldn't be a Git specific extractor which can be run on its own. So the number of repositories which could use CodeQL to detect this (and which also want to set up CodeQL) would be smaller than the number of repositories which have Dependabot enabled.

When I wrote this issue I mainly had projects on github.com in mind where the case you described of "running Dependabot behind a firewall" would not be the case.

Due you think it would be possible to add support for Git submodules as optional check which is enabled on github.com by default but not when running Dependabot elsewhere (if you really think this would cause too many false positives)?

**Comment by Marcono1234** [comment]
> So I'm going to pass the idea along to the CodeQL team and then close this.

Do you know what happened to this idea and what they thought about it?
