### ISSUE TITLE
Missing  ext-pcov 

### ISSUE THREAD

**Issue by oleg-andreyev** [dependabot/dependabot-core#4202]
**Package ecosystem**
composer
**Package manager version**
composer 2.x
**Language version**
PHP 7.3
**Manifest location and content prior to update**
```json
{"require": {
    "php": "^7.3",
    "ext-pdo": "*",
    "ext-curl": "*",
    "ext-iconv": "*",
    "ext-json": "*",
    "ext-zlib": "*",
    "doctrine/common": "~2.7",
    "google/apiclient": "^2.0",
    "jms/serializer-bundle": "~0.13|~1.1|^2.0|^3.7",
    "symfony/console": "^2.8|^3.4|^4.4|^5.1",
    "symfony/dependency-injection": "^2.7|^3.4|^4.0|^5.1",
    "symfony/monolog-bundle": "^2.11|^3.1",
    "symfony/stopwatch": "^2.6|^3.4|^4.4|^5.1",
    "twig/twig": "1.42.3|^2.4",
    "webmozart/assert": "~1.8.0"
  },
  "require-dev": {
    "ext-pcov": "*",
    "infection/infection": "^0.18.0",
    "doctrine/orm": "^2.7",
    "phpmd/phpmd": "^2.10",
    "phpmetrics/phpmetrics": "^2.7",
    "phpunit/phpunit": "^9.2",
    "psalm/phar": "~4.1.0",
    "qossmic/deptrac-shim": "^0.11.1",
    "symfony/framework-bundle": "^5.1",
    "symfony/dotenv": "^5.1",
    "symfony/event-dispatcher": "^5.1",
    "symfony/yaml": "^5.1",
    "symfony/proxy-manager-bridge": "^5.1",
    "sensiolabs-de/deptrac-shim": "^0.10"
  },}
```

**Updated dependency**

```
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires PHP extension ext-pcov * but it is missing from your system. Install or enable PHP's pcov extension.

To enable extensions, verify that they are enabled in your .ini files}
```

**Native package manager behavior**
-

**Images of the diff or a link to the PR, issue or logs**
-

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by oleg-andreyev** [comment]
Hi 👋 

I don't remember, but based on Dockerfile, yes, it's still is required.

**Comment by jeffwidman** [comment]
Thanks, I understand the issue now.

We chatted about this internally, and for now we're not going to add a custom extensions for a language ecosystem to the base docker image unless it's super popular. As far as I'm aware this one isn't, since this issue hasn't attracted any additional 👍 .

That said, you can easily workaround this by running Dependabot yourself as a custom GitHub action. Take our base docker image and then add your needed dependency as an additional layer. I thought we had an example repo showing how to do this, but I'm not finding it now... you can always use https://github.com/dependabot/dependabot-script/ as an entrypoint.
