### ISSUE TITLE
Case insensitivity for package names generated wrong security alert

### ISSUE THREAD

**Issue by LizelleJ** [dependabot/dependabot-core#4204]
**Package ecosystem**
npm
**Updated dependency**
The file states _JSON_, while the dependency that Dependabot reported to be updated is _json_.
**What you expected to see, versus what you actually saw**
The package being used in the package.json file was _JSON_, for which available updates were expected to be seen; however, a security advisory was given for the _json_ package instead, asking to update to _json 10.0.0_. The observation was that it was due to case insensitivity from the Dependabot side.

Specifically, the file contained this:
"JSON": "^1.0.0"

But some of the links reported for the dependency's vulnerability was:
- https://nvd.nist.gov/vuln/detail/CVE-2020-7712
- https://github.com/advisories/GHSA-3c6g-pvg8-gqw2 

The dependencies:
- json: https://www.npmjs.com/package/json
- JSON: https://www.npmjs.com/package/JSON

**Comment by jurre** [comment]
I'm assuming this is only an alert you received, or did we attempt to update the JSON package to `10.0.0` in a pull request? The reason I'm asking is the alerting system is separate from dependabot-core so I can route it to the right team in that case. If it was a PR, lmk and I can take a look! 🙇

**Comment by LizelleJ** [comment]
Hi there, yes it was for an alert received and not a PR.

Thank you

**Comment by jeffwidman** [comment]
@LizelleJ thanks for clarifying. As @jurre mentioned, the code to generate alerts is a different service owned by a different team.

I've reported it to them and after a quick look they think they spotted at least one thing they need to fix... they're tracking it internally, so I'm going to close this since there's nothing more we can do on the `dependabot-core` side.
