### ISSUE TITLE
No way to disable dependabot on public repo

### ISSUE THREAD

**Issue by diamondap** [dependabot/dependabot-core#4244]
We have disabled dependabot alerts and security updates on our public repo. See the attached screenshot. As pointed out in bug https://github.com/dependabot/dependabot-core/issues/2097, those settings don't actually work. 

![Screen Shot 2021-09-20 at 9 30 03 AM](https://user-images.githubusercontent.com/225514/134011860-3b424e72-78ef-4824-bb4f-ed11c9693ecf.png)

We have also set open-pull-requests-limit to zero our dependabot.yml file, as documented here: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit. 

That does not stop dependabot.

We have also set ignore depenency-name to * in the yaml file, as documented at https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore

That does not stop dependabot either.

So how do we keep dependabot out of our repo?

![Screen Shot 2021-09-20 at 9 30 57 AM](https://user-images.githubusercontent.com/225514/134011980-6d20a809-f40a-4ed0-b525-79b429361114.png)

**Comment by jurre** [comment]
@diamondap you'll want to completely remove that config file, the `open-pull-request-limit` applies to periodic version updates only, it does not set a limit for security updates.

I am a little confused by your screenshots though, is this the `APTrust/dart` repo you're referring to? Because it looks like its [config file](https://github.com/APTrust/dart/blob/master/.github/dependabot.yml#L9) is configured to allow for 10 version updates.

Lmk if removing the config file resolves the issue though.

**Comment by diamondap** [comment]
Well that may be the problem. I didn't know that other config file existed. I will delete the config file I pointed to and will adjust the settings in .github/dependabot.yml. Thanks for your help. I'll get back to you and let you know if that works.

**Comment by jurre** [comment]
Ah, yeah it needs to be in that exact location or dependabot cannot pick up the config file. It looks good now though so I think this should resolve it 🤞

**Comment by diamondap** [comment]
OK, it looks like this worked. Thanks for the help.
