### ISSUE TITLE
Support for NuGet ManagePackageVersionsCentrally

### ISSUE THREAD

**Issue by dorssel** [dependabot/dependabot-core#4261]
NuGet has a new way of centralized package versions:
https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions
Sure, this is still in preview, but the interface and functionality have been stable for more than a year and several projects already use it.

The function is quite similar to:
https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions
This is already supported by dependabot since https://github.com/dependabot/dependabot-core/pull/1311

In fact, the two are so similar that the support could possibly be integrated. Instead of parsing `Packages.props` also parsing `Directory.Packages.props` could already be sufficient.

**Comment by dorssel** [comment]
Currently, GitHub's native Dependabot *does* check `Directory.Packages.props` (and `global.json`, etc.). This may have been implemented by now, in which case this issue can be closed. I don't know if `dependabot-core` and GitHub's version are in sync...

GitHub still does not display the right version in the Dependency Graph, but that issue has nothing to do with dependabot and has been reported to GitHub.

**Comment by jurre** [comment]
Yeah they're mostly in sync, sometimes the version deployed to GitHub lags behind a little, but all development on dependabot-core happens here 👍. I should note that dependabot-core only powers dependabot _updates_ and not alerts or the dependency graph.

I believe this was implemented by https://github.com/dependabot/dependabot-core/pull/1880 and later fixed by https://github.com/dependabot/dependabot-core/pull/2309.

Those PRs seem to pre-date this issue, so not sure what happened tbh 😄 I think we should be ok to close this out though.
