### ISSUE TITLE
Dependabot to update reusable github-actions workflow

### ISSUE THREAD

**Issue by fizyk** [dependabot/dependabot-core#4327]
Hello,

I'd love for dependabot to also update reusable github actions.

I've got a repository with reusable actions created and started adding these to my repositories. I do pin them by semantic-version tag (v1.0.0, v1.1.0) and it would be really great if dependabot apart from custom actions could also update references to reusable actions.

**Comment by jorsmatthys** [comment]
For us this would be a huge feature. 
Our enterprise is migrating everything to GitHub and Azure, and for provisioning - and interacting with cloud infrastructure our developers do nearly _everything_ with reusable workflows. Nearly every repository that we created in GitHub enterprise has reusable workflows. We have a fairly large development community (100+), and we notice that now that now that every team has started migrating (some recently, some a year ago) their applications to the cloud, it is becoming very hard to keep workflow versions aligned / up-to-date. 

Since private actions are already supported, is this something that sits on the top of your backlog ? :)

**Comment by ali-kafel** [comment]
I'm bumping this as well, it would huge for our firm.

**Comment by jeffwidman** [comment]
Please don't bump via comment as that spams everyone else subscribed for actual updates, a "thumbs up" on the top post is the better way to indicate interest. Or submit a PR--this is open source, and we merge community contributions all the time.

**Comment by lorengordon** [comment]
@jeffwidman Can you help point us where in the code someone might start to implement this, so contributors can get an idea whether this is something they'd be able to contribute?

**Comment by deivid-rodriguez** [comment]
@lorengordon I think a good starting point would be to implement this method:

https://github.com/dependabot/dependabot-core/blob/3846a60c18074d6b52f6d05c33a554e6a1b6ff31/github_actions/lib/dependabot/github_actions/file_fetcher.rb#L69-L72

That way we'll actually fetch the files that we'll need to update.

**Comment by lorengordon** [comment]
@deivid-rodriguez Thanks! Our team has contributed to Dependabot before, we'll take a look and see if we can figure this out...

**Comment by lorengordon** [comment]
@deivid-rodriguez @jeffwidman Alright, PR opened! https://github.com/dependabot/dependabot-core/pull/6660

**Comment by ssbarnea** [comment]
While this is closed as fix, one major issue was missed, making dependabot able to update action version inside reusable actions themselves. Now it only works for the `.github/workflows` folder and not the `.github/actions` one. See https://github.com/dependabot/dependabot-core/issues/6345
