### ISSUE TITLE
Support Conda as a dependabot ecosystem

### ISSUE THREAD

**Issue by adamsuk** [dependabot/dependabot-core#4369]
It'd be great to allow the support of conda environment yaml files similar to the `requirement.txt` support for pip.

There are a few tickets I've found for this but each points me to the `new-ecosystem` projects and I can't see an open ticket for this issue.

Previous tickets:
https://github.com/dependabot/dependabot-core/issues/1249
https://github.com/dependabot/dependabot-core/issues/2227

**Comment by brrygrdn** [comment]
Thanks for opening this issue @adamsuk, I'm going to close this out in favour of https://github.com/dependabot/dependabot-core/issues/2227 as that's the issue we are tracking for Conda support in general.

Apologies for the lack of movement on this, as discussed in our [Contributing](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems) guidelines we've paused on accepting new ecosystems in the last year to focus on some other priorities.

We are hopeful to start addressing extensibility in the new year in order to make it easier to add and support more ecosystems.

**Comment by adamsuk** [comment]
@brrygrdn thanks for taking the time to reply. I wasn't sure if the other tickets were still active but that makes sense to me. Can't wait to give it a whirl when it's available!
