### ISSUE TITLE
Cannot run dependabot due to missing <module> pom.xml

### ISSUE THREAD

**Issue by kristofdho** [dependabot/dependabot-core#4420]
**Package ecosystem**
maven

**Package manager version**
3.6.3

**Language version**
n/a

**Manifest location and content prior to update**
n/a

**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
```

**Updated dependency**
n/a

**What you expected to see, versus what you actually saw**

The root pom that dependabot is running on contains modules like
```xml
<modules>
    <module>../module1</module>
    <module>../module2</module>
    <module>module3</module>
    <module>module4</module>
</modules>
```

Where `module1` and `module2` are hosted in a different repository which has to be checked out next to the repository containing this. The multi repo structure cannot be changed due to legacy reasons, but the root pom contains all the version management in `<dependencyManagement>` so ideally the missing poms would just be ignored, and the dependencyManagement is updated.

What happens now is this error in `Insights > Dependency Graph > Dependabot`:
![image](https://user-images.githubusercontent.com/43339887/142024499-b8e59ac2-3c0f-43ba-bd12-28c962ea66e8.png)
 
There are a couple ways I can think of that would allow this to work:
* allow ignoring individual submodules
* allow ignoring the encountered exception, where it would just silently skip the missing pom instead of hard crashing

**Native package manager behavior**
n/a

**Images of the diff or a link to the PR, issue or logs**
n/a

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment]
👋 sorry for the slow response.

Since the path to the other repository is a local path, there's no way for Dependabot / the underlying package manager tooling to realize it needs to traverse to another repository.

However, the way ignores works is typically as a post-fetch filter. Dependabot is the glue code that looks for the manifest and hands it off to the native package manager. Today for the maven ecosystem, we re-implement Maven logic in Ruby, but poorly. So technically we could support this use case. But our long term product vision is to move toward having the manifest parsing / version checking handled by the native package manager, and then Dependabot as the glue code will handle turning those updates into PRs.

The problem with doing a pre-fetch filter is that most package managers require knowing all the manifests in order to calculate the version constraints. Even for those that accept a list of "ignored" versions, they're still going to typically traverse the full dep tree in order to know what can / cannot be safely bumped.

So I'm afraid I have to close this as wontfix. Down the road, if/when we transition from our Ruby code to actually calling Maven then you could file an upstream ticket with Maven to support this use case.
