### ISSUE TITLE
Update Cargo to version 1.57

### ISSUE THREAD

**Issue by tomaka** [dependabot/dependabot-core#4574]
Hi :wave: 

Cargo version 1.57, released December 2nd, added support for named profiles:
https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#cargo-support-for-custom-profiles

At the moment, dependabot fails to parse any `Cargo.toml` file that uses this feature. [Example](https://github.com/paritytech/smoldot/network/updates/249725019).

It would be great if you could update Cargo to version 1.57 :pray:

**Comment by jurre** [comment]
Yep, I'll open a PR, but it probably won't land in production until after the weekend, trying to keep changes to a bare minimum in this quieter period.

**Comment by bkchr** [comment]
Hey @jurre any update on this?

**Comment by jurre** [comment]
I'd opened and merged a PR that did this, but due to an issue with CI we missed that the update breaks some things, after which I had some time off so I kind of missed following up on this tbh, thanks for reminding me.

I've reverted the revert commit here https://github.com/dependabot/dependabot-core/pull/4677, so let's see if we can resolve the failures.

**Comment by bkchr** [comment]
Ahh okay, ty :)

**Comment by martinohmann** [comment]
I think this issue can be closed since it seems that dependabot uses cargo 1.58 now (released in January). As of writing, the latest rust release is 1.59 (released end of February).

Dependabot failed on me using 1.59 features (`strip`) because it's still on 1.58. I removed this feature from my build pipeline for now to keep dependabot working (until it's at 1.59+ eventually).

I'm wondering if there's a way to instruct dependabot to use a specific rust toolchain when it visits a repository. E.g. if a repo has a `rust-toolchain.toml`, use whatever rust version is set in there. That would be a great benefit I think :)

**Comment by jurre** [comment]
Bumping it to 1.59.0 here: https://github.com/dependabot/dependabot-core/pull/4921 going to close this for now
