### ISSUE TITLE
Dependabot created a PR branch based on an outdated commit

### ISSUE THREAD

**Issue by tonisostrat** [dependabot/dependabot-core#4603]
**Package ecosystem**
npm

**Package manager version**
N/A

**Language version**
N/A

**Manifest location and content prior to update**
N/A

**dependabot.yml content**
N/A

**Updated dependency**
N/A

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**
N/A

**🕹 Bonus points: Smallest manifest that reproduces the issue**
N/A

We have `dependabot` set up in our project with a 3 PR limit. Yesterday at **2:16PM** I merged a feature branch into our `master`. After that another developer in our team committed straight to `master` at **2:43PM**. Then I resolved two `dependabot`-created PRs at **2:47PM** and **3:05PM**. **At 3:06PM**, as there were less than 3 open PRs `dependabot` created a new PR (and branch) BUT the branch was created from `master` based on the commit I made at **2:16PM**, completely ignoring the 3 subsequent commits.

**Comment by hfhbd** [comment]
See also #4031

**Comment by jeffwidman** [comment]
👋 sorry for the slow reply.

We had some racy logic in our internal service that we _think_ we've squashed: https://github.com/dependabot/dependabot-core/issues/5234#issuecomment-1283984313

Since we haven't had further reports of it, I'm going to close, but if for some reason you're still seeing this please file a new ticket. You'll need to include more information though then was included ☝️, ideally an open source repo that we can debug against, but at the very least job logs. If it's a private repo, the easiest is actually to open a support ticket as that makes it easier for us to request the necessary access to your private repo in order to further debug it.
