### ISSUE TITLE
Better Support for GitHub Protected Branches

### ISSUE THREAD

**Issue by coreyja** [dependabot/dependabot-core#461]
I love the new auto-merging feature, but I wish it could be a little more aware of the GitHub protected branch settings I have in place in my repositories. The two relevant settings that I use are:

- `Require status checks to pass before merging`
- `Require branches to be up to date before merging`

Dependabot is aware of the CI status so it doesn't have any problems with the first one! But it kinda has issues with the second one. Here is what I think currently happens.

When there are multiple PR's with Green Status checks it merges the first one successfully. But then due to the second required status check the rest need to me merged(/rebased). Currently Dependabot will simply attempt to merge the second one, and then fail due to the status check. This also has the side-effect of disabling auto merging for the repo.

The rebasing does kick in later however and all the PR's are updated to be up to date

**Comment by greysteil** [comment]
Thanks for the feedback Corey. We can definitely do better than this - I’ll take a look tomorrow morning 🙂

**Comment by greysteil** [comment]
I've just pushed a fix for this - basically, Dependabot's merge logic wasn't handling the case where GitHub tells it that a PR is "mergeable" but "behind", which is what happens when a branch is requires PRs to be up to date before merging. It does now.

Corey - looking through the PRs that had an "automerge failed" comment on your repo, I've manually set your automerge preferences for that repo for "minor" for dev dependencies and "patch" for runtime dependencies. If I got that wrong (the runtime dependencies might have been "minor", I couldn't tell so chose the more conservative option) then you can update it in your settings as normal.

Thanks masses for the feedback on this one, and sorry for the inconvenience.

**Comment by greysteil** [comment]
And FYI, you were exactly right on the diagnosis of the problem!

**Comment by coreyja** [comment]
Wow! Thanks for getting to this so fast that's awesome!

I'll double check my settings, thanks for the heads up!
