### ISSUE TITLE
Support vendoring for JS (specifically yarn-offline-mirror)

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#462]
Yarn has an option (specified in the `.yarnrc`) to create an offline mirror, that will allow offline installs:

```
yarn-offline-mirror "./npm-packages-offline-cache"
yarn-offline-mirror-pruning true
```

This is essentially vendoring, and it would be nice for Dependabot to support it.

See https://github.com/dependabot/feedback/issues/7 for original issue.

**Comment by nuc** [comment]
Oh nooo....

**Comment by henhal** [comment]
:+1: 
Dependabot is really cool, but when every PR it creates in our repos fails CI because it only updates `package.json` and `yarn.lock` and NOT our `yarn-offline-mirror`, its use is fairly limited for us. Our CI (as well as our docker containers) uses `yarn install --offline --frozen-lockfile --link-duplicates`.
So if dependabot could understand from .yarnrc that the offline mirror is used and add also the files in `./yarn-offline-mirror`, it would be awesome.

**Comment by vmo-mgosling** [comment]
almost 3 years now...
i tried using a workflow to update the offline mirror but then dependabot sees the PR as edited by someone else (despite it being the author of the commit)

**Comment by davidsbond** [comment]
The golang support was updated to include vendoring not too long ago: https://github.com/dependabot/dependabot-core/issues/670, feels like the npm support should be next.

**Comment by jeffwidman** [comment]
We shipped Yarn Berry support including support for the “zero install” feature which relies on this offline cache. Since this is resolved for yarn berry, I'm going to close for now.

However, I am unclear what yarn 1 did in this regard, so if you're still blocked on this for some reason, please comment explaining the situation and what is missing and we can re-open.
