### ISSUE TITLE
Dependabut doesn't ignore major version when using nuget ( Azure Devops)

### ISSUE THREAD

**Issue by NicoJuicy** [dependabot/dependabot-core#4628]
**Package ecosystem**
Nuget

**Package manager version**
Latest on Azure Devops

**Language version**
c#

**Manifest location and content prior to update**
**Updated dependency**
Bump Microsoft.EntityFrameworkCore from 5.0.0 to 6.0.1

**What you expected to see, versus what you actually saw**
I expected to see the latest nuget of Microsoft.EntityFrameworkCore with 5.x.x. Which is 5.0.13 
[Link to available package versions](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore)

**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/445937/149150698-f7745b71-6dd9-43f7-b998-26518e2d1e97.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

[Test project on Azure Devops](https://dev.azure.com/nsap0038/_git/Dependabot-Test)
- [Dependabot pipeline file](azure-pipelines-dependabot-v2.yml)
- [Dependabot config](https://dev.azure.com/nsap0038/_git/Dependabot-Test?path=/.dependabot/config.yml)

Note: Configure PAT as a variable in Azure Devops ( Personal Access Token)

**Comment by jurre** [comment]
Hey, it looks like you're running dependabot-script, it doesn't support anything the the config file, if you want to pass in an ignored version, you'll have to pass it into the `UpdateChecker` manually as an [`IgnoreCondition`](https://github.com/dependabot/dependabot-core/blob/2d99d7d1e5b8db830e070e09fe14cab5f6fc62a9/common/lib/dependabot/config/ignore_condition.rb) object, the argument on the `UpdateChecker` is [`ignored_versions`](https://github.com/dependabot/dependabot-core/blob/2d99d7d1e5b8db830e070e09fe14cab5f6fc62a9/common/lib/dependabot/update_checkers/base.rb#L25).

You'll have to modify the script in order to be able to do this.

**Comment by craigta** [comment]
UpdateChecker doesn't take IgnoreCondition object, it only takes ignored_versions object -- which means that there isn't a ready way that I found so far to skip major/minor versions. I saw config has this, but new to Ruby and trying to figure out how to get it to skip major/minor still. Any ideas?

**Comment by craigta** [comment]
Also tagging @NicoJuicy to see if you found some way to do something like this

**Comment by NicoJuicy** [comment]
@craigta This was an innovation project at my company. I currently decided to not continue this for Azure Devops until it get's easier.

Since Microsoft bought Github and Github bought dependabot, it doesn't seem an unrealistic predicition.
