### ISSUE TITLE
Slack support

### ISSUE THREAD

**Issue by Masadow** [dependabot/dependabot-core#4642]
I'd like to reopen #2245.

Answer says Github slack integration is the way to go but it does not work because dependabot applies labels after the creation of the PR. Github slack integration only works properly if the label is set at the PR creation.

Not being able to filter pull requests created by dependabot makes the integration totally useless. A reliable solution would be greatly appreciated 🙏

**Comment by www-imotoneigesled-net** [comment]
Its possible tu help me for this? Please...

Le mar. 18 janv. 2022 1 h 16 p.m., Jimmy Delas ***@***.***> a
écrit :

**Comment by mwaddell** [comment]
You should be able to solve this issue using a custom workflow that is triggered by the [label create](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#label) event and uses [slack-action](https://github.com/marketplace/actions/slack-action) to send your notification(s).

**Comment by glemvik** [comment]
> Not being able to filter pull requests created by dependabot makes the integration totally useless. A reliable solution would be greatly appreciated 🙏

Agreed! Filtering pull requests created by dependabot is our main motivation for using this integration. We really hope that this feature request is accepted! 🤞

**Comment by benatdelta** [comment]
Our team is also still wanting this

**Comment by jeffwidman** [comment]
This isn't just a Dependabot limitation. 

The root problem is that [the PR creation API doesn't currently support including labels during create](https://stackoverflow.com/questions/68459601/can-we-add-labels-to-a-pull-request-while-creation-using-rest-api). Interestingly, the Issue create API _does_ allow setting a label at creation time. 

So until that changes, _any_ bot that creates PR's, not just Dependabot, will have the same problem.

**Comment by mwaddell** [comment]
Isn't this issue really a limitation with the Github+Slack integration rather than with Dependabot?  This could be accomplished now if the Github+Slack integration allowed you to subscribe to PRs upon the label-add action (instead of only on initial creation) or to subscribe to PRs based on their author (I don't believe either of these are supported).  This would also make that integration more flexible (for example, I want to be notified any time someone adds the "critical" label to a PR regardless of whether it exists upon initial creation or not.

**Comment by jeffwidman** [comment]
Good point! 

It could probably be considered an issue with either the GitHub + Slack integration or the PR create API, because if that allowed including labels on create than we'd happily support that. But you make a great point that there are scenarios where being notified on label-add is useful apart from PR creation.

Closing as I've passed this feedback along internally to the appropriate teams, and there's nothing more we can do here from the Dependabot side... and it's definitely out of scope for `dependabot-core` library.

For anyone affected by this, the best place to give public feedback to the PR/Slack integration teams is via creating a new discussion here: https://github.com/orgs/community/discussions/.
