### ISSUE TITLE
Dependency upgrade for new branch 

### ISSUE THREAD

**Issue by mejuhi** [dependabot/dependabot-core#4727]
We have multiple branches in our repository. In dependabot yaml we have mentioned the target branch, if we close any pull request for a version upgrade and later on change the target branch on dependabot.yaml to point to a different branch same pull request does not get raised.
We expect once a pull request is closed for that branch and later if target branch is changed, it should open all the pull request for dependency upgrades

For example:

We have a pull request for upgrading some python dependency (1.0 to 2.0) and we closed it for the branch 'branch1' 
Now when we create a new branch and changing dependabot to new branch and we switched the default as newly created branch. 
Since it is a new branch we are expecting the pull request for all the version upgrades should get opened (even though the pull request was closed for other branches)

**Comment by jurre** [comment]
I'm not sure that I'd consider this a bug, I think the behavior is desirable for most users. They've already told dependabot they don't want this update and changing the branch is IMO not a clear signal that this has changed.

I think you should be able to reopen the old PR and maybe you'll need to change the base branch and tell dependabot to rebase it (`@dependabot rebase`).

**Comment by ajishikea** [comment]
Hi, We understand the scenario. It will fit for the one branch concept with out parallel development.
How we can do this for Parallel development branches? Kindly look below example and suggest

We have parallel development the base branch is  Branch_A and i dependabot is pointing to Branch_A so we using to get all the latest version in some point of time this branch is freezed and we waiting for testing team to gohead. During freezed time we got around 100+ pull request. We don’t want to merge since we close all the pull request.

During Branch_A in testing we got new requirement and we created new Branch_B from production. Now I am changing the base branch and dependabot to Branch_B now I was expecting depondabot will run and fetch the newversion even though it has been closed in other branch.

Do we have any solution for this? Since we have around 100+ pullrequest we cant go and reopen all pull request.

**Comment by jeffwidman** [comment]
This is a fairly complex scenario, I suggest automating it with GitHub actions.

I'm going to close as I don't think there's a straightforward way for us to resolve this without annoying all the users who'd prefer those PR's to remain closed. In general, most teams seem to be moving away from having lots of branches for parallel development, prefer'ing to release early/often. That's not always possible for folks with multiple deployment targets, but in that case I still typically see a "mainline" dev branch that then gets backported or occasionally snapshotted/promoted to the release branch... I really haven't heard of many times when they want Dependabot PR's simultaneously against multiple branches.
