### ISSUE TITLE
Respect semantic version for npm

### ISSUE THREAD

**Issue by Verbalinsurection** [dependabot/dependabot-core#4734]
I have a package.json with :
```
"dependencies": {
    "@actions/core": "^1.6.0",
    "@actions/github": "^5.0.0",
    "actions-exec-listener": "0.0.2",
    "node-fetch": "^2.6.7",
    "xml2js": "^0.4.23"
  },
```
For exemple `"node-fetch": "^2.6.7"` meaning that I accept update for minor version like `"node-fetch": "^2.99.99"` but not major.

Today dependabot create PR with this modifications : 
```
- "node-fetch": "^2.6.7",
+ "node-fetch": "^3.2.0",
```
PR available here : https://github.com/Verbalinsurection/track-pypi-version/pull/100

Any idea why semantic not respected ?
Thanks you

**Comment by jeffwidman** [comment]
There's a misunderstanding here. The range in specified in `package.json` is for when you run your code.

But Dependabot is actually for managing the dependency pins in your `package.json`... so it's _supposed_ to open PR's to bump these pins, so that when you're ready to change them, the PR is already ready to go for you.
