### ISSUE TITLE
Use ruby's default bundler version

### ISSUE THREAD

**Issue by waghanza** [dependabot/dependabot-core#4785]
Hi,

In `ruby` **2.7**, `bundler` version is **2.1**
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

With this line

https://github.com/dependabot/dependabot-core/blob/f6acb90326f54ad7b19d6045ad9d8f9960248855/bundler/lib/dependabot/bundler/helpers.rb#L21

`dependabot` use version **2.2** of `bundler` when reading `Gemfile.lock` made by the default bundler version in ruby 2.7

Any rationales behind this ?

Regards,

**Comment by waghanza** [comment]
Hi @brrygrdn,

Seems reasonable not to support all 337 versions of https://rubygems.org/gems/bundler/versions.

How about supporting minor version (last patch) for each current version of `ruby`, I mean :

- 2.7
- 3.0
- 3.1

ℹ️  2.6 support stops at this end of this month

This will make only 3 minors version :

- **2.1** for  `ruby` **2.7**
- **2.2** for  `ruby` **3.0**
- **2.3** for  `ruby` **3.1**

Regards,

**Comment by waghanza** [comment]
Also, why supporting `bundler` **1.17.3**. Is their still users of this version ?

**Comment by brrygrdn** [comment]
We generally don't factor in bundler/ruby version pairing since the version of Ruby in use is ultimately determined by Dependabot Core itself. We use variant bundler versions alongside our Ruby version as generally there isn't significant enough variance between Ruby and Bundler pairings to result in any difference in outcomes when generating diffs on Gemfiles.

The rationale for supporting Bundler 1.x vs Bundler 2.x is that there are significant breaking changes in the internal bundler code dependabot-core uses and at present we do actually have enough projects using Bundler v1.x versions it is worth supporting, but it's something we'd like to deprecate.
