### ISSUE TITLE
`SharedHelpers#with_git_configured` is non-thread safe 

### ISSUE THREAD

**Issue by mattt** [dependabot/dependabot-core#4909]
The `SharedHelpers#with_git_configured` method performs the passed block within a context where the global Git configuration file is swapped out for one generated by Dependabot: 

https://github.com/dependabot/dependabot-core/blob/e50d44cf5464c1ae1a7db1ce918c350459ed67a5/common/lib/dependabot/shared_helpers.rb#L161

This method is called by many of the ecosystem adapters, including `bundler`, `cargo`, `composer`, `go_modules`, `hex`, `npm_and_yarn`, `pub`, `python`, `terraform`.

As a result, Dependabot cannot be run safely from multiple processes at the same time. Because update jobs are performed in isolated, single-threaded environments, this isn't normally an issue. However, I've been looking at ways to speed up our test suite, and this came up as a blocker.

Using the [`parallel_tests` gem](https://github.com/grosser/parallel_tests) to run our rspec test suite could improve our runtime by a factor of 2–4x. But because of how this is currently implemented, a bunch of tests fail with the Git error `"unable to auto-detect email address"`.

Is there another way that we could execute Git commands with an ephemeral configuration?

**Comment by mattt** [comment]
It looks like `--config-env=` might give us what we need: https://git-scm.com/docs/git#Documentation/git.txt---config-envltnamegtltenvvargt

**Comment by jurre** [comment]
Thanks for opening this @mattt! I've also ran into this when trying to use `parallel_tests` (I've pushed the [branch](https://github.com/dependabot/dependabot-core/compare/jurre/parallel-rspec?expand=1) from when I experimented with this), but I gave up when I ran into this threading issue. _Maybe_ we can use a local git config? We'd just have to make sure to ignore it in cases where we create a temp directory in order to run some package manager commands, and then inspect the files in that directory for changes.

**Comment by mattt** [comment]
@jurre What if we set `GIT_CONFIG_NOSYSTEM=1`? According to [the Git docs](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables), that _should_ ensure that only the local configuration is read.

**Comment by jurre** [comment]
Yeah that sounds right, let's give it a spin? Would be pretty sweet if we could run things in parallel

**Comment by mattt** [comment]
@jakecoffman Could we replace this helper with a `git` shim like how you're doing with to resolving SSH URLs for Cargo?

**Comment by jakecoffman** [comment]
We'd be able to delete the configure_git_to_use_https method with the shim, but I think we'll still want the credentials configuration. Not sure how the shim would help there.

**Comment by yeikel** [comment]
I ignore why the current updater jobs are executed in isolated, single-threaded environments as running in parallel increases performance considerably beyond tests. 

I used to run `maven` upgrades sequentially and it used to take a very long time for projects with hundreds of dependencies. Parallelizing it speeds it up from hours to minutes. This is particularly relevant because our internal maven central proxy is slow and resolving each dependency individually takes a considerable time. 

I'd love to see this as well as I faced this similar problem while running `npm_and_yarn` in parallel and I am currently forced to run it in a single process.
