### ISSUE TITLE
Add a proper license

### ISSUE THREAD

**Issue by bittner** [dependabot/dependabot-core#491]
To solve your license uncertainties I would suggest you put the code in this repository under either [MIT](https://opensource.org/licenses/MIT) (popular, but allows closed-source development) or the [GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html) license (preferred, requires public development). This way you make sure your software remains free to use and extend for everyone forever.

From the [text in your README](https://github.com/dependabot/dependabot-core#license) it's evident that you're unsure about a choice, because you want to keep the possibility to ask for money. This is okay. However, try think about it this way:

- An actual free software is easier to make popular. Non-free software will always have the unclear license question as an issue (no matter what kind of custom permissions you give in a README).
- Make your tool globally popular, then build the accompanying services to it (website, dashboards, etc.) that create additional value. There will be customers ready to pay for it! Having a large audience it will be easy for you to have income.

This will make you happier and also (financially) successful in the end. You as the core developers will always be the ones that are in control as long as you put sufficient love into the product. And once you lose interest someone else will be able to build on your work (and you may not even care).

**Comment by greysteil** [comment]
Thanks for getting in touch - always good to talk these issues through.

Perhaps it would help to give some context? Dependabot Core is the key logic behind the Dependabot hosted service, which has a few thousand customers, a couple of hundred of whom pay. I develop it full time, on my own, without a salary. I don't *think* anyone else uses it (Dependabot Core), although I'm super positive about them doing so for non-commercial purposes.

There's a huge amount of work in Dependabot, as you can see from the changelog or the commits, and that work has only been possible because I think there's a financial return to it. To put some kind of number of that work, as it stands I've invested about $200k in forgone income in this project. That's been worth it to build something cool, and I'm proud to show it off, but I've spent my entire life's savings on this.

I considered licensing with MIT or AGPL v3, but ended up rejecting them for this project. The key consideration is this: I would be really unhappy if GitLab turned around tomorrow and said they'd taken Dependabot Core and were including it in their offering. Likewise GitHub or one of Dependabot's competitors. Were I to put either license on this project that would be possible (for GitLab), and they'd have no legal obligation to provide me with any compensation whatsoever.

Weighed against having to defend against the above is the adoption argument. However, for this particular library, I think the number of people who will ever want to use it is small. I've already said in the readme that I'm more than happy for others to hack together bots or scripts using it for their own personal use, or at work, so that use case is covered.

If I'm ever forced to give up on Dependabot as a commercial venture then I will certainly open source it, under an MIT license, but until this I think that the current setup is better. I'd feel pretty stupid giving $200k of work to GitLab for nothing, so I don't think I should write the legals that way...

**Comment by bittner** [comment]
If you're happy with it, totally fine.

I can't recommend your software in my projects, although I feel it may be a compelling alternative to, say, [pyup](https://github.com/pyupio/pyup) and others. Because it's not possible to use it as free software ("free" as in "freedom", not free beer). In my opinion, companies and individuals should decide to pay for a service because they see a real benefit in it (e.g. bodies from India or Eastern Europe may decide to do costly maintenance themselves -- because "costly" means something totally different to them as their salaries are low).

Fix the fear with GitLab eating you up. In some way. GPL may be an option (it doesn't allow closed-source development for their Enterprise offerings). Or go into negotiations with them. Not sure though if they already have decided for a different route (they bought [Gemnasium](https://gemnasium.com) half a year ago).

**Comment by greysteil** [comment]
👍, and sorry you won't be able to recommend Dependabot. Best of luck with @painless-software!
