### ISSUE TITLE
Rust: use toolchain from `rust-toolchain.toml`

### ISSUE THREAD

**Issue by martinohmann** [dependabot/dependabot-core#4915]
I'm wondering if there's a way to instruct dependabot to use a specific rust toolchain when it visits a repository. E.g. if a repo has a `rust-toolchain.toml`, use whatever rust version is set in there. That would be a great benefit I think :)

Implementing this feature might also reduce the number of issues opened regarding rust version bump requests in dependabot, e.g: #4574.

Using `rustup`, dependabot should be able to use any rust version there is if a `rust-toolchain.toml` file is provided.

My specific trouble with dependabot was that I was using a rust 1.59 feature but dependabot stopped working due to that since it's still running 1.58. So I abandoned this feature in favor of keeping dependabot working.

Not fair! I think the bot that's asking us to upgrade should be a shiny example and be running bleeding edge versions of everything (or be humble and follow what our toolchain files say) :joy: 

Btw: thanks for dependabot, you guys rock!

**Comment by jeffwidman** [comment]
Related:
* https://github.com/dependabot/dependabot-core/issues/4915

**Comment by jeffwidman** [comment]
So actually we do use the toolchain specified in the file... @jakecoffman just confirmed that in the logs, but mentioned it looks like we only search for `rust-toolchain` vs you have `rust-toolchain.toml`? So maybe just need to extend :dependabot: to look for that file as well?

Should be easy to pin down the root cause by using [the dry-run or CLI tool to simulate the job locally](https://github.com/dependabot/dependabot-core#debugging-problems).

Care to submit a PR?
