### ISSUE TITLE
Dependabot reports an alert on a deleted file - package-lock.json

### ISSUE THREAD

**Issue by qz912z7500** [dependabot/dependabot-core#4951]
Hello,
On the Github of my package, I am receiving dependabot alert for a deleted package-lock.json.
You can see in the screenshot that no file exist in the https://github.dxc.com/Platform-DXC/release-pipeline-backend project. (It has been removed 2 months ago).

**Package ecosystem**
docker
**Manifest location and content prior to update**
https://github.dxc.com/Platform-DXC/release-pipeline-backend

**What you expected to see, versus what you actually saw**
Dependabot error:
![image](https://user-images.githubusercontent.com/102995916/161621564-bbcd49e2-2fed-43b4-8d56-767581d093f3.png)

Click the link in the dependabot error
![image](https://user-images.githubusercontent.com/102995916/161621650-abeaf1e0-f5fa-49c9-9877-2c8257f155fa.png)

File directory in master branch - also shows no package-lock.json
![image](https://user-images.githubusercontent.com/102995916/161621860-d930c57c-ce96-4680-ae1b-f71b5f137d7d.png)

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

The issue tracker for this repo is about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves. Versus this issue is about the alerts themselves, not the resulting PRs.

So I'm afraid I'll have to close this.

I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles alerts. Feel free to drop a breadcrumb link on this issue to the discussion.

I will also add that that team has been shipping a lot of bugfixes the past six months, so there's a decent chance this has been fixed.
