### ISSUE TITLE
Support new SCM: Gerrit

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#496]
in an ideal world, direct support for raising changes on Gerrit instances instead of GitHub PRs.

in the meantime, just :robot: https://github.com/vorburger/vorburger-dotfiles-bin-etc/blob/master/bin/github2gerrit.sh works pretty well for me... :smiley:

**Comment by greysteil** [comment]
Interesting, thanks for the request. Adding support for new SCMs is a little way off (we're working on GitHub Enterprise right now as a starting point), but once we got from 1 to 2 I don't see why we shouldn't be able to add others relatively straightforwardly.

**Comment by ryjones** [comment]
Hyperledger would be interested in Gerrit support.

**Comment by infin8x** [comment]
Closing this as we don't expect to get to it in the foreseeable future. We're not accepting PRs at the moment due to capacity limitations, but in the future we expect to accept contributions that add or improve Gerrit support in Dependabot Core, as long as they don't damage the maintainability of Dependabot Core.
