### ISSUE TITLE
Dependabot doesn't work properly with monorepos

### ISSUE THREAD

**Issue by SpaNb4** [dependabot/dependabot-core#4993]
**Package ecosystem**
npm
**dependabot.yml content**
![image](https://user-images.githubusercontent.com/69504277/163219110-d5b82471-026c-4757-83b0-378371568a6c.png)

I use ```directory``` to specify multiple folders in my monorepo that uses **npm workspaces**. And when Dependabot creates PRs in this repo, it only updates a ```package.json``` file in a ```/packages/package-name/``` folder. Same behavior when using **lerna**
![image](https://user-images.githubusercontent.com/69504277/163222510-ffea2f93-7308-47c2-acab-065dbd804e9b.png)

Shouldn't it also update the ```package-lock.json``` for the root folder? 
Because for monorepos, we need to run the ```npm install <pkg> -w @nickname/package-name``` for npm workspaces or ```lerna add <pkg> packages/package-name``` for lerna to correctly install our dependencies. And these commands will update both ```/packages/package-name/package.json``` and the root ```package-lock``` files.

**What you expected to see, versus what you actually saw**
Dependabot updates both files: ```package.json``` in the specific package folder and ```package-lock.json``` in the root

**Comment by mellis481** [comment]
Any update on this? Dependabot effectively not working in monorepos is a significant problem.

**Comment by JoA-MoS** [comment]
I am also seeing this issue using npm workspaces

**Comment by dennisMeeQ** [comment]
For those still looking for a solution:
The solution is described here: https://github.com/dependabot/dependabot-core/issues/5226

Short version:
* Do not set up the `dependabot.yml` as described above (by listing each package individually) but by just listing the npm root like so:
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
```
* To trigger dependabot to also properly fix the `package-lock.json`, set `versioning-strategy: increase`

**Comment by jeffwidman** [comment]
Based on ☝️ I'm going to close this.

Given that you're effectively wanting the top-level file to change you need to tell Dependabot to start at that directory level... starting further down the tree won't work. 

Many thanks @dennisMeeQ for chiming in here. 🎉

**Comment by blowsie** [comment]
As per the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file) , dependabot is not configurable for Alerts, meaning the only way we can use dependabot in monorepos is to have it do updates.

I am unable to use dependabot for notifications only in my monorepo (pnpm workspace)

**Comment by jeffwidman** [comment]
This is an older ticket, please open a new issue because it's not entirely clear what you're asking, as there's a few different things going on... for example, you can set dependabot to only provide security update PR's (it's a hack but by setting the `open-pull-requests-limit: 0` to indicate you don't want version updates), although we don't yet support `pnpm` version updates: https://github.com/dependabot/dependabot-core/issues/1736. But again, please open a new issue.

**Comment by mellis481** [comment]
> For those still looking for a solution: The solution is described here: #5226
> 
> Short version:
> 
> * Do not set up the `dependabot.yml` as described above (by listing each package individually) but by just listing the npm root like so:
> 
> ```
> version: 2
> updates:
>   - package-ecosystem: "npm"
>     directory: "/"
> ```
> 
> * To trigger dependabot to also properly fix the `package-lock.json`, set `versioning-strategy: increase`

@dennisMeeQ Thanks for sharing this!

Question: If you have a mono repo that uses npm workspaces, the syntax to install/update a dependency in one of the mono repo packages is `npm install lodash@latest --workspace=packages/foobar`. What this means to me is that dependabot would need to effectively execute this same command when it creates a PR rather than doing an `npm install` (which I assume is what it normally does).  Are you able to say if configuring dependabot as you've recommended will correctly update dependencies for one, multiple, or all packages in a mono repo depending on which packages that dependency is used in?
