### ISSUE TITLE
FYI: Is dependabot-gitlab (unofficial "fork") okay?

### ISSUE THREAD

**Issue by puttehi** [dependabot/dependabot-core#5032]
https://gitlab.com/dependabot-gitlab/dependabot/

They definitely have a mention or two about this project but they do not respect your `LICENSE`. Just FYI.

**Comment by andrcuns** [comment]
I'm the maintainer of that project and it is not a fork, it's an orchestrator that uses `dependabot-core`.

I have been previously approached by `dependabot` team from GitHub, hence the disclaimer and as far as I know, it does respect the license, since it is not a commercial software and it mentions the `dependabot-core` in the `LICENSE`

https://gitlab.com/dependabot-gitlab/dependabot/-/blob/master/LICENSE#L17

**Comment by puttehi** [comment]
Good to know it's all good and straight =)

For reference, I was referring to this line in the `LICENSE`

> 2. Ensure everyone who gets a copy of this software from you, in
   source code or any other form, **gets the text of this license**
   and the contributor and source code lines above.
