### ISSUE TITLE
Provide more context in case of Error bumping dependencies

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#504]
It could be helpful if there as a file and line number in an error messages such as: _"Error bumping dependencies: Dependabot couldn't parse the Property not found: karaf.version found at Property not found: karaf.version."_ which I am getting from that little red triangle on my https://app.dependabot.com/accounts/vorburger/repos for https://github.com/vorburger/infrautils.

That error in this case is most likely due to #503, so this is more of a general suggestion, than something I need to figure out that particular problem.

**Comment by greysteil** [comment]
Sounds like it's definitely going to be #503 related, but I agree the error message could be better here - I'll take a look.

**Comment by greysteil** [comment]
OK, I've updated the error message so it will read:

```
Dependabot can't evaluate your Java dependency files.

As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.

The error Dependabot encountered was:

Property not found: karaf.version
```

Hopefully that's a little clearer! At the moment it will stop the update process entirely, but an alternative would be for Dependabot to just ignore dependencies that use a property version that it can't find. Would that be better?

(I've stopped short of including line numbers because I think grepping for the property name is probably the easiest way to find it.)

**Comment by vorburger** [comment]
> an alternative would be for Dependabot to just ignore dependencies that
> use a property version that it can't find. Would that be better?

actually I think that would be great! Best still show a warning though, not just completely silently ignore?

**Comment by greysteil** [comment]
Done! You'll still get an error if *all* of your dependencies rely on properties that Dependabot can't reach, but won't do otherwise.

Unfortunately it's not easy for Dependabot to show a warning in the partial case without it being kind of annoying (it will create a GitHub issue for you each time), so I've left that out for now. I'll have a think about how it could be done better, but in the case where Dependabot can't find a property there's no way that it would be able to update that property, so I *think* the new behaviour might be what's desired anyway.

Thanks for your feedback on this one - much nicer solution now 😄

**Comment by vorburger** [comment]
Cool - it works: https://github.com/vorburger/infrautils/pulls - thank you!
