### ISSUE TITLE
One notification/mail for dependabot (Digest mode)

### ISSUE THREAD

**Issue by mliradelc** [dependabot/dependabot-core#5098]
While I like Dependabot for helping keep updated the dependencies, I hate that fills every time my notifications and emails with every new dependency version.

Can we have a digest notification/email for Dependabot one time a week? (Except for the critical security ones)

**Comment by jeffwidman** [comment]
Sorry about the noise.

This repo/issue-tracker is only about creating the PR's, not the notifications that come from them. The only thing we can control here is creating fewer PR's, for that you're probably looking for:
* #1190 

Otherwise, if you want all these PR's but wish you could better control the notification settings, that's really a feature request for PR notification customization in general, and for that you'll need to start a discussion over in https://github.com/community/community/discussions/, as we have no control over notifications from PR's, and the teams responsible for notifications don't watch this repo's issue tracker (nor should they).

If you do start a discussion, feel free to drop a breadcrumb link to it here.
