### ISSUE TITLE
shows 'Dependabot version updates aren't configured yet' even when it is configured

### ISSUE THREAD

**Issue by yashash1511** [dependabot/dependabot-core#5112]
![image](https://user-images.githubusercontent.com/89068816/167456168-e8343e5f-a89d-4774-a0dc-56c885ceaa7c.png)
https://github.com/blueedgetechno/win11React/blob/master/.github/dependabot.yml

![image](https://user-images.githubusercontent.com/89068816/167456054-8a23861b-3ccc-4618-8d09-bd9d6f6f235f.png)
https://github.com/blueedgetechno/win11React/network/updates

happens with this particular repo only (even if i fork this repo and then enable dependabot on the fork it works in the fork)

**Comment by jakecoffman** [comment]
The Dependabot data was in a weird state for this repo so I manually resync'd it, and now it looks like it's in working order.

**Comment by yashash1511** [comment]
@jakecoffman

![image](https://user-images.githubusercontent.com/89068816/168880269-a3681f06-dfd0-45ea-8abe-eb7e71e02fe9.png)
unfortunately now it is stuck at 'Checking now'

**Comment by tillmannheigel** [comment]
@jakecoffman , how did you resync it?

**Comment by Will956** [comment]
@jakecoffman Hello 👋 we have exactly the same issue with one of our private repositories. I tried to delete/re-push our `dependabot.yml` but didn't fix the issue. I checked the file against the dependabot validator and it looks fine. Is this still an existing issue (repository in a weird state that needs to be resync), or is there anything I can do to fix that? Thanks 
![Capture d’écran 2023-01-10 à 18 02 37](https://user-images.githubusercontent.com/13664270/211616053-173c1bee-6366-4241-80f9-76acf9407bac.png)
![Capture d’écran 2023-01-10 à 18 02 52](https://user-images.githubusercontent.com/13664270/211616073-188a27fe-cfdb-4367-853a-3c7104188a5d.png)

**Comment by jorihardman-aumni** [comment]
@jakecoffman is there some way for users to initiate the resync? I'm having the same issue with the docker ecosystem and a private repo. I've added a config file when prompted but still get "Dependabot version updates aren't configured yet" and no updates.

**Comment by ianrathbone** [comment]
@jakecoffman seeing the same issue on our repo here:

https://github.com/4Com/vue-azure-app-configuration/blob/main/.github/dependabot.yml

Any way of running this command for us? Thank you!

**Comment by jeffwidman** [comment]
Sorry for the pain. 

Please file a new issue, as the original problem in this issue is solved... and yours, despite the same symptoms, may have a different root cause. So I'm not going to reopen, and comments on closed issues are easily lost track of.

You'll need to include a link to your repo so we can investigate, so if that's private, please file a support ticket instead.

More generally getting out of sync should be a very rare thing, and when it does happen, if it's reported before the logs expire we try to investigate deeper to actually fix the source of the race or add an auto-healing cleanup to the code.
