### ISSUE TITLE
nuget: add support for Basic Auth

### ISSUE THREAD

**Issue by hoerup** [dependabot/dependabot-core#5122]
Nuget update checker currently only supports token based authentication

Please consider adding basic auth with username &  password 

Until this is implemented (or if req is rejected) please update the docs to correspond this

**Comment by hoerup** [comment]
Well it turns out it  can be tricked into basic auth if I provide a "token:" value generated as "username:password"

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

Are you running Dependabot as the native service on GitHub, or standalone via something like https://github.com/dependabot/dependabot-script?

I ask because the credential handling is different for those two paths, so it's unclear to me which section of code is resulting in the behavior you're seeing. 

In GitHub native we run a sidecar proxy so that creds are never actually exposed to `dependabot-core`, to eliminate the chance that a malicious package could extract creds and then phone them home. That proxy may need to be extended to support basic auth. Or if you're running standalone, then probably `dependabot-core` needs extending.

**Comment by jeffwidman** [comment]
Nudge @hoerup

**Comment by brettfo** [comment]
Authentication from `dependabot.yml` now supports two formats: `token: "username:password"` and `username: myuser`/`password: mypassword`.
