### ISSUE TITLE
Improve commit message configuration doc.

### ISSUE THREAD

**Issue by fuadop** [dependabot/dependabot-core#5192]
Reading the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message) to create custom commit messages, lacks result examples. I suggest if you can please add an example off what the commit messages would be looking like after setting the `prefix: "my_prefix"` and `include: "scope"`.  

Had to do trial and error with two PRs to know what the commit message would look like !.

**Comment by jeffwidman** [comment]
Good idea!

Did you realize you can actually submit a PR against the docs yourself? Scroll to the bottom of the page and click "Make a contribution" which should lead you [here](https://github.com/github/docs/edit/main/content/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file.md). You can edit the file directly from the Web UI, no need to `git clone` etc.

Would you be willing to put together a PR based on what you discovered from your two test PR's? 

Otherwise one of us will likely need to do the same trial/error work that you did to see what it looks like before we can submit a fix to the docs team, and there's no sense in duplicating work if you've already figured it out.

If you post a link to the PR here, then I can work with the docs team to help make sure it gets merged promptly.

**Comment by fuadop** [comment]
Hi @jeffwidman 👋🏾 , thank you so much for your feedback. I'll check the doc repo out.

**Comment by fuadop** [comment]
related issues/PRs where we've had issues knowing what the commit-message would look like:

- https://github.com/LearningTypeScript/projects/pull/29
- https://github.com/LearningTypeScript/projects/pull/23

**Comment by mchammer01** [comment]
I'll take a look at this on behalf of Docs 😃
