### ISSUE TITLE
Dependabot shouldn't open PRs if it will take a "good" id 😉

### ISSUE THREAD

**Issue by jonthysell** [dependabot/dependabot-core#5193]
Over in [React Native for Windows](https://github.com/Microsoft/react-native-windows) we were coming up on issue/PR 10,000. What a milestone for an OSS project!

Imagine our dismay when it ended up getting grabbed by dependabot: https://github.com/microsoft/react-native-windows/pull/10000

Dependabot should check that it isn't going to take a "good" id number by opening a PR. Maybe something like:

```js
while (isPowerOfTen(nextID)) { sleep(0) };
```

See https://codereview.stackexchange.com/questions/117203/checking-whether-a-number-is-a-power-of-10 for options on defining `isPowerOfTen()`.

**Comment by jeffwidman** [comment]
Congratulations, 10K is an impressive milestone! 🥳 

I'm a maintainer on a number of OSS projects, so I understand the urge to celebrate project milestones. Although I'm a little surprised as I rarely hear of projects celebrating the number of tickets/PRs... more typical is number of commits, or number of committers, or a particular release.

One difficulty with this feature request is that it leaves open-ended the question of "so what do we do if we've got a valid PR but on a 'special' number?" Because some (most?) project owners will want the immediate PR, and others will want to reserve it. Sure, we could build in a special config for reserved ID's, but by the time we roll that out, write tests, docs etc it takes a fair bit of work.

Given the work required and that this affects less than 0.01% of projects running Dependabot, I don't think it's worth putting our limited resources into.

Congratulations again on the milestone!
