### ISSUE TITLE
add comment to PR after rebase

### ISSUE THREAD

**Issue by OskarStark** [dependabot/dependabot-core#522]
Hey,

it would be cool if the PR could pop up again in the notifications after a rebase, so instead of updating the PR header it should add a comment:

- when executing the reabse

and

- when the rebase is finished.
In this case i get notified again, but to not bother anyone, a setting could be nice!

**Comment by greysteil** [comment]
Interesting. This one would definitely need to be a setting, as I think a lot of people wouldn't want the noise. I have a couple of bugs I need to crush first, and want to add settings for auto-merging first, but will get to this. I'm also going to delay it a little in case GitHub implement a better notification flow (there's talk of apps being able to insert items into a PR's timeline, which would be really slick for this).

I'm also going to move this over to https://github.com/dependabot/feedback, because the work required isn't in dependabot-core.

**Comment by OskarStark** [comment]
Thank you 👍
