### ISSUE TITLE
Github advisories to accept comments

### ISSUE THREAD

**Issue by frackham** [dependabot/dependabot-core#5269]
The text of a dependabot auto generated PR appears to be driven from github advisories (please correct me if I'm wrong!).

e.g. https://github.com/advisories/GHSA-gpqq-952q-5327 

However, if the text of this advisory is wrong/unhelpful, the only way you can submit a change is to submit a PR. Often, the user of a dependabot alert won't know what the fix/correct text is, only that the underlying advisory may have some incorrect info.

In the example of the advisory above, I can see that the exploit under Impact is incorrect. `doEvilThing` isn't mentioned in the example, so can't be being called. I don't see any way of raising this.

Appreciate that this is upstream from you, don't see any other way to surface this! I suspect that this is just a limitation that has to be accepted.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

This repo / issue tracker is about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves. Versus this issue is about the alerts themselves, not the resulting PRs.

So I'm afraid I'll have to close this.

I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles alerts. Feel free to drop a breadcrumb link on this issue to the discussion.
