### ISSUE TITLE
Dependabot cannot fix a vulnerability

### ISSUE THREAD

**Issue by Milo123459** [dependabot/dependabot-core#5340]
**Package ecosystem**
cargo
**Package manager version**
1.62.0 (latest stable version)
**Language version**
rust 1.62.0
**Manifest location and content before the Dependabot update**
n/a
**dependabot.yml content**
n/a
**Updated dependency**
crossbeam-utils
**What you expected to see, versus what you actually saw**
dependabot to create a pr, instead it failed with this message:
```
updater | INFO <job_405055966> Requirements to unlock update_not_possible
updater | INFO <job_405055966> Requirements update strategy bump_versions
updater | INFO <job_405055966> The latest possible version of crossbeam-utils that can be installed is 0.7.2
updater | INFO <job_405055966> The earliest fixed version is 0.8.7.
updater | INFO <job_405055966> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
```

It's rather annoying seeing it pop-up on my repository page, but dependabot can't actually fix it. The error message is also very unclear.

**Comment by Milo123459** [comment]
This is happening to every single vulnerability dependabot finds in my rust projects. Very annoying that it warns me about it but can't do anything about it.

**Comment by jurre** [comment]
Could you please share the contents of your manifest and lockfile (`Cargo.toml` and `Cargo.lock`)? It looks like some other dependency is pinning the version to a vulnerable version, but it's hard to tell without being able to see the relevant files

**Comment by Milo123459** [comment]
https://paste.rs/nV1 https://pastebin.com/6XuiK8Jh

**Comment by jurre** [comment]
It looks like `crossbeam-epoch` and `crossbeam-queue` depend on that vulnerable version of `crossbeam-utils`, and when traversing the dependency tree up to the top-level dependencies I can see `prisma-client-rust` and `serenity` ultimately pull them in via their own transitive dependencies. `prisma-client-rust` @ 0.5.2 pulls `query-core` at a [git rev](https://github.com/Brendonovich/prisma-client-rust/blob/0.5.2/cli/Cargo.toml#L19) which pulls in `crossbeam-queue` at 0.2 which pulls in `crossbeam-utils` at ^0.7: https://crates.io/crates/crossbeam-queue/0.2.3/dependencies

So in this case I don't think there is a way for dependabot to resolve the issue, even updating `prisma-client-rust` would not resolve the issue: https://github.com/Brendonovich/prisma-client-rust/blob/0.6.0/cli/Cargo.toml#L19

**Comment by Milo123459** [comment]
Thanks for the info. It would be nice to get a detailed explanation like this on vulnerabilities as to why they cannot be fixed.

**Comment by jeffwidman** [comment]
I'm going to close as the underlying root cause was fixed. 

Also, I agree completely it'd be nice to have a full explanation on each vulnerability when Dependabot is unable to create a PR to fix it, but  I'm afraid an explanation for each one-off vulnerability is probably not going to be something we will do anytime soon.

We _are_ working on adding more clarity for these `update_not_possible` cases, but we're prioritizing the problems that systematically affect many PR's across multiple security updates. So perhaps Dependabot may one day be smart enough to auto-generate a message saying that it walked the tree and there was no way to pull them in due to transitive dependencies out of its control etc... But that's probably quite a ways off unfortunately.
