### ISSUE TITLE
Does not respect the targeted Node.js version

### ISSUE THREAD

**Issue by sindresorhus** [dependabot/dependabot-core#5489]
**Package ecosystem**

npm

**Config**

https://github.com/sindresorhus/to-readable-stream/blob/d2ca3e102351a57b2b6f8f68027ffbb493e9280f/.github/dependabot.yml

---

I have a package that defines in package.json that it supports Node.js 12 and later: https://github.com/sindresorhus/to-readable-stream/blob/d2ca3e102351a57b2b6f8f68027ffbb493e9280f/package.json#L15-L17

I expect Dependabot to only upgrade dependencies that are compatible with Node.js 12. However, in https://github.com/sindresorhus/to-readable-stream/pull/12, it upgraded a dependency that requires Node.js 14 and later (not 12). (You can see this if you click on "Release notes" there). This obviously breaks CI and wastes my time.

**Comment by mattt** [comment]
Hey @sindresorhus! Thanks for trying out Dependabot version updates and taking the time to open an issue. I'm sorry this wasn't working as expected for you.

I just cloned [`sindresorhus/to-readable-stream`](https://github.com/sindresorhus/to-readable-stream) and tried out a few things:

Running `npm update tsd`, and it didn't update the downloaded version. This makes sense because no other releases satisfy the requirement `^0.14.0`:

```console
$ curl "https://registry.npmjs.org/tsd/" | jq ".versions | keys" 
  # ...
  "0.13.0",
  "0.13.1",
  "0.14.0",
  "0.15.0",
  "0.15.1",
  # ...
  "0.22.0",
```

To update the requirement of the dependency to the latest version, I tried:

```console
$ npm install --save "tsd@*"
```

Doing this updates `tsd` to the latest release, `0.22.0`, which is what Dependabot proposed in https://github.com/sindresorhus/to-readable-stream/pull/12. However, as you correctly point out, that's the wrong behavior.

In the context of an application, it’s a bit easier to get `npm` to do what we want. By enabling [`engine-strict`](https://docs.npmjs.com/cli/v8/using-npm/config#engine-strict) option, it should honor the host engine settings when determining which version to install.

```diff
+ 	"engineStrict": true,
```

In the context of a library, where it’s about the requirements of engines as a meta dependency, I couldn’t find a way to that with `npm` alone. However, [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates) appears to do the right thing:

```console
$ npx npm-check-updates -u tsd --enginesNode
Using yarn
Upgrading /Users/mattt/Downloads/to-readable-stream-main/package.json
[====================] 1/1 100%

 tsd  ^0.14.0  →  ^0.21.0
```

As far as Dependabot goes, we’re actively looking into ways to delegate core functionality to dedicated, ecosystem-specific tools. I can’t give you a timeline or roadmap yet, but I’m really excited about the direction we’re taking. I’ve made a note about this specific behavior, and will make sure that it’s addressed as part of these upcoming improvements.

**Comment by ElvenSpellmaker** [comment]
I'm having a very similar issue whereby I have a basically completed library and Dependabot keeps trying to update to packages that don't satisfy my version settings.

E.g.: https://github.com/ElvenSpellmaker/node-service-status/pull/73

I've clearly stated I need Node > 12: https://github.com/ElvenSpellmaker/node-service-status/blob/822a679e0759e9abcc598abbecac5f23d43805f1/package.json#L11-L13

**Comment by jeffwidman** [comment]
As mentioned above, and [documented here](https://stackoverflow.com/a/29349773/770425), you need to set `engine-strict=true` in `.npmrc` for those version constraints to be enforced.

Also as noted above, that isn't a great solution for a library... but I'm not currently aware of any other solution offered by native `npm`.

Dependabot is focused on being the glue code that fetches manifests then hands them off to native package managers to process/generate the suggested updates, and then Dependabot turns those into PRs. So this is something that needs to be fixed by upstream `npm`, and then we'll happily pull it in.

I'm going to close as I'm not aware of any alternative here, but if for some reason I'm wrong or missing information please comment and we can reopen.

Also related:
* https://github.com/dependabot/dependabot-core/issues/4072
