### ISSUE TITLE
`-slim` suffix removed when updating Dockerfile base image from `python:3.10.5` to `python:3.10.6`

### ISSUE THREAD

**Issue by grahamalama** [dependabot/dependabot-core#5538]
In a multistage build with two python base images:
```
python:3.10.5 as base
python:3.10.5-slim as production
```

the `-slim` suffix wasn't preserved in an update from `3.10.5` to `3.10.6`

**Package ecosystem**
docker

**Manifest location and content before the Dependabot update**
https://github.com/mozilla/jira-bugzilla-integration/blob/main/Dockerfile

**dependabot.yml content**
https://github.com/mozilla/jira-bugzilla-integration/blob/main/.github/dependabot.yml

**Updated dependency**
`python:3.10.5-slim`

**What you expected to see, versus what you actually saw**
What I expected to see:
`python:3.10.5-slim as production` -> `python:3.10.6-slim as production`

What I saw:
`python:3.10.5-slim as production` -> `python:3.10.6 as production`

**Images of the diff or a link to the PR, issue, or logs**
```diff
diff --git a/Dockerfile b/Dockerfile
index 4324ead..d64ace4 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,5 @@
 # Creating a python base with shared environment variables
-FROM python:3.10.5 as base
+FROM python:3.10.6 as base
 ENV PIP_NO_CACHE_DIR=off \
     PIP_DEFAULT_TIMEOUT=100 \
     PIP_DISABLE_PIP_VERSION_CHECK=on \
@@ -21,7 +21,7 @@ COPY ./poetry.lock ./pyproject.toml ./
 RUN poetry install --no-dev --no-root
 
 # `production` stage uses the dependencies downloaded in the `base` stage
-FROM python:3.10.5-slim as production
+FROM python:3.10.6 as production
 ENV PORT=8000 \
     PYTHONUNBUFFERED=1 \
     PYTHONDONTWRITEBYTECODE=1 \

```

**Comment by jeffwidman** [comment]
There's a chance we may have to revert the fix for this given the discussion in https://github.com/dependabot/dependabot-core/issues/3261 and the fact that it included similar PR which then got reverted... [a few more details](https://github.com/dependabot/dependabot-core/pull/5560#issuecomment-1230941234).

But even if #5560 gets reverted, this should still stay closed as a duplicate of 
* https://github.com/dependabot/dependabot-core/issues/3261
