### ISSUE TITLE
Expose branch_name_prefix in common\lib\dependabot\pull_request_creator.rb 

### ISSUE THREAD

**Issue by KnicKnic** [dependabot/dependabot-core#5571]
I would like to expose branch_name_prefix so it can be configurable.

The reasoning is that I am running dependabot against an Azure DevOps repository. I run dependabot multiple times against this repostory using separate directories as filters. I would like for each directory potentially create independent PR's even for the same dependencies. The easiest way I see to accomplish this is to set the branch_name_prefix independently for each directory.

**Comment by andrcuns** [comment]
I'm using `dependabot-core` directly and I am able to create dependency updates for the same dependency in different directories because branch name actually includes the directory dependency is located in. https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/pull_request_creator/branch_namer.rb#L49

**Comment by jeffwidman** [comment]
It sounds like the problem is how `dependabot-core` is being executed since it's not done directly but instead via the `tinglesoftware/dependabot-azure-devops` wrapper... many thanks to @mburumaxwell for documenting how to set this up
https://github.com/tinglesoftware/dependabot-azure-devops/issues/334#issuecomment-1250694422 to preserve the directory names.

**Comment by jeffwidman** [comment]
Also I closed because I'm reasonably confident this is working as expected and just requires tweaking your config, but if for some reason this isn't resolved via the config mentioned ☝️ please comment and we can re-examine...
