### ISSUE TITLE
Branch protection rule for `main`: require conversation resolution before merging

### ISSUE THREAD

**Issue by HonkingGoose** [dependabot/dependabot-core#5601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

This is a tip for the Dependabot maintainers, not a feature request for the bot itself. 😉 

You can configure GitHub to only allow merges when _all_ conversations on the Pull Request are marked as resolved. [^gh-docs] This stops you from accidentally merging things that are not ready.

To enable this rule:

1. Go to this repository's _settings_ tab (as a member with sufficient rights)
2. Click on _Branches_ in the sidebar
3. Go to the branch protection rules for the `main` branch, and click on edit
4. Check the box labeled: **Require conversation resolution before merging**
5. Done

[^gh-docs]: [GitHub Docs: branch protection rules, require conversation resolution before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-conversation-resolution-before-merging)

**Comment by jeffwidman** [comment]
👋 Thanks for the heads up. 

I'm aware of this feature, but I actually prefer not to enable it... I often use conversations on my PR's to document _why_ I may have done something... commentary that would be too noisy to put in a code comment, but it still useful for the PR reviewer to know.

I've found that if the conversation is resolved before merge, then it's easy for later code spelunkers to completely miss that commentary... vs just keeping it floating allows someone to quickly say "oh, that's why they did it that way"...

I definitely understand it can save some headaches, but so far that hasn't been a recurring issue for us. If it starts becoming a problem, then we'll enable this safeguard.
