### ISSUE TITLE
How to setup dependabot to take care of the dependencies of a specific branch?

### ISSUE THREAD

**Issue by franktopel** [dependabot/dependabot-core#569]
I have a private repository which has a long-living branch which the main development takes place on. I have setup dependabot to work on that repository - and it does so very nicely, but it works on the master branch. How do I configure dependabot to work on an additional/different branch?

**Comment by greysteil** [comment]
Hey @franktopel,

When you add an update config to a repo you can select the branch of Dependabot to target under "advanced options". It will then open PRs against that branch. Unfortunately you'll have to do the change as a delete-and-add, because we don't support updating the target branch on an update config at the moment (I should change that).

Hope that clears things up, and thanks for using Dependabot!

**Comment by franktopel** [comment]
@greysteil Delete-and-add won't help me, I need dependabot on both the master and the specific, long-living dev branch within the same repository.

**Comment by greysteil** [comment]
Ah, sorry, in that case you can just add a second update config for the same repo, but with the different target branch. If you click `add language` on that repo in your Dependabot dashboard then you can add the same language again, as long as you set s different target branch in the advanced options.

Let me know if that doesn't work for you. There aren't many people using Dependabot with that setup, but I know that the folks at owncloud do and that it works for them.

**Comment by franktopel** [comment]
What is the dependabot dashboard? Is it the page I find under https://github.com/settings/installations/XXXXX ? If yes, I cannot find an "Add language" function/button/whatever there.

**Comment by greysteil** [comment]
It's [here](https://app.dependabot.com).

**Comment by kkuk6-dev628** [comment]
Hi, I also have this issue.
@franktopel, how did you fix?
