### ISSUE TITLE
Gradle constraints

### ISSUE THREAD

**Issue by Pr0methean** [dependabot/dependabot-core#5764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I use Gradle constraints to update transitive dependencies when no available version of the direct dependency does so. It would be nice if Dependabot could automatically update transitive dependencies by adding and updating constraints, e.g. if it could have generated https://github.com/Pr0methean/OcHd-KotlinBuild/commit/e0e1d0d4e152b85d71b1f3839f66b4a4ee84b4e7 automatically.

**Comment by jeffwidman** [comment]
In general, we'd like to provide better support for Java, both Gradle and Maven. It's one of our more popular ecosystems. However, there's a lot of complexity there so probably we'll need to lean more on native helpers rather than continuing to duplicate (poorly) the logic in Ruby. So so any new features in that area will be a larger lift and probably something that it'll take us a bit to get to. Also, transitive would be convenient, but the first step is making sure our support for direct deps is rock solid.
