### ISSUE TITLE
NPE in ReleaseFinder

### ISSUE THREAD

**Issue by leoamigood** [dependabot/dependabot-core#5787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

dependabot-common

### What you expected to see, versus what you actually saw

Looks like `ReleaseFinder` in common does not check for wether dependency.previous_requirements exist:
```
NoMethodError: undefined method `filter_map' for nil:NilClass

          previous_refs = dependency.previous_requirements.filter_map do |r|
                                                          ^^^^^^^^^^^
```

i get this for example on:
```
dependency = {Dependabot::Dependency} #<Dependabot::Dependency:0x0000000113f5e678>
 @name = "rails"
 @package_manager = "bundler"
 @previous_requirements = nil
 @previous_version = nil
 @removed = false
 @requirements = {Array[1]} [{:requirement=…]
 @version = "7.0.3.1"
```

**Comment by jeffwidman** [comment]
How are you running Dependabot? 
This doesn't look like the normal logs output from the service... are you using the dry-run script or some other entrypoint? 

Are you running on github or another platform?

This may be a legit bug, but it'd be helpful if you had an example repo with the manifest file that is triggering this bug...

**Comment by leoamigood** [comment]
That's an output in my Rubymine, yes, i am running it against github:

```
metadata = Dependabot::Bundler::MetadataFinder.new(
  dependency:,
  credentials: 
)

metadata.releases_text
```

see dependency object above

**Comment by jeffwidman** [comment]
Can you clarify how you're planning to actually use `dependabot-core`? I assume you're not just playing around with random method calls, but actually planning to build something with it.

In general for Ruby code, it's not hard to make it crash easily if you want to, by hitting code paths or feeding inputs nobody expects/uses.

I appreciate your bug reports, but it's actually not our goal to not crash on _any_ situation... instead, we want to be sure we don't crash in _normal_ use cases using normal expected entrypoints. So that's why it'd be helpful if you can clarify your entrypoint and actual practical use case.

Also, for any of these, feel free to submit PR's. It's all open source.

**Comment by leoamigood** [comment]
@jeffwidman Good point. I actually don't remember which repo i got this error on. Let's close this issue, i'll reopen with more details if i git it once again. Thank you
