### ISSUE TITLE
[Composer] Dependabot replace repository type by vcs 

### ISSUE THREAD

**Issue by codisart** [dependabot/dependabot-core#589]
When running Dependabot for a composer project with the "repositories" param, it replaces `type="git"` by `type="vcs"`.

Since composer has to intepret the url given to know what client to use, it seems more optimal to use git. So I think this modification by dependabot is wrong when the type is already done.

**Comment by greysteil** [comment]
Frustratingly, I think this is required. From memory (and the comment I put on the code) if `git` is used then Composer doesn't use its auth credentials - the relevant code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_updaters/php/composer.rb#L127-L131).

That said, since I wrote that I added the ability for Dependabot to use git's underlying auth, which Composer *might* fall back to in this case. Do you have a repo you can test it on?

**Comment by greysteil** [comment]
Fixed! 🎉
