### ISSUE TITLE
packages defined in subdirectories

### ISSUE THREAD

**Issue by dschep** [dependabot/dependabot-core#603]
Is it possible to have dependabot manage updates for a sub-directory of a repo?

ie repo looks like
```
/
/package.json
/subfolder
/subfolder/package.json
```

**Comment by greysteil** [comment]
Absolutely - if you click "add language" in your dashboard and then "advanced options" then you can select a sub-directory for Dependabot to operate on there. If you use Lerna or Yarn workspaces then it will automatically pick up all of your packages and update them in a single PR (per dependency, rather than multiple PRs for the same dependency).

**Comment by dschep** [comment]
Awesome. Thanks!
