### ISSUE TITLE
PR Submitted for Missing JAR in Central

### ISSUE THREAD

**Issue by jeremylong** [dependabot/dependabot-core#605]
Please see https://github.com/jeremylong/DependencyCheck/pull/1381

A PR was submitted for groovy-all-2.5.1. However, if you look in [Central](http://central.maven.org/maven2/org/codehaus/groovy/groovy-all/2.5.1/) - the JAR file itself is missing.

**Comment by greysteil** [comment]
Ah, sorry, I saw your comment on this but was crunching on adding Go support. That’s done now, and I’m going to spend the next few weeks working on polish - I’ll make sure this gets fixed!

**Comment by greysteil** [comment]
Ah, this is embarrassing - I'd fixed this but had managed to type both the code and the test for it. Fixed in https://github.com/dependabot/dependabot-core/commit/d2ae4bacf8b1cf34ba045b10c1b8a425097b8328.

I'll re-run Dependabot on all existing Maven PRs to close any that shouldn't be open once that's deployed.
