### ISSUE TITLE
Yarn Berry Cache not included in dependabot PRs where cache exists

### ISSUE THREAD

**Issue by wozzo** [dependabot/dependabot-core#6076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

3.2.x

### What you expected to see, versus what you actually saw

Yarn's offline cache is not updated by dependabot when using the `nodeLinker: node-modules` setting from yarn.

This relates to [PR #6017](https://github.com/dependabot/dependabot-core/pull/6017) and [my comment](https://github.com/dependabot/dependabot-core/pull/6017#issuecomment-1303802118).

We are using [Yarn's offline cache](https://yarnpkg.com/features/offline-cache/#gatsby-focus-wrapper), so a zip file is stored for each dependency.
When updating the a dependency the old zip file is typically deleted and a new one added to the repository in the cache folder (default `.yarn/cache`).

However this fix assumed that the offline cache was always used with zero-installs and checks for the existence of the `.pnp.cjs` file to determine whether to update the cache.
The existence of this file relates to the [`nodeLinker` option's value](https://yarnpkg.com/configuration/yarnrc#nodeLinker)
We use `node-modules`, not `pnp` so the above file does not exist, but we still maintain an offline cache at `.yarn/cache`.
The location of the offline cache is configured with the [`cacheFolder` option](https://yarnpkg.com/configuration/yarnrc#cacheFolder).

I think dependabot should check for the existence of the cache folder in the repository instead of the `.pnp.cjs` file as the determining factor in whether to update the cache or not.

**Comment by pavera** [comment]
The issue I ran into when we used the existence of the cache folder as a determinant was that on repositories which do not have that folder committed, once we run an update the cache folder is created and so suddenly we detect that we should be updating the cache, which is not what the user wants in the case where the cache folder is not committed. I'll be revisiting this in the next few days as the PR you mentioned also did not fix the permissions change on `.pnp.cjs`. Thanks for the heads up here, I think we might need to inspect `.gitignore` or maintain state about the original state of the repo so that changes induced by Dependabot don't change behavior mid-update.

**Comment by wozzo** [comment]
@pavera has there been any progress on this?

**Comment by pavera** [comment]
@wozzo unfortunately no, it's now next on my plate, I should be starting work on it tomorrow.

**Comment by pavera** [comment]
@wozzo I've deployed the PR that I believe resolves this issue. I'm closing the issue but if you continue to see the problem feel free to re-open! Thanks for bringing this to our attention :)
