### ISSUE TITLE
Alerts on dependencies that I do not have in my project

### ISSUE THREAD

**Issue by fromi** [dependabot/dependabot-core#6134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

yarn 1.22.19

### Language version

Node.js 16.17.1

### Manifest location and content before the Dependabot update

https://github.com/fromi/game-park/blob/master/yarn.lock

### Updated dependency

Prototype pollution in webpack loader-utils
Package: loader-utils (npm)
Affected versions: < 1.4.1
Patched version: 1.4.1

minimatch ReDoS vulnerability
Package: minimatch (npm)
Affected versions: < 3.0.5
Patched version: 3.0.5

### What you expected to see, versus what you actually saw

Issues are open with this text:
**No security update is needed as minimatch is no longer vulnerable
Dependabot hasn't attempted to update minimatch as it's no longer vulnerable.**

Both issues links to [package-lock.json](https://github.com/fromi/game-park/blob/-/package-lock.json)
This file does not exist in my project, as I am using yarn, not npm.
Finally, both loader-utils & minimatch does not exist in my yarn.lock file.

Also, when I try to dismiss the alerts they still appear in the open alerts. And I receive emails.

**Comment by jeffwidman** [comment]
👋 Sorry for the slow response.

This repo is about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves. Versus this issue is about the alerts themselves, not the resulting PRs.

So I'm afraid I'll have to close this.

I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles alerts. Feel free to drop a breadcrumb link on this issue to the discussion.

I'll also add that a number of bugfixes have shipped around this fairly recently, so there's a chance it's been fixed in the past few months.

**Comment by fromi** [comment]
Thanks, indeed the bug has disappeared meanwhile.

**Comment by jeffwidman** [comment]
Awesome, that's great news!
