### ISSUE TITLE
`@dependabot only next major` command

### ISSUE THREAD

**Issue by staabm** [dependabot/dependabot-core#6211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

time goes by pretty quickly which turns into dependabot pull requests, which jump across several major versions, e.g.

![grafik](https://user-images.githubusercontent.com/120441/203936687-0101b7c5-2479-4d68-9a2e-0afa7f2240f5.png)

it would be great, if we could instruct dependabot with a new command, e.g. `@dependabot only next major` and dependabot would then provide a PR which only jumps to the next major version (relative to the one currently used), instead of the latest new major version.

so we could approach the update in several steps and do breaking changes per major version instead of possilbly creating huge high risk PRs with lots of BC related changes.

in the above case (screenshot), this would mean dependabot would create a PR for `Bump complex/clxfrontendcms from 2.8 to 3.x.y` instead of the jump immediately to `8.3.4` across 6 major versions

**Comment by jeffwidman** [comment]
👋 The use case makes sense, I've lived this problem myself.

Since Dependabot opened/closed PR's for those previous versions, an easy solution is to pull up the list of closed PR's, probably limit to the ones from `dependabot` and then find the specific intermediate version you wish to bump to... then re-open and merge that PR. You'll probably have to manually re-build it to fix merge conflicts.

Another possible thing to do is manually [add an `ignore` condition to your `dependabot.yml`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) that ignores the later major versions. That allows you to then re-open the old PR and do a `@dependabot rebase` and it will rebuild the old PR on top of tip of `HEAD`. This would be temporary... as you slowly bump to the newer major versions, you remove those `ignore` conditions.

This won't work for someone who just started using Dependabot, but that's a one-time migration so not worth worrying too much about IMO.

While this does make sense as a convenience, I think it's unlikely that we'll build it since the `ignore` workaround is so straightforward. I'll wait a few weeks before closing in case others on the team think differently.

**Comment by jeffwidman** [comment]
Circling back on this, I still think it's a valid problem, but we're unlikely to every tackle it, especially withe the workaround of re-opening old closed PR's and then re-using those (although you'd have to rebase / rebuild each time except for the final one).
