### ISSUE TITLE
release cycle

### ISSUE THREAD

**Issue by THETCR** [dependabot/dependabot-core#6670]
The libraries haven't been released under a new version for a while now.
Is the release cycle changed deliberately or is there something blocking it?

**Comment by deivid-rodriguez** [comment]
Hi @THETCR!

Recently we started using a new workflow internally that allows to deploy changes faster to the GitHub service without having to release gems explicitly to rubygems.org. Because of this, our release cycle to rubygems.org has become slower. I assume that's what you're asking about, right? We do plan to release a new version soon, and to make releasing to rubygems.org more frequent in general, most likely with some regular cadence. We'll let you know once we have something more concrete in place!

**Comment by melotte25** [comment]
Hi @deivid-rodriguez. I'll echo @THETCR's comments, and to answer your question: yes, talking specifically about releases to rubygems.org.

The 0.215.0 release from Dec 7 is pretty long in the tooth and some of my projects that don't use the GitHub service are "stuck" until a new release is put out to rubygems.

I appreciate the update and am appreciative of the team. If this lapse of deployment to rubygems in the short term means long term benefits, I'll take it!

**Comment by yeikel** [comment]
> Hi @THETCR!
> 
> Recently we started using a new workflow internally that allows to deploy changes faster to the GitHub service without having to release gems explicitly to rubygems.org. Because of this, our release cycle to rubygems.org has become slower. I assume that's what you're asking about, right? We do plan to release a new version soon, and to make releasing to rubygems.org more frequent in general, most likely with some regular cadence. We'll let you know once we have something more concrete in place!

Would it be possible to share some insights about this workflow you're referring to? Or is that private/secret information?

I am currently consuming the [dependabot core docker image ](https://hub.docker.com/r/dependabot/dependabot-core/tags ) while still using the code directly. I do not consume the published gems

As a side note, the latest tag of this image was published about a month ago, but the latest tag is from over 3 months

**Comment by deivid-rodriguez** [comment]
We consume the built images directly, without needing to publish any gems to rubygems.org. So, yeah, that's a good idea if you don't want to depend on rubygems.org releases :)

The reason that image is out of date is because we have switched to building ecosystem specific images, to avoid having to maintain a giant monolithic image. The newer images are  [here](https://github.com/orgs/dependabot/packages?repo_name=dependabot-core).

**Comment by andrcuns** [comment]
@deivid-rodriguez Do You somehow manage breaking changes between the code and all the built images? Before, the big monolithic image followed the same release cycle which doesn't seem to be the case anymore.

I was usually updating both the docker image and the gems together before. I wonder what would be the better approach now to not run in to situation where ruby code might not be compatible with one of the images (or you just make sure that all changes to docker images are backwards compatible?)

**Comment by deivid-rodriguez** [comment]
We don't make such backwards compatibility considerations at this stage. The idea is to have a regular release cadence so we can do with you did before and update images and code at the same time.

**Comment by yeikel** [comment]
> We consume the built images directly, without needing to publish any gems to rubygems.org. So, yeah, that's a good idea if you don't want to depend on rubygems.org releases :)
> 
> The reason that image is out of date is because we have switched to building ecosystem specific images, to avoid having to maintain a giant monolithic image. The newer images are [here](https://github.com/orgs/dependabot/packages?repo_name=dependabot-core).

Do you have any example combining more than one ecosystem in one image? The previous setup worked really well for us and now it seems that we'll need to manage each one separately :/

**Comment by deivid-rodriguez** [comment]
No, I don't, sorry. When you come up with something feel free to share it with the rest of the community!

**Comment by THETCR** [comment]
Hi @deivid-rodriguez ,

A solution would've been easily implemented by end-users if `Dependabot` supported updating `gems` that are directly sourced from `git` repositories.
Sadly it seems this is not supported (yet).

**Comment by THETCR** [comment]
@deivid-rodriguez 
I opened an issue for it (#6816 )

**Comment by jeffwidman** [comment]
I spent some time thinking about ways we could improve this, and wrote up a tracking ticket here:
* https://github.com/dependabot/dependabot-core/issues/7132

It has a bunch of notes, which seemed best as the first "first" post in an issue, so that's why I created a new ticket rather than tracking it here. So I'm going to close this one in favor of that... 

It also highlights a few decisions we need to make, so I/we would appreciate input from the community if there's bits you have an opinion on.
