### ISSUE TITLE
shows 'Dependabot version updates aren't configured yet' even when it is configured

### ISSUE THREAD

**Issue by DamienCassou** [dependabot/dependabot-core#6701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

https://github.com/foretagsplatsen/yaem/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I see "Dependabot version updates aren't configured yet" but the dependabot.yml is there. Trying to create the dependabot.yml file with the "Configure" button shows my dependabot.yml file.

![image](https://user-images.githubusercontent.com/217543/220309913-4ec15d95-71ef-4c9e-a69d-b83cea821690.png)

I was expecting to see the log of dependabot updates.

**Comment by jeffwidman** [comment]
This is because your config file has validation issues: https://github.com/foretagsplatsen/yaem/runs/11486196996

Unfortunately, due to some technical reasons that we're slowly working on fixing, the validation check only runs _after_ the file lands on the default branch (in this case `main`). So after you fix and merge, then look at the next run to validate that it actually passed.

More details:
* https://github.com/dependabot/dependabot-core/issues/4605

**Comment by DamienCassou** [comment]
Thank you very much for your help @jeffwidman, the bug is now fixed.

Something else you might want to consider improving is showing validation errors more prominently. I wouldn't have bothered you if I had seen the error messages.

**Comment by jeffwidman** [comment]
Agreed, tracked in #4605 as mentioned above...
