### ISSUE TITLE
Another missing Maven Plugin version upgrade

### ISSUE THREAD

**Issue by vorburger** [dependabot/dependabot-core#675]
Further to #671 (BTW thanks again for this; I got LOTS of new PRs due to that today!), I thought it was curious that you found https://github.com/vorburger/ch.vorburger.exec/pull/12/files but missed https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-pom-lite/pom.xml#L99 (no PR raised for that yet) - or is that just queued and about to come?

**Comment by vorburger** [comment]
@greysteil

**Comment by greysteil** [comment]
Just took a look into this, and it's because of the way that `mariaBD4j-pom-lite` is included in the top-level POM:
- It's included as a [parent](https://github.com/vorburger/MariaDB4j/blob/master/pom.xml#L4-L11) rather than a [module](https://github.com/vorburger/MariaDB4j/blob/master/pom.xml#L27-L39)
- As a result, Dependabot *doesn't* update the versions in it

The thinking behind the above is that when you add a project to Dependabot you might only want to add some of its subprojects. If Dependabot went up the tree and updated versions in the parent file, too, then in some (most?) cases that would be unexpected.

A workaround for the above would be to add a second update config in Dependabot (under "add project") with the directory as `mariaBD4j-pom-lite` - you'd then get separate PRs for updates to that file.

Does the above make sense to you? Seems like it's not perfect in this case - is there any way Dependabot could have automatically detected that?

**Comment by infin8x** [comment]
Closing this due to age and inactivity. If this scenario is critical to your workflow please feel free to comment.
