### ISSUE TITLE
Go: support the Go vulnerability database/service

### ISSUE THREAD

**Issue by daenney** [dependabot/dependabot-core#6800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The Go team maintains a (new) vulnerability database and service, as explained in https://go.dev/blog/vuln. Contrary to many other SAST tools which purely look at dependencies, the vulnerability DB and the govulncheck utility understand if the vulnerable code path is every (transitively) called by your program (for any modules the Go proxy is aware of).

This makes the alerts much more actionable and purposeful by not simply triggering on whether a vulnerability exists in a version, but if the vulnerability is reachable from your code.

It would be great if Dependabot checked with this database.

**Comment by jeffwidman** [comment]
This repo is about the code that creates PR's to bump versions--whether from cron or from security alerts--but not about the security alerts themselves. Versus this issue is about the alerts themselves, not the resulting PRs.

So I'm afraid I'll have to close this.

I suggest starting a discussion over in https://github.com/community/community/discussions/categories/code-security as that's probably the best way to reach the team that handles alerts. Feel free to drop a breadcrumb link on this issue to the discussion.

I do know that team is already aware of the `go` vulnerability work, as I was one of the folks who internally notified them when it first shipped, although I haven't been involved further.
