### ISSUE TITLE
Surface what dependencies are added/removed in the new version

### ISSUE THREAD

**Issue by tim-schilling** [dependabot/dependabot-core#6819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Many library maintainers like to limit the number of dependencies they have. However, in some cases it makes sense to add the dependencies. Such as Python's [Hatch adding a dependency](https://github.com/pypa/hatch/pull/762) to Python's [Trove Classifiers](https://github.com/pypa/trove-classifiers).

While Dependabot has no place in determining what dependencies are added, it can help improve the security of the programming ecosystem by surfacing what dependencies have been added/removed in a version change for a library. This type of information can help maintainers decide whether or not to continue to use a dependency.

**Comment by yeikel** [comment]
This might be easy to implement for ecosystems that use lock files like npm as comparing both lock files should give a diff of the newly introduced dependencies. 

For others, it would need to resolve all the dependencies and that's likely hard to do securely. For Maven, for example, it would need to resolve the pom using something like `dependency:tree`  

How do you envision building this?

**Comment by jeffwidman** [comment]
It's an interesting idea, but I think that's the responsibility of the underlying library to have a solid changelog/commit history.

We want to keep Dependabot focus on the glue code... ie, we connect to the repo, hook up the native package manager, takes its diff, fetch the changelog, and then roll both together into a PR. That alone is more work than we can handle, esp as we look to build out support for more ecosystems.

I don't think we want to get into the business of being opinionated on what should show up in the changelog... because that library maintainer knows better than we do whether that's truly worth surfacing to a user.

Perhaps waayyyy down the road we might take another look at this, but not in the foreseeable future.
