### ISSUE TITLE
Dependabot stuck on Checking now

### ISSUE THREAD

**Issue by morenol** [dependabot/dependabot-core#6835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

rust

### What you expected to see, versus what you actually saw

I expect that dependabot should run and create PRs as usual.

<img width="933" alt="Screenshot 2023-03-14 at 3 30 43 PM" src="https://user-images.githubusercontent.com/22335041/225116476-6d88e042-d82f-4d87-9667-cf6e3df2818f.png">

For npm and github actions it run without problems

This is in a private repo

**Comment by jeffwidman** [comment]
It's unclear if this is a problem with our service infra, or a local problem with your repo + Dependabot.

What happens if you try to run [the `dry-run` script](https://github.com/dependabot/dependabot-core#running-with-docker) against this repo? If it completely successfully, then this is a service infra problem, and we'll need you to file a support ticket pointing to your repo so we can debug better.

But in many cases, this is actually a repo-level problem, and `dependabot-core` isn't exposing the error or short-circuiting the timeout appropriately. So it'd be helpful if you can run the dry-run script to help differentiate.

**Comment by morenol** [comment]
How can I run the `dry-run` script in a private repo? how to use my credentials with it?

**Comment by jeffwidman** [comment]
https://github.com/dependabot/dependabot-core/blob/6c0e30514c92c336dcca9715ee387ea3a35a50fd/bin/dry-run.rb#L129-L136

Read through the script config options further down that file for more info... if you run it without args it'll also spit out a help menu.

**Comment by morenol** [comment]
I tried it and had success. Where can I fill a ticket for a private repo?

**Comment by jeffwidman** [comment]
https://support.github.com/request

For other users, please only file support issues for stuff that's truly account-specific... otherwise we try to debug here in public so that other users can provide potential workarounds, and also provides a form of documentation to later users trying to figure out their issues.

I'm going to close here in the public repo since this is moving to private support thread.
