### ISSUE TITLE
Squash workflow for all your changes

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6899]
Hey there, 

I was wondering if you ever considered using the squash workflow (instead of merge) for `main`

The current `main` is quite messy as not all pull requests are following the same workflow. Some are using `merge`, and some are using `squash` 

As someone that watches the project closely, the current mix makes it confusing and harder to follow

A squash workflow would be considerably cleaner and many projects are adopting this workflow. Examples: 

https://github.com/apache/maven
https://github.com/apache/spark/commits/master

And many others

**Comment by abdulapopoola** [comment]
Thanks, that is a great suggestion @yeikel . @jeffwidman and @deivid-rodriguez what are your thoughts?

**Comment by jeffwidman** [comment]
Good question.

I tried to address this a bit more in a recent PR to the Contributing doc:
https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#how-to-structure-your-git-commits 

Personally, while I _generally_ merge via squash, I'm not a fan of requiring _always_ squash workflow, because commits and PR's are two distinct "types" of units of work... while I prefer small single-commit PR's, there _are_ times that a PR benefits from multiple commits, where each of the commits is a logical changeset from a reviewer / `git blame` perspective, but may not actually pass CI... that's why having merge commits is useful to not break `git bisect`. https://github.com/dependabot/dependabot-core/pull/6996 is a great example. 

We used to merge multiple-commit-PR's via rebase (unless it would break CI/`git bisect`) until @deivid-rodriguez pointed out to me that using merge via merge created a commit linking to the accompanying PR, whereas rebase it was harder to track down. So we've kinda gone for a Squash-if-appropriate-otherwise-use-a-merge-commit workflow.

That said, commit logs can easily get out of hand / noisy if you're not careful. And as my teammates can attest, I have privately gotten after them if they start putting up useless commit messages/not carefully ordered.

But looking at recent commit history it looks pretty reasonable to me: https://github.com/dependabot/dependabot-core/commits/main

At some point, as we grow, we may need to require a specific process, but for now I'd rather empower folks to use their judgement and not force a process until we actually need to...

**Comment by jeffwidman** [comment]
Closing, as I think this answers the question and summarizes what @deivid-rodriguez and I have discussed previously, but happy to re-open if I'm overlooking something or if this becomes a problem down the road.

**Comment by yeikel** [comment]
I am just adding a few notes because generally you know what's best for the project and the idea is not to argue

> Personally, while I _generally_ merge via squash, I'm not a fan of requiring _always_ squash workflow, because commits and PR's are two distinct "types" of units of work... while I prefer small single-commit PR's, there _are_ times that a PR benefits from multiple commits, where each of the commits is a logical changeset from a reviewer / `git blame` perspective, but may not actually pass CI... that's why having merge commits is useful to not break `git bisect`. #6996 is a great example.

While using `squash`, a `bisect` will return the pull request that introduced the issue, but it is true that it won't be able to point out the exact commit that did it when the pull request contains multiple small commits. 

The challenge with pull request with multiple small commits, is that for the cases of issues, it'll be tricky to decide what to revert (as opposed to reverting the entire pull request) and more so if the changes are related one way or another

If the smaller commits are truly independent, I'd argue that it is an example of bundling multiple changes together. I'd be curious to hear an example where this is not the case

> We used to merge multiple-commit-PR's via rebase (unless it would break CI/`git bisect`) until @deivid-rodriguez pointed out to me that using merge via merge created a commit linking to the accompanying PR, whereas rebase it was harder to track down. So we've kinda gone for a Squash-if-appropriate-otherwise-use-a-merge-commit workflow.

Squash(from the Github UI) includes the pull request title and the pull request number automatically minus the individual commits and the explicit merge commit message

**Comment by jeffwidman** [comment]
To clarify, for the above sections, I was referring to "merge-via-rebase" vs "merge-via-merge"... Merge-via-squash is preferred whenever possible, and keeping one-commit-per-PR is too.

I was more thinking of logical changesets that are mentally distinct, but both have to land in order to not break CI...

I do get your point though--sometimes I see folks do a refactor commit or two before their main commit in a PR, and while I support them pulling those out as a separate commits, ideally those would actually be separate PR's entirely...

**Comment by jeffwidman** [comment]
I think this really comes back to let's go with what we've got for now, as generally I don't think allow a "merge-via-merge" is adding too much noise to the changelog... what's noisy is the pure volume of commits, and "how" we merge won't solve that... that's more a question of "are folks doing too small of commits" or "commits that aren't well-worded" which IMO we're doing okay on right now...

Re: keeping up with the project w/o overwhelmed by noise... for that it'd be better if we had regularly releases with a published changelog... that's actually work planned for this coming few months, so that should help
