### ISSUE TITLE
Question: Is it possible to use updater library to build a bot

### ISSUE THREAD

**Issue by noorul** [dependabot/dependabot-core#6900]
We are using dependabot but it looks like the dependabot bot code is not publicly available. In order build something similar is it possible to use the updater library? It looks like the updater is talking to an internal service. Or is there any other easy way to automate what dependabot is doing on Github?

**Comment by yeikel** [comment]
See https://github.com/dependabot/dependabot-script

**Comment by noorul** [comment]
@yeikel I already looked into it. I should have mentioned that. But it is very simple. For example it does not have the logic of handing cases like removing already raised PR which is not merged but a higher version is detected.

**Comment by noorul** [comment]
I was specifically looking for the logic in https://github.com/dependabot/dependabot-core/tree/main/updater

**Comment by yeikel** [comment]
That is just a sample and you'd need to adapt it for your needs. 

For example, to close existing pull requests you would need to 

1. Search for existing pull requests matching current dependency
2. Close them 

You can initialize a github client using 


```ruby
github_client = Dependabot::Clients::GithubWithRetries.for_source(
  source: source,
  credentials: credentials
)


```

And then you can search using

```ruby

``  existing_pull_requests = github_client.search_issues(
    "is:pr state:open repo:#{PROJECT_PATH} #{search_query}"
  ).items
```

**Comment by jeffwidman** [comment]
The code in `/updater` is specific to the :dependabot: service at GitHub, and does talk to an internal service API. That code is private and unlikely to be open sourced anytime soon... and to be frank, even open sourcing it wouldn't do much as it talks to GitHub using internal communication methods that aren't accessible from external networks.

As @yeikel pointed out, `dependabot-script` or https://github.com/dependabot/cli are your best bets here, although the latter is still a bit primitive because we haven't added actual PR creation to it yet (we're still noodling on what we plan to do with it).
