### ISSUE TITLE
Question: Is there a way to build a single container with all the package ecosystem?

### ISSUE THREAD

**Issue by noorul** [dependabot/dependabot-core#6943]
Recently there was a change to move to independent containers for each package ecosystem. I have a requirement to have them as a single container. Does this project publish one or is there a way to achieve it?

**Comment by yeikel** [comment]
As far as I understand, the only way would be to build your container learning from the existing package-specific containers. The obvious downside of doing this is that you'll be on your own

I suggest you migrate to the independent containers and find a way to fit them within your requirements

**Comment by noorul** [comment]
@yeikel That is one way to solve this issue.

**Comment by jeffwidman** [comment]
Sorry, we're not planning to publish a monolith image anytime in the foreseeable future. Most of our users want only one or at most a couple of ecosystems, and we also want to move towards more pluggability / platform model, so maintaining a single image doesn't make sense.

You are obviously welcome to build your own custom one on top, and if you open source it, feel free to drop a breadcrumb link here so that others can find it. 

I rewrote the README recently and added a diagram of how the docker images fit together, you may find it useful if you try to build something yourself:
https://github.com/dependabot/dependabot-core#building-images-from-scratch

**Comment by noorul** [comment]
@jeffwidman I understand, thank you!
