### ISSUE TITLE
Dependabot doesn't run & says it's not configured even though it is

### ISSUE THREAD

**Issue by n1ckoates** [dependabot/dependabot-core#7026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

https://github.com/n1ckoates/blog/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

In every repository that I have Dependabot configured (`n1ckoates/quoter`, `n1ckoates/perhaps`, `n1ckoates/blog`), Dependabot does not run and shows a message saying it isn't configured in settings. Apart from the last repo, all of them previously had working Dependabot. I've tried re-pushing the default Dependabot config file, but that didn't do anything, and didn't even show the config check GitHub action.

Notably, this issue seems to have popped up right after I changed my GitHub username around a week ago, as I haven't received any PRs from Dependabot since then.

![image](https://user-images.githubusercontent.com/58091943/230695305-c8069ce1-1d95-444f-b6ec-a6b21b3c44d5.png)

**Comment by yeikel** [comment]
Did you enable dependabot from the Service settings? 

https://github.com/n1ckoates/blog/settings/security_analysis

![image](https://user-images.githubusercontent.com/8935151/230704535-2ebf96ac-06a6-4f87-9268-2c6f1a2afcae.png)

After doing so, you can go to  

https://github.com/n1ckoates/blog/network/updates and you should see something like : 

![image](https://user-images.githubusercontent.com/8935151/230704577-17fc5dc7-76f7-422a-b082-1860e8589dea.png)

I also noticed that you're using [lockfile v3 for NPM](https://github.com/yeikel/blog/blob/main/package-lock.json#L4). As far as I understand, the support for that is in early stages as we're still targeting [npm 8](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/Dockerfile#L12) and lockfile v3 was introduced with NPM 9

Can you downgrade to lockfile v2 and retry?

**Comment by yeikel** [comment]
I can confirm that downgrading to lockfile v2 fixed it. 

See https://github.com/yeikel/blog/commit/b737b2df4310a3f1ee724bc08333b3c3919142d0

```shell
C:\Users\Yeikel>npm --version
8.19.3

rm  package-lock.json
npm install
```

Note that I had to download a dependency manually https://github.com/yeikel/blog/commit/c9cc4ab69d1115f39c95fb41d7f59b80ce0921ce

Because your repository is already up to date

Example pull request : https://github.com/yeikel/blog/pull/1

**Comment by n1ckoates** [comment]
Unfortunately, neither of those fixes worked for me.

I checked `settings/security_analysis` on all three repositories, and they already had version updates enabled. `perhaps` *didn't* have Dependabot alerts or security updates enabled, but I'm not sure if that matters as version updates were still turned on.

I tried downgrading lockfile v2 on `blog` and then downgraded a dependency (as you did), but this didn't seem to change anything. Quoter & Perhaps were already using lockfile v2, as they are older repositories.

**Comment by jeffwidman** [comment]
The "not configured yet" indicates it's not even triggering the Dependabot job. Whereas the lockfile v3 issue would manifest later in the job logs, probably as a "unable to find" or "unable to parse" manifest file.

Version updates should work regardless of alerts/security updates, all you should need to do is push the `dependabot.yml` file and it should start working.

I've stuck this on our internal board for further investigation, but it probably won't get looked at til this coming week sometime.

Also, this is almost certainly something specific to this particular user, so for anyone else hitting this issue, please file a new issue rather than tagging onto this ticket.

**Comment by jeffwidman** [comment]
Also, many, many thanks @yeikel for chiming in!

**Comment by yeikel** [comment]
I noticed that Github UI is not great because even after enabling it you will see that "Dependabot is not enabled". It takes at least a page refresh to update the message and that can be confusing. 

Also for this example, it seems that v3 is also working fine : https://github.com/yeikel/blog/pulls

But I still think that sticking to v2 for now is better

**Comment by jakecoffman** [comment]
@n1ckoates I can see in the Dependabot DB the old account is deactivated, but there's no entry for the new account so I can't force a sync for it.

Can you try turning Dependabot Security Updates off and on again for one repo? That should emit the event that Dependabot needs to install or it will give us a fresh error in the logs to find. Let me know when you complete this and I can take another look.

**Comment by jakecoffman** [comment]
That didn't seem to do it. Let's try one more thing, try committing a newline or other change to the dependabot.yml in the default branch.

**Comment by n1ckoates** [comment]
I [removed](https://github.com/n1ckoates/blog/commit/044359d51ae8f5268a99afade5f333c6159f1966) a comment from `dependabot.yml`.

**Comment by jakecoffman** [comment]
That didn't do it, I'll keep looking into it. Thanks for your patience.

**Comment by n1ckoates** [comment]
Just checking if there's any update on this @jakecoffman 

Thanks!

**Comment by jakecoffman** [comment]
I tried to recreate what you did: I made a new user, setup Dependabot on a repo, and then renamed my user. But it all just worked. I'm not entirely sure what has gone wrong here. 

Have you noticed anything strange in other GitHub products? Web-hooks not firing, etc?

**Comment by n1ckoates** [comment]
I haven't noticed anything else in other products; just tested a webhook I previously had setup and the event fired as expected.

This is a really weird issue.

**Comment by jakecoffman** [comment]
@n1ckoates it looks like your account is now setup properly in the Dependabot database. Can you try touching the `dependabot.yml` again to see if that picks it up?

**Comment by n1ckoates** [comment]
I can confirm it's working! I made a change to the config file, and it immediately picked it up and started checking for updates.

Thanks so much for your help.
