### ISSUE TITLE
Maven hard `[<version>]` requirement should be followed

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#7092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Package manager version

Any

### Language version

Any

### dependabot.yml content

```yml

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

```

### What you expected to see, versus what you actually saw

What I saw

```diff

diff --git a/pom.xml b/pom.xml
index b28d27c..6849233 100644
--- a/pom.xml
+++ b/pom.xml
@@ -45,7 +45,7 @@
         <dependency>
         <groupId>org.springframework</groupId>
         <artifactId>spring-context</artifactId>
-        <version>[6.0.5]</version>
+        <version>[6.0.8]</version>
     </dependency>
 
       <dependency>

```

What should happen: 

When versions are declared using `[version]` in Maven, that means that it is a hard requirement on that version. Dependabot should not try to update these dependencies

Documentation https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges 

Pull request:
* https://github.com/yeikel/dependabot-playground/pull/62

### Smallest manifest that reproduces the issue

```xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.test</groupId>
  <artifactId>test</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>demo</name>

  <dependencies>
   <groupId>org.springframework</groupId>
   <artifactId>spring-context</artifactId>
  <version>[6.0.5]</version>
  </dependencies>
 
</project>
```

**Comment by yeikel** [comment]
This is similar to #4276 but in Maven

**Comment by yeikel** [comment]
@jeffwidman @deivid-rodriguez 

This could also be seen as a feature request, and I am open to reword/change the issue type if that makes more sense

**Comment by deivid-rodriguez** [comment]
Can you elaborate a bit more on why these requirements should not be bumped?

I think this is different from #4276 because in the case of #4276 there's no numeric version involved, so a PR will never be created anyways since there's nothing to bump.

**Comment by yeikel** [comment]
> Can you elaborate a bit more on why these requirements should not be bumped?
> 
> I think this is different from #4276 because in the case of #4276 there's no numeric version involved, so a PR will never be created anyways since there's nothing to bump.

They should not be bumped because the user explicitly configured maven to force that specific version. If you bump it, it would go against what the user configured in the build

**Comment by deivid-rodriguez** [comment]
In other ecosystems, as far as I recall, we generally bump explicitly pinned dependencies too, because even if the user is explicitly choosing a specific version, we don't expect pins to stay there forever, so Dependabot can help eventually bumping them.

But since in Maven there's this concept of "suggested pin" vs "forced pin", I guess it's sensible to ignore "forced pins".

**Comment by yeikel** [comment]
> In other ecosystems, as far as I recall, we generally bump explicitly pinned dependencies too, because even if the user is explicitly choosing a specific version, we don't expect pins to stay there forever, so Dependabot can help eventually bumping them.
> 
> But since in Maven there's this concept of "suggested pin" vs "forced pin", I guess it's sensible to ignore "forced pins". 

To be fair, I have never seen this explicitly set before. I imagine that the usage is low and for very specific reasons

**Comment by deivid-rodriguez** [comment]
Oh, interesting! What prompted you to create this issue and PR then? Is it that you just noticed this from reading the code?

**Comment by jeffwidman** [comment]
I personally think we should *not* skip opening a PR for a "forced pin".

I get that it's forced by the user, but the whole point of Dependabot is to be a convenient option for the user, whenever they are ready to bump that dependency. For example, I know there are times I've explicitly pinned something in some ecosystems knowing that the next few versions are going to be incompatible releases, but I want to continue to be notified of new releases via a Dependabot PR... and I kept reading the release notes to see if it'd fixed my issue. 

IF they don't want :dependabot: to open a PR bumping that dep, then they can ignore that particular dependency. That's kinda why we have the whole concept of ignores...

**Comment by jeffwidman** [comment]
I also think this would be confusing behavior to most users... as most are going to be more familiar with the model of "I pinned, therefore Dependabot will come along and bump the pin" and won't be familiar with the nuance of user pin vs user hard/forced pin (which I still argue will never practically be truly a forever hard/forced pin)...

That said, rather than closing, we could leave this issue open for a year and see how much interest it garners from others? If we get consistent feedback on it, then could merge, if not then don't.

**Comment by yeikel** [comment]
> Oh, interesting! What prompted you to create this issue and PR then? Is it that you just noticed this from reading the code?

A combination of things. I wanted to test what would happen if we used that pattern, and also because I used that pattern a few years ago. 

> IF they don't want :dependabot: to open a PR bumping that dep, then they can ignore that particular dependency. That's kinda why we have the whole concept of ignores...

Fair enough, in that case, this feature is not needed given that the ignore feature is in place

From what I understand, pinning a version is not common in the Maven ecosystem. In fact, that syntax is buried deep in the documentation and I only found a couple of examples [after searching for it
](https://github.com/search?q=%2F%3Cversion%3E%5C%5B%5Ba-zA-Z0-9%5D%2B%5C%5D%3C%5C%2Fversion%3E%2F+language%3A%22Maven+POM%22&type=code)
In case it helps, the only time I had to do this is when we added a dependency that had a license change. For that specific example, we were not expecting to upgrade that dependency again due to that constraint and if dependabot were to create  any pull request it would be noise. 

 I do not know how common this is and as @jeffwidman mentioned, users could use the ignore pattern.

**Comment by jeffwidman** [comment]
Sounds good thanks for being open to a conversation about it. Let's float this for a while and see if it comes up for anyone else and if not can close it a ways down the road.

Also, long term we want to move to using native Maven if possible, in which case this issue would be moot because we'd defer to its behavior... one less decision for us to impose on the ecosystem users. I have a sneaking suspicion it would honor this syntax and refuse to ever return a version bump. 😁

**Comment by deivid-rodriguez** [comment]
I think we can close this, to be honest. I also just noticed that this has been an intentional feature for This has been an intentional feature for [5 years](https://github.com/yeikel/dependabot-core/commit/dcb42a61a7229742b1723ae49aefe6f2d93d67f5), and we don't recall of any complaints. If @yeikel has not been bothered by it either and the issue/PR was just the result of testing/experimentation, I think we can move on.
