### ISSUE TITLE
support `usePreemptive` for maven repositories requiring authentication

### ISSUE THREAD

**Issue by mdering** [dependabot/dependabot-core#7116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello,
We use a provider (fury) for managing private packages in maven which requires the option `usePreemptive` to be true in the repository configuration. The provider documentation states:

> The `usePreemptive` setting is required to authenticate into your private Maven repository. Without it, you will only be able to access your public packages.

As such dependabot is unable to help us update our private packages, only the public ones. It would be great if dependabot could support this option so we can use it to manage all of our packages, not just the public ones.
Thanks!

**Comment by yeikel** [comment]
I have limited understanding about this topic, but after a quick search, it seems that this parameter is only needed if you use Maven directly

dependabot does not use maven directly (at least for now) and it just authenticates to the repositories like any other web client. 

What happens when you configure [the private registry ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries) and set the values like to fury documentation expects? (user should be your token and password NOPASS)

```yml
registries:
  private_registry: 
    type: maven-registry
    url: yourfuryregistry
    username: ${{secrets.FURY_TOKEN}}
    password: NOPASS
```
