### ISSUE TITLE
Publish the Dependabot ruby gems more frequently (weekly??)

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#7132]
### Code improvement description

This ticket is a planning/tracking ticket for publishing the Dependabot gems more frequently to RubyGems.

### Context:
We used to publish releases about once a week, which were then deployed to the GitHub Dependabot service. A few months ago, we switched to deploying straight from PR's to the GitHub service... this allowed us to test code live in production before merging to `main`, ensuring that released code has already been validated in production.

However, because we no longer had a forcing function for publishing the gems to RubyGems, we never got around to it... and several months passed between releases. 

We want to get back to a regular publishing cadence, as we've got many users who use the `dependabot-core` library outside of the GitHub service, and they are some of our most active contributors.

### Plan:
In order to do this, we need to streamline the release process so it requires less maintainer time.

My current thought is the following:
1. Streamline the script for bumping the PR versions. Today it has some unnecessary complexity making it brittle (https://github.com/dependabot/dependabot-core/issues/5777).
2. Have a GitHub action that leverages this script to automate opening a PR to bump the version. This could happen on the cadence we plan to cut the releases, or it could open the next one as soon as the previous one is merged.
3. Switch the release notes from a Changelog text file to using GitHub releases. Otherwise we have a race condition where if another PR gets merged before the version bump PR, it won't be included in the changelog...
4. When a maintainer is ready, they merge the version bump PR, then tag the release using GitHub releases.
5. A GitHub action watches for new tags and pushes them to RubyGems. (this already happens today)

#### Edge cases:
* Need to cut an emergency release: A human can either run the script for bumping versions, or run the github action that normally runs on cron.
* Want a major version bump: we'd probably just do this manually.

### Decisions:
* What frequency to release? I think weekly is probably about right, but anywhere from daily to monthly could work. We're open to input from the community.
* What versioning scheme to use? Calver, semver, or a hybrid? We're open to input, but we also have some internal constraints related to the Dependabot service at GitHub that aren't fully visible that may influence the outcome here.
* Do we fully automate cutting releases, or should we keep a human involved with merging the version bump PR and double-checking the changelog? This influences the versioning conversation.

### Other notes:
* If we stick with full semver, then probably we'd need the github action in 2️⃣ above to take an input arg of "major/minor/patch" and a human would need to trigger it.
* I think we'll be more successful with keeping to a regular cadence if the process is either entirely automated, or if the version bump PR shows up via Cron as a reminder for the maintainer who's currently taking the first-responder shift to cut a new release.
* The release process we follow in `fetch-metadata` is a good example of how we could further simplify things... especially once https://github.com/dependabot/fetch-metadata/pull/347 lands. Essentially it's "run `bump-version.rb`, get PR merged, tag the release"... but even that may feel too onerous if we're trying to do it weekly. My guess is we'll either release less frequently, or end up automating more.

**Comment by jeffwidman** [comment]
We don't have to figure this out entirely up front... baby steps is the way to go, and probably the first baby step is switching from a flat Changelog file to GitHub releases.

This way we no longer have to merge the version bump PR as soon as it gets created, which unlocks a bunch of other potential simplifications and automations.

**Comment by yeikel** [comment]
I am one of the users who asked about this, and I'd like to add that I think that it is no longer needed 

The reason that I asked for  a quicker release cycle is because releases used to include a release of the docker image you used to publish with all the native packages in one

My understanding is that you're publishing a new image of the ecosystem images with every build of the main branch and that the tags are no longer associated with the images

If that understanding is correct, I no longer need to tie my releases to your releases because I can simply track the images separately and pin my build to a given sha from main

Please let me know if I am misunderstanding anything

**Comment by Skenvy** [comment]
## A workflow suggestion to minimise manual intervention.
If it's decided to swap from a changelog to GH releases, _with automatic release notes_, that could, instead of being the **trigger** for the [current gem release workflow](https://github.com/dependabot/dependabot-core/blob/3d599419cd538a34bb7606872dbd46befee4f50b/.github/workflows/gems.yml), be added as a parallel job to the gem releasing. Assuming the source of truth for the most recently released version remains [this file](https://github.com/dependabot/dependabot-core/blob/3d599419cd538a34bb7606872dbd46befee4f50b/common/lib/dependabot.rb)

Simply convert the release workflow's trigger to;
```yaml
on:
  push:
    branches:
    - 'main'
    paths:
    - 'common/lib/dependabot.rb'
```

Then have a job that determines if the value of the version in that source of truth file already has an existing tag (an edge case if re-running, or a change has been made to that file that didn't update the version value). [Something like my example](https://github.com/Skenvy/dependabot-linguist/blob/298a80f56b78282872a00b98453c894dd56d8c40/.github/workflows/build.yaml#L41-L48).

Then you could [condtionally gate](https://github.com/Skenvy/dependabot-linguist/blob/298a80f56b78282872a00b98453c894dd56d8c40/.github/workflows/build.yaml#L49-L52) (the [_if_](https://github.com/Skenvy/dependabot-linguist/blob/298a80f56b78282872a00b98453c894dd56d8c40/.github/workflows/build.yaml#L57-L58)) the automatic [gh release ...](https://github.com/Skenvy/dependabot-linguist/blob/298a80f56b78282872a00b98453c894dd56d8c40/.github/workflows/build.yaml#L96-L97).

Assuming the manual task of tagging is supposed to be `1:1` with the merge that updates the version, the same condition would gate the gem releasing as a down stream result of the release being possible, so the job that releases the gems could branch off the same conditional check and use the same workflow triggering condition as the automatic release, so be a parallel job in the same workflow.

Then the only questions are around what mechanism you'd want to trigger the PR / merge of the update to the version.

**Comment by jeffwidman** [comment]
Thanks for the feedback @yeikel appreciate you clarifying.

Some of our users use the docker images, some use the ruby libraries. We want to offer both, using a regular/frequent release cadence.
Step 1 is automate all the drudgery we currently have around releases, but (at least for now) keep a human involved for the actual release approval... but should take no more than 5 mins of our time per release.

After we improve this, we'd like to also improve the paved path for using the docker images, but baby steps...

**Comment by jeffwidman** [comment]
I've merged a bunch of improvements around this topic, and the flow is now much more streamlined:
https://github.com/dependabot/dependabot-core/blob/eb13f32aa454f94dff443f642a7ce83feec105f1/README.md#notes-for-project-maintainers

The only remaining step is triggering this via cron:
* https://github.com/dependabot/dependabot-core/pull/7325
