### ISSUE TITLE
Azure Devops/VSTS support

### ISSUE THREAD

**Issue by JamieMagee** [dependabot/dependabot-core#729]
I understand that this is a large feature, but I believe the work done to make dependabot less GitHub specific (Bitbucket & Gitlab support) would make this a little bit easier.

Unfortunately there is no officially supported Ruby client, however VSTS does supply an [OpenAPI spec](https://github.com/MicrosoftDocs/vsts-rest-api-specs) from which you can generate a client SDK, as well as extensive [REST API docs](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1).

I am happy to contribute towards this goal, however I have limited Ruby experience.

**Comment by greysteil** [comment]
Hey @JamieMagee, thanks for the feedback.

There's an issue open [here](https://github.com/dependabot/feedback/issues/128) to track adding Azure DevOps support to Dependabot (the hosted service) but I'm going to keep this open here, too, because adding it to Dependabot Core shouldn't be too tricky, and would allow you to use Dependabot Script with Azure DevOps.

I'll take a look through the API docs in the next few days and get back to you with any questions. This shouldn't be *that* much work...

**Comment by greysteil** [comment]
FYI, I made the first step towards this today by adding support for Azure DevOps to `Dependabot::Source`. The next step is to do the FileFetcher, followed by the `PullRequestCreator`, followed by the `PullRequestUpdater`. None of those should be *that* difficult, and I plan to work on this in the evenings this week.

**Comment by JamieMagee** [comment]
Wow, thanks for the (very) quick update on this!

**Comment by Adamsimsy** [comment]
Hey i was wondering if anyone was able to make any progress on this? Would be awesome to get the integration with Azure DevOps.

**Comment by colbywhite** [comment]
@greysteil, any update on that Oct 30, 2018 work you mentioned? still a WIP or was that abandoned?

and more importantly, does the [acquisition by :octocat:](https://dependabot.com/blog/hello-github/) affect the priority on this and dependabot/dependabot-core#1153? 

fyi, i'm totally down to work on this. so if your branch is pushed somewhere i'd be happy to take a look and see how far i can take it.
