### ISSUE TITLE
Missing tagged releases of the `dependabot-core` image

### ISSUE THREAD

**Issue by Flexicon** [dependabot/dependabot-core#7368]
### Code improvement description

The newest versioned tag of [ghcr.io/dependabot/dependabot-core](https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-core) is still at `0.215.0`.

When will release `0.218.0` come for this image, if ever?
If never, is there an alternative image?

I ask because images such as [ghcr.io/dependabot/dependabot-updater-core](https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-updater-core) don't include specific package manager helpers such as `node`, `yarn`, `go`, etc.

Our usecase is, we're running our own version of dependabot in an internal Gitlab instance basing on the code in `dependabot-core` and so basing our own images on the `dependabot/dependabot-core` base image has been great until recently for ensuring we have all the required runtime dependencies pre-built.

**Comment by andrcuns** [comment]
I'm pretty sure it will never be released given the architecture of how images are built is completely different where there is no more `core` image which contains all native helpers.

I think there was already an issue like this but couldn't really find it anymore.

**Comment by Flexicon** [comment]
Interesting. Yeah I _thought_ that might be the case but I also couldn't find any existing/closed issue on the topic.

On that note, is there a specific reason why there isn't any `core` image which contains all native helpers anymore?

**Comment by andrcuns** [comment]
I don't know all the reasons behind it, that's probably better for members of dependabot team to answer, but from architectural point of view it makes total sense to not have to hog a huge image around all the time when you need to update `Docker` dependency that requires no native helpers for example.

>On that note, is there a specific reason why there isn't any core image which contains all native helpers anymore?

Since there are different dockerfiles per ecosystem, there is nothing to build the old core image from. You could probably "glue" instructions from all the files and build such an image yourself.

**Comment by jurre** [comment]
Yeah @andrcuns is right, we no longer use a single image for all ecosystems anymore, but instead use ecosystem specific images, these are published using sha's since we no longer do periodic releases on these, but instead run production against main. You can find the npm one [here](https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-updater-npm) for example.

There are a number of reasons we made this change, some of the context is documented [here](https://github.com/dependabot/dependabot-core/issues/946).

I'm going to close this issue out, but please feel free to ping me if you have follow-up questions.
