### ISSUE TITLE
Composer upgrades found but not applied

### ISSUE THREAD

**Issue by danepowell** [dependabot/dependabot-core#7379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

composer

### Package manager version

Composer 2

### Language version

PHP 8

### Manifest location and content before the Dependabot update

https://github.com/acquia/cli/blob/main/composer.json

### dependabot.yml content

https://github.com/acquia/cli/blob/main/.github/dependabot.yml

### Updated dependency

typhonius/acquia-php-sdk-v2

### What you expected to see, versus what you actually saw

I expected several dependencies, including symfony/flex and typhonius/acquia-php-sdk-v2, to be updated in the latest Dependabot run. In the run log, I see entries like this: `Updating typhonius/acquia-php-sdk-v2 from 3.0.8 to 3.0.9`

But then a PR is never actually opened to apply this update, and I see no other errors in the log indicating why a PR wasn't opened.

The acquia-php-sdk-v2 update has been available for two weeks, so it should have been applied in the weekly grouped update.

This problem only started after adding the grouped update configuration.

### Native package manager behavior

All packages are updated

### Images of the diff or a link to the PR, issue, or logs

Dependabot log: https://github.com/acquia/cli/network/updates/670475525

**Comment by danepowell** [comment]
I disabled grouped updates and immediately got an update PR ([logs](https://github.com/acquia/cli/network/updates/674226521)), so I think this is related to group updates.

Note that in the interim I manually upgraded the dependencies in the issue description.

**Comment by Nishnha** [comment]
This was fixed with https://github.com/dependabot/dependabot-core/pull/7358

I made a [fork](https://github.com/dark-dependabot/cli/) of acquia/cli and checked out the commit where grouped updates was first enabled. Now, with Dependabot enabled, I see that `typhonius/acquia-php-sdk-v2` is actually being updated from 3.0.8 to 3.0.9 in the grouped update PR: https://github.com/dark-dependabot/cli/pull/1/files#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5L6464
