### ISSUE TITLE
PR opened by dependabot does not show release notes properly

### ISSUE THREAD

**Issue by stinodego** [dependabot/dependabot-core#7386]
I work on the [Polars](https://github.com/pola-rs/polars) project. We use [Release Drafter](https://github.com/release-drafter/release-drafter) to auto-generate a changelog using the official GitHub releases feature.

The issue is that this changelog does not show up in the pull requests opened by Dependabot. For example:
* The [latest release](https://github.com/pola-rs/polars/releases/tag/py-0.18.0) (0.18.0)
* A [pull request](https://github.com/stinodego/python-cookiecutter/pull/26) opened by Dependabot for this release

What could be the cause of this? Is there anything we can do to make our changelog show up in the pull requests nicely?

**Comment by stinodego** [comment]
Hi @deivid-rodriguez , sorry for pinging you, but could you please let me know if there is anything we can do to make our release notes render nicely?

I am just wondering if this is a bug you need to fix, or whether there is some easy setting I need to enable / format I need to adhere to. I cannot find any documentation on this specific topic.

Thanks for your help!

**Comment by deivid-rodriguez** [comment]
Hei, not sure without investigating. I _guess_ this may be because releases for different libraries seem to live in the same repo, and use certain tag naming conventions Dependabot may not be aware of? 

Logic to find release notes lives here: https://github.com/dependabot/dependabot-core/blob/349bfa872b09cb221e777086d5b91284324c1974/common/lib/dependabot/metadata_finders/base/release_finder.rb.

Have a look at the README for instructions on how to get setup for local development and digging into this for yourself!

**Comment by stinodego** [comment]
Thanks for the pointers, I'll take a look!

**Comment by stinodego** [comment]
@deivid-rodriguez I'm not too familiar with Ruby and I can't immediately see what's wrong. Is there a way I can see debug logs of some sort for the PR generated by dependabot?

**Comment by deivid-rodriguez** [comment]
You can see some logs at "Insights > Dependency Graph > Dependabot", but not sure it will help here. You can run the CLI or the dry-run.rb script as explained in the README and add some logging yourself though!

**Comment by stinodego** [comment]
I just saw that Polars release notes show up properly now. Thanks for the fix!
