### ISSUE TITLE
Generates false vulnerabilities, or lies about branch(?)

### ISSUE THREAD

**Issue by d3x0r** [dependabot/dependabot-core#7504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Github

### Package manager version

none

### Language version

C99

### Manifest location and content before the Dependabot update

https://github.com/d3x0r/SACK/security/dependabot/4
Says that this file (which doesn't exist) is a vulerability
https://github.com/d3x0r/SACK/blob/master/src/netlib/html5.websocket/server/jquery-1.4.2.min.js

I don't know how it thinks it can see that file - it's been deleted for the last 3 alerts... I don't use that file anyway.

### dependabot.yml content

None

### Updated dependency

None

### What you expected to see, versus what you actually saw

I expect to see nothing anymore, since the file doesn't exist in the repository anymore.

### Native package manager behavior

n/a

### Images of the diff or a link to the PR, issue, or logs

n/a
Sept 20, 2022 (10 months ago with first warning?)
https://github.com/d3x0r/SACK/commit/2cb23f49455312080d9a24e5f588adec76ed2b54

I had even removed a reference to the file.
3 weeks ago
https://github.com/d3x0r/SACK/commit/81753a87eed222a987b91690b1d593611a25adad

**Comment by Bo98** [comment]
Seen similar issues with npm: https://github.com/Homebrew/actions/security/dependabot/3

Dependency was deleted 2 years ago: https://github.com/Homebrew/actions/commit/6ad9ecc5cefbadbfcacd4af73786f2bcd9d91557. Doesn't seem to be a branch issue as there is no old branches.

**Comment by mormegil-cz** [comment]
I have the same problem: Dependabot alerts about jQuery < 3.4.0 on four files (jquery.js, .min.js, .slim.js, and .slim.min.js) _which [have not existed](https://github.com/mormegil-cz/kdypojedevlak/blob/master/wwwroot/lib/jquery/jquery.js)_ in the repository for two years already (they have been moved [elsewhere](https://github.com/mormegil-cz/kdypojedevlak/blob/master/KdyPojedeVlak.Web/wwwroot/lib/jquery/jquery.js)). The repository does not have any branches or tags even, so no issue there.

**Comment by deivid-rodriguez** [comment]
Hello!

This repository only powers the creation of security updates for existing dependabot alerts, not the creation of the alerts themselves. That's responsibility of another team in Github. I suggest to open an [support ticket](https://support.github.com) to get in touch with them. Feel free to mention this issue in the ticket.

Also, I saw this reported as a [community discussion](https://github.com/orgs/community/discussions/60842) that looks quite similar, so feel free to post there any information that may be helpful to others regarding this issue.

I'll close this issue in favor of that discussion since a community discussion is a better fit given that the code that generates the alerts does not live in this repo.

Thanks!
