### ISSUE TITLE
Support for grouped update PRs that group across directories with same ecosystem

### ISSUE THREAD

**Issue by mx-psi** [dependabot/dependabot-core#7547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

On [open-telemetry/opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) we have 200+ Go modules that depend on each other. We currently have a manual system to group all the updates of these modules into a single PR that bumps all of these dependencies (see e.g. open-telemetry/opentelemetry-collector-contrib/pull/24175), since the current configuration we use creates 80+ PRs every single week (see e.g. [the PRs created yesterday, July 10th](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+created%3A2023-07-10)).

The recent grouped updates feature is a step in the direction that would make Dependabot more usable for our repository, but it only allows grouping updates per Go module. We would instead want to group all updates across all modules in a single PR, both for operational reasons (we don't have enough people to review all PRs) as well as to avoid manual changes (since some Go modules depend on other Go modules in the repository, bumping a dependency in one of them may imply bumping them also in others; making all updates in one go avoids having to do manual updates on Dependabot PRs).

Is this a supported feature of the grouped updates? If not, could it be considered as a feature request?

**Comment by spencerschrock** [comment]
+1 [ossf/scorecard](https://github.com/ossf/scorecard) has a similar problem with both our Go and Docker ecosystems. 

We have 7 Dockerfiles defined in our `dependabot.yml`, all of which depend on the same base image (`golang:1.19` currently). When there's an update, we get 7 PRs, 1 for each Dockerfile. If these could be grouped that would be a nice QoL improvement. Here's an example of the 7 dependabot PRs that I closed and submitted a manual PR instead.
* [Bump golang from 4b1fc02 to 6b3fa4b](https://github.com/ossf/scorecard/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+label%3Adocker+%22Bump+golang+from+4b1fc02+to+6b3fa4b%22)

**Comment by jmhbnz** [comment]
+1 - The etcd project are currently resorting to manual pr's each week to group updates due to a multi module structure and a need to bump a dependency in all places in one pr.  I believe a grouping across all modules in the project would resolve this.

**Comment by abdulapopoola** [comment]
To provide an update: we've started to investigate how to make this happen

**Comment by abdulapopoola** [comment]
Some update: This should be heading to beta within a month or less. Tagging @jurre , @jakecoffman , and @Nishnha

**Comment by jzabroski** [comment]
Oh heck yeah!! Thank you for pinning this issue as well. I'd love to beta test this if you tell me how.  I have tons of dependencies in my project and would make great use of groups.

**Comment by jzabroski** [comment]
@abdulapopoola How far off are we now from being able to use this?  It has technically been a month :)  Can't wait!

**Comment by abdulapopoola** [comment]
[here it is](https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/); open to hearing your thoughts as you try out the beta!

Tagging @carlincherry

**Comment by billinghamj** [comment]
We've just had our first one merge, seems to work great :) Looking forward to our first updates to GCP terraform providers

**Comment by ivanvc** [comment]
Hi @abdulapopoola, what would be a good channel to provide feedback regarding this beta feature? I'm testing it out in a Go project with multiple modules (`go.mod` files), but it seems like it's not working as expected.

**Comment by ex-nihil** [comment]
I tested out the new `directories` together with `groups`.

Using the `package-ecosystem: npm` it results in the same dependency being checked multiple times.
For instance, the jest dependency was requested a total of **76** times:
> GET https://registry.yarnpkg.com:443/jest/29.7.0

Regrettably, these redundant requests are causing timeouts for Dependabot, which is limited to a 45-minute timeframe.

**Comment by spencerschrock** [comment]
Tested `directories` with the 8 docker images in github.com/ossf/scorecard, and the first round of PRs only updated one of the docker images (`/Dockerfile`) and not the other 6 or 7.

## `distroless/base`

Only updated `/Dockerfile` (https://github.com/ossf/scorecard/pull/4064), while there were [6 more occurrences in specified directories](https://github.com/search?q=repo%3Aossf%2Fscorecard%20FROM%20gcr.io%2Fdistroless%2Fbase%3Anonroot%40sha256%3A29da700a46816467c7cb91058f53eac4170a4a25ac8551d316d9fd38e2c58bdf&type=code)

## `golang`

Again, only updated `/Dockerfile` (https://github.com/ossf/scorecard/pull/4063), while there were [7 more occurrences in specified directories](https://github.com/search?q=repo%3Aossf%2Fscorecard%20FROM%20golang%3A1.22.2%40sha256%3Ac4fb952e712efd8f787bcd8e53fd66d1d83b7dc26adabc218e9eac1dbf776bdf&type=code)

**Comment by billinghamj** [comment]
Similar here actually - it definitely doesn't seem to be working for our Terraform directories. We've just had it open a couple of PRs making updates in 1 directory, when they should actually have updated 6

- https://github.com/wearemojo/mojo/pull/8162
- https://github.com/wearemojo/mojo/pull/8161

**Comment by jzabroski** [comment]
OK, after adding properly configuring my dependabot.yml, I see a unique error in my logs that _only_ seemed to start happening with the introduction of grouped updates.  What's weird is that after I reverted my dependabot.yml, the audit logs changed in the Insights -> Dependency Graph -> Dependabot UI to suggest there was never any errors.  It's almost like the audit logs are tightly coupled to a version of the dependabot.yml somehow.

See the logs here https://github.com/fluentmigrator/fluentmigrator/network/updates/821783403

It seems like AWSSDK.S3 was fetched as 3.7.0.4

  proxy | 2024/04/30 16:40:42 [396] GET https://api.nuget.org:443/v3-flatcontainer/awssdk.s3/3.7.0.4/awssdk.s3.3.7.0.4.nupkg

and then later in the log, `NuGet.Versioning.SemanticVersion.Parse` cannot parse this dependency's version, presumably because it's not in semver format but legacy nuget format.  What's interesting is none of my dependencies are directly against the AWSKSDK.S3.  It must be a deep transitive dependency somewhere.
<details><summary>Details</summary>
<p>
updater | 2024/04/30 16:40:57 ERROR <job_821783403> Block argument of NuGetConfigCredentialHelpers::patch_nuget_config_for_action causes an exception Discovering build files in workspace [/home/dependabot/dependabot-updater/repo/src/FluentMigrator.DotNet.Cli].
updater |   No dotnet-tools.json file found.
updater |   No global.json file found.
updater |   Discovering projects beneath [src/FluentMigrator.DotNet.Cli].
updater |   No packages.config file found.
updater | Unhandled exception: System.ArgumentException: '3.7.0.4' is not a valid version string. (Parameter 'value')
updater |    at NuGet.Versioning.SemanticVersion.Parse(String value) in /opt/nuget/lib/NuGet.Client/src/NuGet.Core/NuGet.Versioning/SemanticVersionFactory.cs:line 22
updater |    at NuGetUpdater.Core.Discover.SdkProjectDiscovery.GetTransitiveDependencies(String repoRootPath, String projectPath, ImmutableArray`1 tfms, ImmutableArray`1 directDependencies, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs:line 113
updater |    at NuGetUpdater.Core.Discover.SdkProjectDiscovery.DiscoverAsync(String repoRootPath, String workspacePath, String projectPath, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs:line 69
updater |    at NuGetUpdater.Core.Discover.DiscoveryWorker.RunForProjectPathsAsync(String repoRootPath, String workspacePath, IEnumerable`1 projectPaths) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs:line 160
updater |    at NuGetUpdater.Core.Discover.DiscoveryWorker.RunForDirectoryAsnyc(String repoRootPath, String workspacePath) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs:line 125
updater |    at NuGetUpdater.Core.Discover.DiscoveryWorker.RunAsync(String repoRootPath, String workspacePath, String outputPath) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs:line 59
updater |    at NuGetUpdater.Cli.Commands.DiscoverCommand.<>c.<<GetCommand>b__4_0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/DiscoverCommand.cs:line 30
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext():
</p>
</details>

**Comment by magnusjtvisma** [comment]
For nodejs/npm this seems to work well. I'm having some problems with nuget though, I'm seeing this error for a lot of different packages:

updater | 2024/04/30 08:08:36 ERROR <job_821597127> Error processing MySqlConnector (Dependabot::DependabotError)
updater | 2024/04/30 08:08:36 ERROR <job_821597127> FileUpdater failed
updater | 2024/04/30 08:08:36 ERROR <job_821597127> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'

I'm also experiencing timeouts on some larger repositories. Perhaps that's related to the issue mentioned by a comment above, or maybe it's just because the repo is huge.

**Comment by carlincherry** [comment]
> Hi [@abdulapopoola](https://github.com/abdulapopoola), what would be a good channel to provide feedback regarding this beta feature? I'm testing it out in a Go project with multiple modules (`go.mod` files), but it seems like it's not working as expected.

Hi @ivanvc thank you for raising this to the team; this is unexpected behavior and we've created a https://github.com/dependabot/dependabot-core/issues/9664 which our team will prioritize fixing soon.

**Comment by carlincherry** [comment]
Hi @billinghamj we've created a [bug report](https://github.com/dependabot/dependabot-core/issues/9665) for this issue which we'll prioritize fixing soon. Thank you!

**Comment by carlincherry** [comment]
@spencerschrock we added Docker to this [bug report](https://github.com/dependabot/dependabot-core/issues/9664#issuecomment-2093435109) as well. Thank you!

**Comment by carlincherry** [comment]
Hi @jzabroski I'm sorry you experienced this behvaior; this is a known issue; our team is actively investigating and we'll update here as we investigate.

**Comment by carlincherry** [comment]
> updater | 2024/04/30 08:08:36 ERROR <job_821597127> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'

Hi @magnusjtvisma can you please give us more details about the error you're seeing? We suspect that this is a nuget issue and would like more details about the error logging to confirm. Please file as much information as you can in an [issue as a bug report](https://github.com/dependabot/dependabot-core/issues). Thank you!

**Comment by jzabroski** [comment]
> Hi @jzabroski I'm sorry you experienced this behavior; this is a known issue; our team is actively investigating and we'll update here as we investigate.

The problem is here: https://github.com/dependabot/dependabot-core/blob/da53246feba7084a36add3cef17970ebfe0017fd/nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs#L117

The code is assuming semantic versioning all-the-way down. At any rate, given this bug seems to be AWSSDK.S3, and is a Top 100 nuget package with 787,013,240 total downloads, I expect others will definitely have this problem.

I believe you want this version: https://github.com/NuGet/NuGet.Client/blob/0f32917aaba18c2db765fc7ad5bc95ebf12ec58d/src/NuGet.Core/NuGet.Versioning/NuGetVersionFactory.cs#L36

If you see the documentation, NuGetVersion is a superset of SemanticVersion, so it will properly handle these edge cases: (https://github.com/NuGet/NuGet.Client/blob/0f32917aaba18c2db765fc7ad5bc95ebf12ec58d/src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs#L9C1-L13C19

**Comment by brettfo** [comment]
Fix for the 4-part version is in #9689.

**Comment by billinghamj** [comment]
I have had a Terraform Dependabot PR work nicely with grouping + multiple directories today btw

**Comment by Fe1777** [comment]
Certainly! Here is a structured GitHub issue description and a detailed solution proposal for the feature request in the Dependabot Core repository about supporting grouped update PRs that group across directories with the same ecosystem.

---

## **Title:** Support for Grouped Update PRs Across Directories with Same Ecosystem

**Type:** Feature Request

**Reported by:** [User who reported the issue]

---

### **Description**

The feature request aims to introduce support for creating grouped update pull requests (PRs) that can span across multiple directories but within the same ecosystem. This would enable a more streamlined and efficient dependency update process for projects with a multi-directory structure sharing the same package management ecosystem.

### **Current Behavior**

Currently, Dependabot generates individual PRs for dependencies located in different directories, even if they belong to the same package management ecosystem. This can lead to numerous PRs, making it harder to manage and review dependency updates.

### **Desired Behavior**

Introduce functionality to:

- Allow users to configure Dependabot to group dependencies across different directories but within the same ecosystem into a single PR.
- Ensure that the grouped PR correctly updates all relevant files across the specified directories.

### **Use Case**

This feature is particularly beneficial for monorepos or projects that maintain separate directories for different parts of an application but use the same package management ecosystem (e.g., npm for frontend and backend folders).

### **Proposed Solution**

- **Implementation Details:**
  - Enhance the configuration to support specifying directories to be grouped together.
  - Update the grouping logic to accommodate dependencies from the specified directories into a single PR.

- **Example Configuration:**
  ```yaml
  version: 2
  updates:
    - package-ecosystem: "npm"
      directories:
        - "/frontend"
        - "/backend"
      schedule:
        interval: "daily"
      groups:
        shared-deps:
          update-types:
            - "all"
  ```

- **Technical Approach:**
  1. **Configuration Parsing:** Extend the Dependabot configuration parser to recognize and support multiple directories under the same ecosystem entry.
  2. **Dependency Detection:** Modify the dependency detection logic to scan the specified directories and aggregate dependencies.
  3. **Grouping Logic:** Ensure the new grouping logic can create a single update PR containing changes across the specified directories.
  4. **Testing and Validation:** Thoroughly test with various configurations to validate that changes are applied correctly and PRs are generated as expected.

### **Acceptance Criteria**

- [ ] Users can configure Dependabot to group updates across multiple directories with the same ecosystem into a single PR.
- [ ] Generated PRs correctly reflect changes to all listed directories and update the relevant files.
- [ ] Documentation is updated to explain the new configuration syntax and usage.

### **Benefits**

- Simplified dependency management for projects with multi-directory structures.
- Reduced number of PRs, easing the review and merge process.
- Consistent updates across related project components.

### **Impact**

There are no breaking changes anticipated with this feature. It will be an optional enhancement that users can leverage if needed.

### **Related Issues/PRs**

- **Potentially Related Issues/PRs:** 
  - [Link to any related issues or PRs]

### **Thank you!**

Thank you for considering this feature request! Grouping updates across directories within the same ecosystem will enhance the efficiency and manageability of dependency updates for multi-directory projects.

---

Feel free to adjust the template as necessary to fit any additional context or specifics of the feature request. This structured format aligns with standard GitHub requirements for issue reporting and provides a clear path for the solution implementation.

**Comment by jzabroski** [comment]
@carlincherry I think I'm a bit confused on how this feature is supposed to work now that the bugs blocking me seems to be addressed (thanks @brettfo).

As an example, npgql 8.0.1 had a security vulnerability and is referenced in two separate directories:

1. src/FluentMigrator.Runner.Postgres
2. test/

I'm only seeing a PR from dependabot as:

[fluentmigrator/fluentmigrator] Bump the third-party-dependencies group across 1 directory with 13 updates ([PR #1812](https://github.com/fluentmigrator/fluentmigrator/pull/1812))

Is this the expected behavior? If so, it doesn't match how Visual Studio package manager works. In any event, if dependabot will support the forthcoming new MSBuild slx solution file format, then I probably don't need this feature right now and can use slnx to teach dependabot my dependencies tree and to update multiple references to the same version.

**Comment by jzabroski** [comment]
@carlincherry Actually, think I figured out what is happening:

[fluentmigrator/fluentmigrator] Bump the third-party-dependencies group across 1 directory with 15 updates ([PR #1818](https://github.com/fluentmigrator/fluentmigrator/pull/1818))

1. It is incorrectly reporting the number of directories as 1 when it is really 3.
2. For some reason, likely due to TargetFrameworks, it is not upgrading dependencies in "src/FluentMigrator.DotNet.Cli" - this executable only targets modern frameworks, whereas Fluentmigrator.Conslole targets net48. I'll try to look through the dependabot  .NET code again to see why and revert back what I find.

**Comment by Nishnha** [comment]
Hi folks, this feature is now live! 🎉 
https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/

If you encounter any issues with this please reach out to GitHub support.

**Comment by marcofranssen** [comment]
> I have had a Dependabot PR work nicely with grouping + multiple directories today btw - with both Terraform and Go. Not sure if that's unexpected?
> 
> <img alt="Screenshot 2024-05-08 at 18 04 33" width="843" src="https://private-user-images.githubusercontent.com/905772/328976206-64842dd5-f4fa-42e3-a762-1bfc0e2ffbf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTYyOTgsIm5iZiI6MTczMDE5NTk5OCwicGF0aCI6Ii85MDU3NzIvMzI4OTc2MjA2LTY0ODQyZGQ1LWY0ZmEtNDJlMy1hNzYyLTFiZmMwZTJmZmJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwOTU5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Njc5ZTRhMWIxM2ZkODFmZWUwZDM3ZTkzNWIwYTJkMzM5ZDc3YWFkMGMzNWQ0ZTM1M2FlNTc3YTI1YmEwMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LcoNAkzBljX2P31idPoCmUlYP9OJKc0mYftNhILMIVk">

@billinghamj would you mind sharing the terraform configuration? I'm looking into grouping all PRs for similar module updates. E.g. I have a repo with many modules that all depend on same upstream modules. Now I get a PR for each of my own modules, but I would love to have it grouped by upstream depedency so I get one PR that updates them in all my modules.

**Comment by alexkunde** [comment]
For anyone who comes here for Terraform, this works:

```yaml
  - package-ecosystem: terraform
    groups:
      terraform:
        applies-to: version-updates
        dependency-type: production
    directories: 
    - '/terraform/**/*'
    schedule:
      interval: daily
      time: '03:00'
      timezone: Europe/Berlin
```

**Comment by billinghamj** [comment]
@marcofranssen ```
- package-ecosystem: terraform
  directories:
  - "**/*"
  schedule:
    interval: daily
  groups:
    google:
      patterns:
      - "hashicorp/google"
      - "hashicorp/google-beta"
```
