### ISSUE TITLE
Dependabot generates false security reports for jquery version

### ISSUE THREAD

**Issue by abraunegg** [dependabot/dependabot-core#7579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

N/A

### Package manager version

N/A

### Language version

N/A

### What you expected to see, versus what you actually saw

It is great that dependabot is generating security alerts like below:

![image](https://github.com/dependabot/dependabot-core/assets/4956234/d0baf6fb-72ab-4562-b3fb-6b4b854d219e)

and

![image](https://github.com/dependabot/dependabot-core/assets/4956234/cd0f1767-0ab2-4cd0-816a-8b64bc5c20aa)

However, the version of jquery being used is 3.7.x ..

![image](https://github.com/dependabot/dependabot-core/assets/4956234/124dc08f-8637-49d7-a031-15930830af17)

I would expect that alerts would be generated for actual valid items, not items are are invalid.

Additionally, dismissing / closing the alert does nothing - as dependabot raises this again.

**Comment by walro** [comment]
Take a look at #7198 and in particular https://github.com/dependabot/dependabot-core/issues/7198#issuecomment-1580334925 and https://github.com/dependabot/dependabot-core/issues/7198#issuecomment-1640472932.

I disabled+enabled "Dependabot alerts" on an affected repository and it seems to have done the trick, let's hope it doesn't re-emerge.

**Comment by hannob** [comment]
I'm also still seeing this. I already had opened bug #7198, which got closed, but the issue is unfixed.

I just got another alert here:
https://github.com/schokokeksorg/webinterface/security/dependabot/5

jquery was previously used in this codebase, but is completely removed now, and I already closed multiple false positive warnings.

**Comment by paul90** [comment]
Seeing the same problem - alerts for jQuery in [FedWiki/wiki-client](https://github.com/fedwiki/wiki-client), complaining about [jQuery 2.2.4](https://github.com/fedwiki/wiki-client/blob/master/client/js/jquery-2.2.4.js), you won't find it, it was removed earlier in the year.

**Comment by abraunegg** [comment]
Again today Dependabot alerted me for a non existent problem with jQuery:

![image](https://github.com/dependabot/dependabot-core/assets/4956234/c34a4930-5f86-4f22-ba0b-e84cf697408d)

The jQuery version in use is jQuery v3.7.0

**Comment by deivid-rodriguez** [comment]
Hello!

As @jurre mention [here](https://github.com/dependabot/dependabot-core/issues/7198#issuecomment-1580334925), this repository only powers the creation of security updates for existing dependabot alerts, not the creation of the alerts themselves. That's responsibility of another team in Github. I suggest to open an [support ticket](https://support.github.com) to get in touch with them. Feel free to mention this issue in the ticket.

Also, I saw this reported as a [community discussion](https://github.com/orgs/community/discussions/60842), so feel free to post there any information that may be helpful to others regarding this issue.

I'll close this issue in favor of that discussion since a community discussion is a better fit given that the code that generates the alerts does not live in this repo.

Thanks!
