### ISSUE TITLE
Move "Dependabot is rebasing this PR" to the top of the top comment

### ISSUE THREAD

**Issue by paulmelnikow** [dependabot/dependabot-core#784]
Thanks so much for this incredible tool. We use it in Shields and it's just been fabulous. 🌟

I'm here to suggest a minor tweak that's one of those "little big details." The amount of productivity Dependabot saves me makes me more aware of the times when it's slowing me down. 😉 

While I'm waiting for dependabot to rebase a PR, I'm often refreshing the page to see when the banner disappears. It would be helpful to move the warning message to the top, so it appears "above the fold," so to speak, making it more obvious when it's gone away.

<img width="1149" alt="screen shot 2018-11-17 at 11 21 26 am" src="https://user-images.githubusercontent.com/1487036/48663259-ab337580-ea5b-11e8-85b6-203312dc62f7.png">

…

<img width="1145" alt="screen shot 2018-11-17 at 11 21 36 am" src="https://user-images.githubusercontent.com/1487036/48663260-af5f9300-ea5b-11e8-8b46-1a9a0d7c6834.png">

P.S. I'd be happy to implement this, and other similar sort of developer experience tweaks, if you'd like to point me in the right direction.

**Comment by greysteil** [comment]
Sorry for taking so long to respond to this one @paulmelnikow! I read it a couple of weeks ago and thought "great shout - I'll do that tomorrow morning" only to drown under a sea of bugs for the next few days.

I've just implemented this, and it's deploying now. It's in the backend for the app (which keeps track of state etc.), rather than Dependabot Core, so it's not open source (yet...).

Thanks for the feedback, the kind words about Dependabot, and for all your work on Shields over the years! ❤️

**Comment by paulmelnikow** [comment]
Sweet! Thanks so much!

<img width="1039" alt="screen shot 2018-11-30 at 10 30 28 am" src="https://user-images.githubusercontent.com/1487036/49298286-fcdff500-f48a-11e8-9f18-dd19730cbb9a.png">
