### ISSUE TITLE
Install dependency via dist-tag

### ISSUE THREAD

**Issue by dwieeb** [dependabot/dependabot-core#807]
For npm dependencies, I believe dependabot looks at the `latest` dist-tag for what the latest version is. 

It would be nice to have a language-specific command like `@dependabot use dist-tag next`, for example, which sets the dist-tag to use for that dependency when looking for new versions.

Our use case is we'd like to use a `dev` dist-tag in separate repositories to install the latest dev version of a library in. Since our CI runs for PRs, a dependabot running our CI for a PR with each new dev version is an attractive feature.

**Comment by greysteil** [comment]
Interesting, thanks for the feedback.

My hunch is that this is one that we want to fix at the npm level, rather than just for Dependabot. Ideally there would be some way to specify that you want pre-releases for all dependencies in your `package.json`, or something like that.

On Dependabot specifically, we use the `latest` dist-tag version *if you're not already on a pre-release*. So if a dependency is specified to use `next` in your `package.json`, or if it's on a version that is a pre-release, you'll get updates to the latest pre, but if it's on a version that's equal to `latest` you'll track latest.

Does the above help? If you only want pres for a specific dependency then you could just set the requirement on it to be that dist tag and Dependabot will update the lockfile for you.

**Comment by dwieeb** [comment]
Yeah, I suppose I've seen this in action, actually. Dependabot does treat prereleases differently. Since our dev releases will be the most common prerelease, this will work 99% of the time for us. 👍 

Still, it would be comforting if dependabot could be told to ever only look at a particular dist-tag for a dependency. Here's a hypothetical use case: Take for example someone using the `next` tag to test the _next major version_ of a library, but still regularly creates current-version prereleases on a `nightly` tag. With current behavior (that dependabot opens PRs for whichever prerelease is the most recent), dependabot PRs would flip-flop between a v2 and a v3 of that library.

**Comment by greysteil** [comment]
👍 

Wouldn't that person then just specify the `next` tag in their `package.json`, and therefore hit [this logic](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/update_checkers/java_script/npm_and_yarn/latest_version_finder.rb#L86-L108) that means Dependabot will update their lockfile to use the latest version associated with that tag?

Either was Dependabot shouldn't flip-flop in that case - it will always update to the highest version pre-release that is related to the current pre ([this logic](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/update_checkers/java_script/npm_and_yarn/latest_version_finder.rb#L67)).

What am I missing here? Keen to make Dependabot smarter on this if we need to!

**Comment by dwieeb** [comment]
Oh, I see. I didn't know how to "tell" dependabot which dist-tag to use. Perhaps my knowledge of dependabot features is extra outdated.
