### ISSUE TITLE
Disable scheduled runs, allow manual-only dependabot usage

### ISSUE THREAD

**Issue by fregante** [dependabot/dependabot-core#8116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I want to use dependabot's updates, but only on request. Can you make `schedule.interval` optional? It looks like it's `required` now but I don’t think it needs to be.

The closest feature request to this would be:

- https://github.com/dependabot/dependabot-core/issues/6339

I'd then set `0 0 30 2 *` (February 30th)

**Comment by carogalvin** [comment]
@fregante thanks for submitting this request! I'm curious as to why you only want manual updates and not scheduled ones?

**Comment by fregante** [comment]
I find dependabot to be mostly noise, when you have a hundred repo the default behavior will trigger hundreds of PRs weekly. That's untenable. 

The choice would either be:

- open PRs every 6/10 months, just to keep the repos alive, or
- open them on demand whenever I return to a repo to work on it again

**Comment by carogalvin** [comment]
OK, so it sounds like you have a lot of repos that don't have a lot of active development, so you don't want to be spammed by tons of Dependabot PRs across these repos, but you still want the dependencies to be bumped every so often. Does that sound right?

**Comment by carogalvin** [comment]
@juandiana thanks for that feedback!

**Comment by sandstrom** [comment]
We would also like to disable the scheduled runs of Dependabot.

We like that it can open PRs manually via the 'Security' tab on a repo, to patch an individual CVE. However, we need to configure the labels it's using (the default labels doesn't work with our label structure). When we try to configure the labels using `dependabot.yml` we are also forced to activate the scheduling of dependabot.

For us, it would be great if we could disable it using one of the following:

1. `schedule.interval` was optional (and it wouldn't run if it wasn't set) or
2. `schedule.interval` could take the value `never`, to have it disabled.

**Comment by carogalvin** [comment]
@sandstrom a workaround for using `dependabot.yml` without enabling scheduled runs is to set `open-pull-request-limit: 0`. Then, Dependabot will still open security updates but not scheduled version bumps to latest.

Not ideal but might help with your use case here?

**Comment by sandstrom** [comment]
Thanks for helping out!

I know about it (and we use it). But our desire here was to disable that too, and only trigger dependabot manually via the security tab.

**Comment by abdulapopoola** [comment]
Let's continue the conversation in #6339

**Comment by karlhorky** [comment]
I see that #6339 was closed in April because the cron expressions feature was shipped:

- https://github.com/dependabot/dependabot-core/issues/6339#issuecomment-2821835933

But this feature did not enable the ability of configuring the automated PRs to "never" happen and only allow for manual request of Dependabot PRs.

IIUC the `open-pull-request-limit: 0` workaround doesn't work, because there should still be the ability of requesting a Dependabot PR manually (which would be greater than `0` open PRs).

@abdulapopoola can we reopen this request? What would be great would be either:

1. Setting [`interval`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#interval) to `never` or something similar
2. Setting an invalid cron expression like `0 0 30 2 *`
