### ISSUE TITLE
[npm] tilde is not respected during grouped version updates

### ISSUE THREAD

**Issue by ayushmanchhabra** [dependabot/dependabot-core#8122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 9.8.1

### Language version

Node.js v20.7.0

### Manifest location and content before the Dependabot update

https://github.com/nwutils/nw-angular-example/blob/43be0c2812fdd67538bcb20a90736a162cdb34fa/package.json

### dependabot.yml content

https://github.com/nwutils/nw-angular-example/blob/43be0c2812fdd67538bcb20a90736a162cdb34fa/.github/dependabot.yml

### Updated dependency

TypeScript: ~5.1.3 -> ~5.2.2
zone.js: ~0.13.0 -> ~0.14.0

### What you expected to see, versus what you actually saw

I expected typescript and zone.js to not be updated since the next version is a minor release not a patch release.

### Native package manager behavior

If dependency is prefixed with tilde, only update to patch releases.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/nwutils/nw-angular-example/pull/68

**Comment by ayushmanchhabra** [comment]
Just updated the links in the bug report - referenced a PR with a smaller diff.

**Comment by jakecoffman** [comment]
This is expected behavior. To achieve what you're after you can either set up [ignore rules](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) for the dependencies in question, or try the `lockfile-only` [versioning strategy](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy) which won't touch package.json.

**Comment by ayushmanchhabra** [comment]
Okay good to know! I think I'll setup an ignorw rule in this case.
