### ISSUE TITLE
gomod: go 1.21.3 not supported

### ISSUE THREAD

**Issue by lucacome** [dependabot/dependabot-core#8203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.21.3

### What you expected to see, versus what you actually saw

In my `go.mod` I have

```
go 1.21.3
```

and now dependabot fails to do anything with errors like

```
updater | 2023/10/16 06:27:05 ERROR <job_735517578> Error processing github.com/aws/aws-sdk-go-v2/config (Dependabot::DependabotError)
updater | 2023/10/16 06:27:05 ERROR <job_735517578> go: go.mod requires go >= 1.21.3 (running go 1.21.1; GOTOOLCHAIN=local)
```

I always assumed that dependabot would use the version specified in `go.mod` to run the updates, but looks like it isn't?

Maybe I'm missing something with the new go.mod versioning? Manually updating the go patch version every time a new version comes out is already getting old...

**Comment by jakecoffman** [comment]
Should be fixed now!

**Comment by lucacome** [comment]
yep it's working now, thanks @jakecoffman !

**Comment by deivid-rodriguez** [comment]
My understanding is that #8225 was not a permanent fix. It was made it so that quickly after each go release, we'll get a Dependabot PR to bump the version that Dependabot uses, and as soon as that PR lands, Dependabot is able to handle the new go release.

In this case, we should be getting a PR bumping go to 1.21.4 next Monday, and once that's merged it will be all good.

**Comment by jakecoffman** [comment]
Go was bumped in https://github.com/dependabot/dependabot-core/pull/8374 so it should be good now.
