### ISSUE TITLE
Dependabot configured, but shows 'Dependabot version updates aren't configured yet'

### ISSUE THREAD

**Issue by gxrsti** [dependabot/dependabot-core#8260]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

pnpm 8.6.8

### Language version

Node.js 18.16.1

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 15

### What you expected to see, versus what you actually saw

I expected dependabot to open pull requests and update my dependencies. Instead it shows as not configured.

Here is the link to my dependabot.yml: https://github.com/gxrsti/censor/blob/master/.github/dependabot.yml

**Comment by deivid-rodriguez** [comment]
Hi! This is probably an issue where the first push to a repository including a `dependabot.yml` won't be noticed by Dependabot, and it won't get activated. Can you push a dummy change to `.dependabot.yml`? I think it should get activated then.

**Comment by gxrsti** [comment]
> Hi! This is probably an issue where the first push to a repository including a `dependabot.yml` won't be noticed by Dependabot, and it won't get activated. Can you push a dummy change to `.dependabot.yml`? I think it should get activated then.

Hey! I tried this multiple times already, still not working.

**Comment by deivid-rodriguez** [comment]
Ah ok, that's not it then, sorry for the false alarm. Will let you know if I find out more.

**Comment by deivid-rodriguez** [comment]
Hei!

So I asked around and this is likely to be some issue that happened when Dependabot was first enabled in your account. Maybe some real bug in Dependabot, but in any case, it won't not be related to the logic that generates pull requests, which is the code this repository hosts.

Normally we recommend to open a [support ticket](https://support.github.com) for this kind of thing, so that this is tracked internally by the proper team at Github. Feel free to link to this ticket when you do that!

For now I'll close this issue to keep only issues that are relevant to dependabot-core. I hope you can get this problem sorted out!
