### ISSUE TITLE
False alert when package not actually installed via resolutions trick

### ISSUE THREAD

**Issue by christian-schwaderer** [dependabot/dependabot-core#8320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

1.22.19

### What you expected to see, versus what you actually saw

"grpc" used to get installed as a dependency of a dependency. However, since I do not use the part where grpc is used in that dependency and grpc installation caused me some issues, I use this trick to NOT install grpc at all:

```
resolutions: {
  "grpc": "link:./node_modules/.cache/null",
}

```

However, now, dependabot is alerting me about a vulnerability in grpc prior to 1.2.4. But that's a false alert since grpc is not installed all. So, I epxect not to get a dependabot alert.

**Comment by deivid-rodriguez** [comment]
Hello @christian-schwaderer 👋!

Terminology is a bit confusing but this repository is only in charge of generating pull requests with dependency updates. The creation of security alerts is handled by another team internally at Github.

I recommend you to open a [support ticket](https://support.github.com), so that your request can be properly redirected to the proper team. Feel free to mention this issue though for context when you do that.

Thanks!
