### ISSUE TITLE
Leave the Gemfile unedited if possible

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#846]
I like to think of the Gemfile version specifications as informative of the expected version support. For example, if my `nokogiri` dependency is `~> 1.2`, that means that I expect my application to work against any 1.x version higher or equal to 1.2. For example, because I needed a feature released with nokogiri 1.2 when I introduced the dependency.

When `dependabot` updates `nokogiri` to, say,  `1.3.0`, I would actually prefer the `Gemfile` to be left alone (unless changing it is needed to update the dependency), because it's not necessary, and because it obscures the reason why the version specifier was introduced.

Is this something you would be willing to change or to introduce as an option?

As always, thanks for `dependabot`!

**Comment by greysteil** [comment]
Since this is already configurable for other languages I've made it configurable for Ruby, too. If you got to the dashboard and click to edit any of your Ruby update configs you should be able to adjust the Gemfile update strategy to `Only increase version if necessary`.

Thanks for the feedback, as always!
