### ISSUE TITLE
Dependabot generates a PR branch name that is too long for Windows build systems

### ISSUE THREAD

**Issue by gsoedharmo-conga** [dependabot/dependabot-core#8565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

dotnet nuget

### Language version

C# .NET 8.0, NetStandard 2.0

### dependabot.yml content

https://github.com/akkadotnet/akka.net/blob/b7c2871e3a97456d9991abe0b5112691ef4ce441/.github/dependabot.yml

### Updated dependency

Dependabot main comment:

Bumps [Microsoft.Extensions.Hosting.WindowsServices](https://github.com/dotnet/runtime), [Microsoft.Extensions.Hosting](https://github.com/dotnet/runtime), [Microsoft.Bcl.AsyncInterfaces](https://github.com/dotnet/runtime), [Microsoft.Extensions.DependencyInjection](https://github.com/dotnet/runtime).Abstractions and Microsoft.Extensions.DependencyInjection. These dependencies needed to be updated together.
Updates Microsoft.Extensions.Hosting.WindowsServices from 7.0.1 to 8.0.0
Updates Microsoft.Extensions.Hosting from 7.0.1 to 8.0.0
Updates Microsoft.Bcl.AsyncInterfaces from 7.0.0 to 8.0.0
Updates Microsoft.Extensions.DependencyInjection.Abstractions from 1.1.0 to 8.0.0
Updates Microsoft.Extensions.DependencyInjection from 7.0.0 to 8.0.0

### What you expected to see, versus what you actually saw

The generated PR branch name is too long, causing Azure Windows image CI/CD to fail because git fetch lock file name exceeds windows file name length restriction

### Native package manager behavior

```
##[warning]Git fetch failed with exit code 1, back off 2.439 seconds before retry.
git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin  +refs/heads/*:refs/remotes/origin/* +refs/pull/7017/merge:refs/remotes/pull/7017/merge
error: cannot lock ref 'refs/remotes/origin/dependabot/nuget/Microsoft.Extensions.Hosting.WindowsServices-and-Microsoft.Extensions.Hosting-and-Microsoft.Bcl.AsyncInterfaces-and-Microsoft.Extensions.DependencyInjection.Abstractions-and-Microsoft.Extensions.DependencyInjection-8.0.0': Unable to create 'D:/a/1/s/.git/refs/remotes/origin/dependabot/nuget/Microsoft.Extensions.Hosting.WindowsServices-and-Microsoft.Extensions.Hosting-and-Microsoft.Bcl.AsyncInterfaces-and-Microsoft.Extensions.DependencyInjection.Abstractions-and-Microsoft.Extensions.DependencyInjection-8.0.0.lock': Filename too long
From https://github.com/akkadotnet/akka.net
 ! [new branch]          dependabot/nuget/Microsoft.Extensions.Hosting.WindowsServices-and-Microsoft.Extensions.Hosting-and-Microsoft.Bcl.AsyncInterfaces-and-Microsoft.Extensions.DependencyInjection.Abstractions-and-Microsoft.Extensions.DependencyInjection-8.0.0 -> origin/dependabot/nuget/Microsoft.Extensions.Hosting.WindowsServices-and-Microsoft.Extensions.Hosting-and-Microsoft.Bcl.AsyncInterfaces-and-Microsoft.Extensions.DependencyInjection.Abstractions-and-Microsoft.Extensions.DependencyInjection-8.0.0  (unable to update local ref)
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/akkadotnet/akka.net/pull/7017

**Comment by Gakk** [comment]
I get the exact same error. Everything worked fine when Dependabot created a single PR for each package, but after supporting to bump multiple packages together (in PR #8179), the path quickly gets too long and build breakes.

Not only does this affect the Dependabot branch, but every fetch from the remote fails on any branch for every developer.

**Comment by Nishnha** [comment]
Looks like nuget needs to add the `dependency_set` metadata when it creates it dependencies so the branch namer can use the group name instead of listing out all of the dependency names https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb#L24

Here's an example of how Gradle does it https://github.com/dependabot/dependabot-core/blob/1efd5e05e06f7ddefd7baf5bca3088af7626d0d6/gradle/lib/dependabot/gradle/file_parser.rb#L319-L324

**Comment by catsburg** [comment]
We're experiencing the same issue. All of a sudden we're getting a grouped PR (which we didn't configure) which breaks all CI builds for the repo because of the branch name length. I guess we'll have to ignore package updates for Microsoft.Extensions.* for now, to prevent this from happening randomly (our dependabot pipeline runs scheduled every night).

**Comment by Magnus-Ekstrom** [comment]
We just got this error as well. Very annoying. In our case the lock file and path would sum up to 263 characters.  
I can see that our enterprise does not have `LongPathsÈnabled` in Windows 10. So it could be related to that since I only see this error on my local machine.
`D:/repos/################/.git/refs/remotes/origin/dependabot/nuget/###.########.########.###/Microsoft.EntityFrameworkCore.Tools-and-Microsoft.EntityFrameworkCore.Design-and-Microsoft.EntityFrameworkCore-and-Microsoft.Extensions.Logging.Abstractions-7.0.15.lock`

Also, we have not enabled the beta feature "Grouped security updates":
![image](https://github.com/dependabot/dependabot-core/assets/90033704/a4efbc7f-6cfa-44b4-be8a-c586a33957f0)

But we still got this:
![image](https://github.com/dependabot/dependabot-core/assets/90033704/a9906e8d-6622-48f4-9a37-be5c7a2aa621)

Since we only saw this error locally we just decided to nuke that branch from the GitHub branch page.

**Comment by jakecoffman** [comment]
https://github.com/dependabot/dependabot-core/pull/9410 Should fix this after I cut a release of Dependabot Core and update our service to use it. I'll let you know when that's done so you can verify.

**Comment by jakecoffman** [comment]
I forked https://github.com/akkadotnet/akka.net to test https://github.com/dependabot/dependabot-core/pull/9410 and verified that the bump https://github.com/akkadotnet/akka.net/pull/7134 no longer has a branch name `dependabot/nuget/DotNetty.Handlers-and-Microsoft.Extensions.DependencyInjection.Abstractions-0.7.6` but is `dependabot/nuget/multi-ba72856d46`.

So going forward, branch names should be much shorter!
