### ISSUE TITLE
High private repo bandwidth usage / Ignoring Ignore rule.

### ISSUE THREAD

**Issue by anthony0030** [dependabot/dependabot-core#9246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

yarn 1.22.19

### dependabot.yml content

version: 2

updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 20
    target-branch: "development_anthony"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Athens"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directory: "/"
    target-branch: "development_anthony"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Athens"
    ignore:
      - dependency-name: "@fortawesome/fontawesome-pro"

  - package-ecosystem: "bundler"
    open-pull-requests-limit: 20
    directory: "/"
    target-branch: "development_anthony"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Athens"

### What you expected to see, versus what you actually saw

I am a Font Awesome pro subscriber, and I have Font Awesome ignored in dependabot.
There is a bandwidth limit now from Font Awesome. I believe dependabot is using bandwidth.

We requested the list of IPs that used bandwidth and saw that most of them (3/4) were from Dependabot. 
---> 18.213.123.130
---> 3.217.79.163
---> 3.217.93.44
X.X.X.X

Included are 3 IP addresses from Github which appear to be linked to GitHub's Security Updates (source: https://github.com/dependabot/dependabot-core/issues/2230#issuecomment-759459133). 

On our build server and local development computers, the packages are cached and only redownloaded when there is an update

I see in the update logs of dependabot
...
updater | 2024/03/08 06:29:18 INFO <job_797517549> All versions of @fortawesome/fontawesome-pro ignored, no update allowed
...
  proxy | 2024/03/08 06:29:38 [251] GET https://npm.fontawesome.com:443/@fortawesome/fontawesome-pro/-/6.5.1/fontawesome-pro-6.5.1.tgz
...

### Smallest manifest that reproduces the issue

version: 2
updates:
  - package-ecosystem: "npm"
    ignore:
      - dependency-name: "@fortawesome/fontawesome-pro"

**Comment by robmadole** [comment]
I'm one of the engineers at Font Awesome. I can help out with logs from the other side if they are useful. But I can't see currently how this would be related to our service provider (Cloudsmith) or anything to do with our package contents.

**Comment by anthony0030** [comment]
This issue seems related to https://github.com/dependabot/dependabot-core/issues/9196

**Comment by jeffwidman** [comment]
This is likely a side-effect of the way Dependabot leans into using native package managers. Most native package managers don't natively implement ignores. So instead ignores are implemented by Dependabot as a post-processing filter, after the native package manager does its thing.

So my guess is that the native package manager is making these calls.

However, we can't really switch to a pre-processing filter because it gets really tricky--many times the dep is intertwined with other deps, or the native package manager will yell at us if we try to munge the file.

Your best bet here is to get the native package manager to implement ignores natively, and then we could possibly pass those ignores into it to use internally. I say possibly because there's a lot of complexity around ignores, and figuring out a clean API to pass ignores into the native package manager can be very tricky. But some package managers are working on it, and if upstream is interested, we're very open to having a discussion with them.

Sorry there's not much we can do here.
