### ISSUE TITLE
Dependabot Security Updates & Gradle

### ISSUE THREAD

**Issue by nnellanspdl** [dependabot/dependabot-core#9351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

7.4

### Language version

Java 17

### Manifest location and content before the Dependabot update

/build.gradle

### dependabot.yml content

n/a - I'm using default Security Updates without a dependabot.yml file

### Updated dependency

pkg:maven/com.google.code.gson/gson@2.8.6

to

pkg:maven/com.google.code.gson/gson@2.8.9

### What you expected to see, versus what you actually saw

Per this [GitHub announcement](https://github.blog/changelog/2023-08-24-gradle-support-for-dependabot-security-updates/):  "_If you have used the dependency submission API to upload your Gradle dependencies to the dependency graph and are receiving Dependabot alerts for those dependencies, Dependabot will now try to open a pull request to resolve them automatically if you have security updates enabled_"

I am using the [official Gradle action](https://github.com/gradle/actions/blob/main/dependency-submission/action.yml) to submit my Gradle dependencies to the GitHub Dependency Submission API.  This is the method [recommended by GitHub](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api#using-pre-made-actions).

I am using a `build.gradle` file to declare my dependencies directly in a `dependencies{}` block.

After submitting to the Dependency API, the dependency does generate a Dependabot Alert.  However, a PR is not automatically opened (yes, I have Security Updates enabled).  If I go to that specific Dependabot Alert and try to manually open a PR for it, then I get an error:  "_This is an indirect dependency not explicitly present in any manifest file, so Dependabot cannot update it._"

Per the announcement linked above, I would expect this to work.

Do I need to declare my dependencies in a different file?  Perhaps Security Updates can't properly parse a `build.gradle` file?

**Comment by nnellanspdl** [comment]
When I click to view logs on the error, I see this:

```
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------------------------+
updater | |                Errors                |
updater | +--------------------------------------+
updater | | security_update_dependency_not_found |
updater | +--------------------------------------+
```

**Comment by hfhbd** [comment]
With Gradle you can use different methods to declare dependencies in Gradle, manually in your buildscript `implementation(...), platforms (BOMs) and by plugins.

To update a transitive dependency, you need to override the version by getting its Configuration, like `implementation`. The configuration isn't extracted by Dependabot or even stored in the Submission API at the moment at all.

=> Ideally, the Submission API supports storing the configuration name. Currently, there are predefined scopes, because it focus on npm. You could open the scope to allow custom values, here the configuration name.

To actually override a transitive dependency, you need to find the correct place add the block `dependencies { implementation(...) }` in the corresponding build file too.

But there are also detached configurations without an option to override a version.
