### ISSUE TITLE
Bump yarn-lib

### ISSUE THREAD

**Issue by Netail** [dependabot/dependabot-core#9378]
### Code improvement description

Yarn in yarn-lib got bumped to 1.22.22 (https://github.com/dependabot/yarn-lib/pull/56), however the package update has to be published to NPM and then the published version has to be updated in here

**Comment by Netail** [comment]
This currently introduces the bug back when dependabot creates a PR :(

**Comment by pavera** [comment]
I've published the yarn-lib package to npm and am working to get dependabot to create the update PR in this repo.

**Comment by pavera** [comment]
I've now deployed and merged the yarn-lib bump. This should be resolved.

**Comment by Netail** [comment]
Thank you :)

**Comment by BPScott** [comment]
Thanks @pavera! When do you expect this to be released? I see that a dependabot release was made just before #9531 was merged, are there plans for a fast-follow release to get this yarn fix in or shall it be next week?

**Comment by jeffwidman** [comment]
@BPScott typically the code for :dependabot: is deployed daily if not more frequently to GitHub cloud. 

The weekly release is primarily for the convenience of others who want to leverage Dependabot in custom ways via a versioned ruby gem.

So if you need it via RubyGems, you'll have to wait for the weekly release... otherwise it's already live.
